### ISSUE TITLE
Extraction of subdomains using certificates 

### ISSUE THREAD

**Issue by detonxx** [six2dez/reconftw#105]
Horizontal subdomain enumeration can be possible by using techniques to extract domains/subdomains through the certificates.

Using the following this could be made possible:

- [crt.sh](https://crt.sh/)
- Using [Certificate Transparency(CT)](https://transparencyreport.google.com/https/certificates) logs  (this gives some out-of-scope domsins)
- Using this [script](https://github.com/m4ll0k/CastleBravo/blob/9ff4de828b0e5c07da814c11ddf78a581af74170/tools/dns/passive/tools/subdomain.sh)

**Comment by six2dez** [comment]
More options:
- [crtfinder](https://github.com/eslam3kl/crtfinder) - The best imho
- [crtsh]https://github.com/famasoon/crtsh
- [subdomain_enum_crtsh.py]https://github.com/appsecco/bugcrowd-levelup-subdomain-enumeration/blob/master/subdomain_enum_crtsh.py

**Comment by six2dez** [comment]
Some considerations to do:

- crtfinder has a quick and deep option, deepest only with specific flag (-d for deep).
- all subdomains returned must end like ". target.tld", everything else removed. To keep in the list the others, another flag indicating "full scope" (-fs for example) must be added.
- crtfinder must have it's own function to add the hability to call it standalone.

**Comment by six2dez** [comment]
Closed 64932c280f3d5746751a224a361438f9116362a8
