### ISSUE TITLE
Urls inside subdomain folder

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#115]
Output of urlcheck function must be stored under one folder for each subdomain. This affects the next steps, cause must be in a loop for every subdomain folder.

**Comment by bileltechno** [comment]
Changes are done [here](https://github.com/bileltechno/reconftw/commit/d4b0abdbf342f7831fe1ba4197b2225078663c2d) 
but:
- files contains a lot of redundant  files.
``` .js
sed -ni '/^http/!d' $dir/urlcheck/$sub_out/${sub_out}.txt
```
needs to be reviewed it erase the files

**Comment by bileltechno** [comment]
:heavy_multiplication_x:  REJECTED :heavy_multiplication_x:
