### ISSUE TITLE
Error: GOPATH not set, but it is.

### ISSUE THREAD

**Issue by ichig069** [six2dez/reconftw#118]
I'm trying to run the install script but it keeps telling me that it is not set but I did set it.

    echo $GOPATH
    /home/ichig0/go

Is that the wrong way to do it?  I'm using Ubuntu 20.04  on linode.

**Comment by six2dez** [comment]
Please, take a look at the installation guide, [this](https://github.com/six2dez/reconftw/wiki#configuring-path-) section

```
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
```

**Comment by six2dez** [comment]
@ichig069 do you still need help on this matter?

**Comment by ichig069** [comment]
I got it past the GOPATH not set error. Figured out that I had to run it
without sudo, and then provide my password afterwards. I'm at about 50%
done so I should be good to go. Thanks bro!
