### ISSUE TITLE
Missing tools in Ubuntu....

### ISSUE THREAD

**Issue by syncinggreen** [six2dez/reconftw#119]
Hello,

I tried to install and run in Kali local machine , it works properly.

But , when i tried in Digital ocean Ubuntu droplet..**.it miss many tools like shodan,anew,nuclei and some more..**

If possible pls check

Thank so much,for coming up with such amazing project.

**Comment by six2dez** [comment]
Thanks for your feedback @syncinggreen. It seems that you don't have golang installed and its environment variables set correctly. Take a look [here](https://github.com/six2dez/reconftw/issues/118#issuecomment-770473277)

**Comment by syncinggreen** [comment]
Thanks , i have followed the installation step starting with Golang installation ...still faced the same issue...pls try once installation in fresh ubuntu machine...not all tools fails..but some.,,,and in fresh kali system. Everything works fine...

**Comment by six2dez** [comment]
@syncinggreen I have fixed an issue with the Chromium install right now that was breaking the rest of the package installation. If after update you are facing with same issues, try to send some information about errors commenting lines 9 and 10 of installer: ``#DEBUG_STD="&>/dev/null"`` and ``#DEBUG_ERROR="2>/dev/null"``

This will output every step of the installation process and then we can approach a solution for your problem :)

**Comment by six2dez** [comment]
Hi @syncinggreen can you give some feedback?
