### ISSUE TITLE
Issue in installation script

### ISSUE THREAD

**Issue by syncinggreen** [six2dez/reconftw#120]
there's a new issue after some recent updates , 

┌──(root💀kali)-[~]
└─# git clone https://github.com/six2dez/reconftw.git
cd reconftw
chmod +x *.sh
./install.sh
Cloning into 'reconftw'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 1000 (delta 11), reused 7 (delta 3), pack-reused 980
Receiving objects: 100% (1000/1000), 9.76 MiB | 2.05 MiB/s, done.
Resolving deltas: 100% (583/583), done.

**#######################################################################
 reconftw installer script (apt/rpm/pacman compatible)

./install.sh: line 30: syntax error near unexpected token `sudo'
./install.sh: line 30: `    eval (sudo apt install chromium-browser -y | sudo apt install chromium -y) $DEBUG_STD '**

Installation gets stopped after the above in both kali and ubuntu machines (no issues with golang)
it just quits and comes back to cmd

img - https://ibb.co/JRcYd6D

**Comment by six2dez** [comment]
You're right, fixed now 0b2e81dccf43e6860bd4bc95da12422239a41a8e
