### ISSUE TITLE
Empty ${domain}_url_extract.txt

### ISSUE THREAD

**Issue by bileltechno** [six2dez/reconftw#122]
**Describe the bug**
```.js
sed -ni '/^http/!d' ${domain}_url_extract.txt
```
:warning:  the above sed cmd delete ${domain}_url_extract.txt content. :warning: 

**Desktop (please complete the following information):**
- Architecture: x86
 - OS: Ubuntu

**Comment by six2dez** [comment]
Done 4601fcdfb82f3335abb8ffb83959e61b13273b55
