### ISSUE TITLE
New tools

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#123]
- [X] Golang [github-endpoints](https://github.com/gwen001/github-endpoints) instead it's python version

**Comment by bileltechno** [comment]
- [RustScan](https://github.com/RustScan/RustScan)
![scripts](https://github.com/RustScan/RustScan/blob/master/pictures/scripts.gif)

**Comment by six2dez** [comment]
Rustscan will not be implemented, the default parameters in RustScan are 4500 simultaneous connections and 1500 ms of rtt timeout, which can be done already in nmap with better results than this tool.

About rustbuster, I have problems installing in rpm distribution because of openssl versions. I will take a look again to check if I can make it works.
