### ISSUE TITLE
hakrawler

### ISSUE THREAD

**Issue by yaahiaa** [six2dez/reconftw#124]
what about hakrawler with gospider for crawling and availability to add cookies for hakrawler to make it efficiency ??

**Comment by six2dez** [comment]
I don't see the point as this is a bulk scan tool, I don't know how it would be useful to manage cookies for, say, around 1000 subdomains. Anyway, try to explain the idea a little more to see how we could fit it.

**Comment by yaahiaa** [comment]
you can add hakrawler and make the cookies be added manually like u did in ssrf collab server ... hakrawler very fast cuze it written in go lang .. and it can be used with cookies or not check the usage here https://github.com/hakluke/hakrawler , so if the user will use the amazing recontFTW <3 to test only one sub-domain (i do that ) he can add the cookies

**Comment by six2dez** [comment]
Ok, I will add this option soon, but I will keep gospider because it also supports cookies and the results obtained are usually better. Thanks, any other suggestion is welcomed :)

**Comment by yaahiaa** [comment]
thanks

**Comment by six2dez** [comment]
@yaahiaa Done e90e5f9a463aef1fc6f1ad4cbb2646887038a1b2

You can do it manually adding your cookies in line 18 ``COOKIE=""`` with this format ``testA=a; testB=b``
