### ISSUE TITLE
Installation process doesnt work properly.

### ISSUE THREAD

**Issue by jiyunatamashi** [six2dez/reconftw#14]
Dear Six2dez,

the installation script doesn't in KALI or ParrotOS fresh installed, nor updated. 

Best regards,

**Comment by a-oneil** [comment]
@jiyunatamashi The install script worked for me on Kali. What errors are you receiving on install or do you have any screenshots of the error?

**Comment by six2dez** [comment]
Please provide more information or screenshots, otherwise this issue will be closed @jiyunatamashi

**Comment by JKKSI** [comment]
> Please provide more information or screenshots, otherwise this issue will be closed @jiyunatamashi

Hello, i find this issue , and i have i think is error too with install.sh, when i run sudo chmod +x *.sh all fine, but when i tried sudo bash install.sh i get this... https://imgur.com/a/NcLmDcs , i try to do sudo bash update.sh and all worked fine, i try to do later sudo bash install.sh and get same error how in the screenshot that i show, do you can suggest me any solution?

**Comment by detonxx** [comment]
You need to install Golang...almost all the tools used in this script are written in Go....so install Go and then add them to your PATH.....then run ./install.sh

**Comment by JKKSI** [comment]
> You need to install Golang...almost all the tools used in this script are written in Go....so install Go and then add it to your PATH.....then run ./install.sh

would be great that you add in the script of install.sh this, because is install, so then would be great that this script install Golang i guess

**Comment by a-oneil** [comment]
![image](https://user-images.githubusercontent.com/18233106/105377736-231bfe00-5bd9-11eb-9a2e-cd66aafeab6e.png)
I get what you're saying, to add the install of the golang into the script but it's in the error message of install...

**Comment by detonxx** [comment]
For the Go to work you need to add them to your PATH which is done in the .bashrc...and the script doing changes in the .bashrc doesnt seem good...as this may mess up with other peoples tool executions...if your into bugbounty stuff you need Go configured properly as most of the tools are written in Go...if you have any doubts dm me @detonxx at twitter

**Comment by JKKSI** [comment]
mm ok, going to check, same thanks guys

**Comment by six2dez** [comment]
As the user has to install Golang on their own, this issue can be closed

**Comment by bileltechno** [comment]
Golang now is installed automatically
