### ISSUE TITLE
the tool is a bit slow 

### ISSUE THREAD

**Issue by Abzokhattab** [six2dez/reconftw#163]
Hello six2dez ,

Thanks for publishing this amazing tool in public ! i believe its the best recon tool so far  
however, there is a problem with it .. it takes so much time to finish and very often the execution hangs for so long without any progress so i think if its written in Go would be much faster 

Thanks

**Comment by bileltechno** [comment]
Hi @Abzokhattab،

Most of used  tools are developed using Go.

We implemented the --deep flag to go deeper and for more slow infogathering. If you run it without --deep it will be faster.

It depends also on target, Pc capacities and network speed.

We are benchmarkibg tools and choose the best and fastest. You can read the closed issues, and you will find some of those comparisons and tools replacement.

Thanks for using reconFTW and for valuable feedback.

**Comment by Sahabalam** [comment]
why this tool getting stuck after running nuclei high.
![reconftw](https://user-images.githubusercontent.com/46862651/146148946-3518b2ea-6a4e-4bda-a572-864125b1120d.png)
