### ISSUE TITLE
Sub_Brute only  in deep mode 

### ISSUE THREAD

**Issue by bileltechno** [six2dez/reconftw#168]
Sub bruting is time consuming:
- run it only in deep mode?
- if not DEEP wordlist = smallWordlist.txt

**Comment by 0-0eth0** [comment]
Hi @bileltechno 
I guess we should use smallwordlist instead of moving this on deep mode.

Regards,
0_0eth0

**Comment by six2dez** [comment]
Done https://github.com/six2dez/reconftw/commit/5f4a4930b931ba94cdffbc72216954f344e49205
