### ISSUE TITLE
Subdomain bruteforcing doesn't works on WSL Linux.

### ISSUE THREAD

**Issue by 0-0eth0** [six2dez/reconftw#169]
**Describe the bug**
Hi team,
As we discussed on group, i was testing this tool on my WSL Linux, i fulfilled all installation requirements, then i started my recon on this beast tool, it was running great but in between it got stuck on subdomain bruteforcing part, initially i thought maybe it takes time. But waited for almost 3-4 hours but didn't worked, maybe i dont know massdns isn't compatible with WSL linux, also i think nmap is not supported for WSL linux.

**To Reproduce**
1. Install this beast tool on WSL linux. 
2. After fulfilling all requirements, enter the target.
3. You will see it will fetch the passive subd enum but when it comes to subdomain bruteforcing, it will get stuck just next after crt.sh scanning.
4. Same with port scanning too.

**Desktop (please complete the following information):**
- Architecture: linux wsl.
 - OS: UBUNTU
 - Version: 20.04

**Comment by six2dez** [comment]
As said here https://github.com/microsoft/WSL/issues/2039, WSL has some limitations that can leads to issues with this tool and other security tools
