### ISSUE TITLE
OpenRedirX Killed

### ISSUE THREAD

**Issue by anasbousselham** [six2dez/reconftw#170]
`#######################################################################
 Open redirects checks
./reconftw.sh: line 877: 169240 Killed                  python3 /root/Tools/OpenRedireX/openredirex.py -l test_redirect.txt --keyword FUZZ -p /root/Tools/OpenRedireX/payloads.txt &> /dev/null`
I tried several times but I always have the same problem.

**Comment by bileltechno** [comment]
resolved ?

**Comment by six2dez** [comment]
Can't reproduce the bug, can you provide more info or something?

**Comment by anasbousselham** [comment]
I thins the problem is caused by my vps! 1cpu 2Ram, OpenRedirX is much snappier and more resource intensive.. Im looking for another alternative.
