### ISSUE TITLE
Merge all the subdomains from the txt files in all.txt

### ISSUE THREAD

**Issue by Md-Rasel-Bhuyan** [six2dez/reconftw#175]
Merge all the subdomains txt files in one file..

you can move the subdomain-related txt files to a specific directory.

and run below python code

![merge](https://user-images.githubusercontent.com/58187315/109052927-600e6f80-7706-11eb-8e47-797873ca34e0.PNG)

**Comment by six2dez** [comment]
I don't get the point to do that, all subdomains found already are in the same file

**Comment by bileltechno** [comment]
Hi @Md-Rasel-Bhuyan ;
We are using bash ,ot python;
All results already merged in ````${domain}_subdomains.txt and ${domain}_probed.txt````
```.js
if [ -f "${domain}_subdomains.txt" ]
then
	deleteOutScoped $outOfScope_file ${domain}_subdomains.txt
	NUMOFLINES_subs=$(wc -l < ${domain}_subdomains.txt)
fi
if [ -f "${domain}_probed.txt" ]
then
	deleteOutScoped $outOfScope_file ${domain}_probed.txt
	NUMOFLINES_probed=$(wc -l < ${domain}_probed.txt)
fi
````

**Comment by Md-Rasel-Bhuyan** [comment]
ops sorry my scanning is still running I was thinking maybe all the subdomains created separately

btw thanks a lot

Go ahead
