### ISSUE TITLE
SSRF Check enhancement

### ISSUE THREAD

**Issue by Anugrahsr** [six2dez/reconftw#176]
https://gist.github.com/hussein98d/d09b5990ff339dac8029b1e9248d2875

The ssrf check we have is looking for header injection, where in this way we can harvest the urls collected by wayback and filtered by gf to check for ssrf

**Comment by six2dez** [comment]
Done https://github.com/six2dez/reconftw/commit/e9d6c9c839b0e3e36f53dbec4d438a2c4ef9e327

**Comment by Anugrahsr** [comment]
that was a fast update
