### ISSUE TITLE
Trap Ctrl C

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#177]
Trap Ctrl C to skip current step

**Comment by gprime31** [comment]
Great idea and how about a pause menu, so i can switch vpn ip's then either resume current scan or skip to the next scan.

**Comment by six2dez** [comment]
It's a good option too, but also remember that when you cancel a scan and rerun the same target, the tool skip the steps already performed ;)

**Comment by 0xKourama** [comment]
not working
