### ISSUE TITLE
JS File Saving

### ISSUE THREAD

**Issue by notrickyyy** [six2dez/reconftw#186]
JS Files should have its own directory.

The directory could be:
_~/reconftw/Recon/Target.com/JS_
and here divided into each subdomains:

**sub.target.com**

Each directory will consist of;
api-endpoints and wordlists of its respective domain only.

And finally an ALL Directory which consist of:
1.API-endpoint of all subdomains
2.Wordlists of all subdomains
3Secrets of all subdomains;

This would allow an user to primarily focus on endpoints and wordlists belonging to specific domains according to his priority.

Also;
Line 717;
cat ${domain}_js_livelinks.txt | python3 $tools/getjswords.py | anew -q ${domain}_js_Wordlist.txt && touch $called_fn_dir/.${FUNCNAME[0]}

I was receiving lot of junk data(numbers)

Since a numeric value cant be a parameter in an ideal scenario.
So I believe its better to remove the numbers  and then save it.

**Comment by notrickyyy** [comment]
cat  js_wordlist.txt  | wc -l 
137174

cat js_wordlists.txt | egrep -v '[0-9]' | wc -l
85161

**Comment by bileltechno** [comment]
> JS Files should have its own directory.

The final results will be  presented for user in a HTML report. So the files organisations it is not that importatnt. chackt the #36 issue. 

> Also;
> Line 717;
> cat ${domain}_js_livelinks.txt | python3 $tools/getjswords.py | anew -q ${domain}_js_Wordlist.txt && touch $called_fn_dir/.${FUNCNAME[0]}
> 
> I was receiving lot of junk data(numbers)
> 
> Since a numeric value cant be a parameter in an ideal scenario.
> So I believe its better to remove the numbers and then save it.

This will be reviexed by @six2dez .

Thanks for your feedback.

**Comment by six2dez** [comment]
Done
