### ISSUE TITLE
While supplying a list of targets, gdorks isn't performing well!

### ISSUE THREAD

**Issue by 0-0eth0** [six2dez/reconftw#196]
**Describe the bug**
I have noticed that when I supply a list of the target to this tool, while gdorks it's taking the input of txt for example,

`Sub-subdomains (https://www.google.com/search?q=site%3A*.*.list.txt)`

Expected behavior:
It should read all the lines from list.txt & perform the Dorking according to that.

Regards,
Jinay.

**Comment by six2dez** [comment]
That's not the expected behaviour, with a list of targets reconftw makes one full execution for each line in list
