### ISSUE TITLE
add option skip phase like subdomin takeover

### ISSUE THREAD

**Issue by shadihh9** [six2dez/reconftw#199]
**Is your feature request related to a problem? Please describe.**
i have problem when test large scope i hope to skip phase like subdomain takeover
**Describe the solution you'd like**
i hope to add option to skip do all phase 
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or featui hope to add option to skip do all phase res you've considered.

**Additional context**

**Comment by six2dez** [comment]
You already can skip in reconftw.cfg config file
