### ISSUE TITLE
Any update on visual interface？

### ISSUE THREAD

**Issue by Jayway007** [six2dez/reconftw#204]
I found such an automated recon framework, it also has a graphical interface, which is very convenient for viewing the scan results
https://github.com/r3curs1v3-pr0xy/vajra/

**Comment by six2dez** [comment]
We are mainly focused on offering the best recognition tool and I think we are on the right track. A visual interface is a great addition, but not the main task, and at the moment there are only a few active contributors.

**Comment by Jayway007** [comment]
Yes, that’s great. I have used and compared several similar frameworks. and Reconftw is the best. I’m happy to join if I need any help.
