### ISSUE TITLE
XSS output error

### ISSUE THREAD

**Issue by goodrookie** [six2dez/reconftw#205]
Hey there, if anyone can help me, I'm obtaining in the XSS folder the XSS.txt file with this content, every time I scan:
[91m
	XSStrike [97mv3.1.4
[0m

Anybody knows what's wrong?
Is there a Telegram or Discord group to solve usage doubts? 
Thanks!

**Comment by six2dez** [comment]
This is because it doesn't found any XSS, anyway Telegram group link is in the README.md: https://t.me/joinchat/H5bAaw3YbzzmI5co

**Comment by goodrookie** [comment]
Great! I thought that was some error code. Thanks for the reply! I'll join you in Telegram, thanks again!
