### ISSUE TITLE
issue while scanning

### ISSUE THREAD

**Issue by knowthetech** [six2dez/reconftw#207]
Github Dorks in process 
Traceback (most recent call last):
  File "/root/Tools/GitDorker/GitDorker.py", line 343, in <module>
    sys.stdout.write(colored('%s' % new_url, 'white'))
NameError: name 'new_url' is not defined

**command used:** ./reconftw.sh -l domain -a -x exclude

**Comment by six2dez** [comment]
Seems like an error on GitDorker, there is already a similar closed [issue](https://github.com/obheda12/GitDorker/issues/18)
