### ISSUE TITLE
Issue with GO, Not Resolving even by adding path in both files

### ISSUE THREAD

**Issue by Nittonull** [six2dez/reconftw#213]
└─$ sudo ./install.sh                                                        127 ⨯

#######################################################################
 reconFTW installer script 

 Golang is already installed 

 GOPATH env var not detected, add Golang env vars to your $HOME/.bashrc or $HOME/.zshrc:

 export GOROOT=/usr/local/go
 export GOPATH=$HOME/go
 export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

**Comment by six2dez** [comment]
Hi,

First of all, test with latest version, this is a common error of the last versions but now it has been fixed.

Also, there is no need to run the installer with sudo, golang env vars are dependant of home user, so try to run as normal user.

**Comment by Nittonull** [comment]
I tried that as well but it really didnt worked at all,

└─$ ./install.sh 


#######################################################################
 reconFTW installer script 

 Golang is already installed 

 GOROOT env var not detected, add Golang env vars to your $HOME/.bashrc or $HOME/.zshrc:

 export GOROOT=/usr/local/go
 export GOPATH=$HOME/go
 export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

**Comment by six2dez** [comment]
I'm pretty sure that you're not running latest version cuz it installs go1.15.10... so try to get latest version and then try again ;)

**Comment by bileltechno** [comment]
`git pull`

to get the latest version

**Comment by Nittonull** [comment]
Thanks a lot it is working now, just one thing it is showing this still pending how to do it? 

#######################################################################
 Checking installed tools 

 [*] GOROOT var		[NO]
