### ISSUE TITLE
noob question - Am i using this right?

### ISSUE THREAD

**Issue by dookgit** [six2dez/reconftw#214]
Lets say i want to target house.com, and get all it's subdomains (e.g *.house.com)

Currently when i run **./reconftw.sh -d house.com -r** it ends up gathering domains i'm not interested in
e.g onthehouse.com or myhouse.com (So basically *house.com)

Am i running this wrong?  Or should i be using it like **./reconftw.sh -d .house.com -r**

Hope this makes sense.  I just want my domain plus *.domain stuff.  Cheers

**Comment by six2dez** [comment]
Hi!

This could be mainly for three reasons: 

- you're not using the latest version.
- you are running with fullscope flag (--fs) which may return this kind of results.
- you have set `FULLSCOPE=true` in reconftw.cfg config file. 

Please check these 3 cases and try again.

**Comment by dookgit** [comment]
Annnnndd, the winner is!

Not using the latest version.   Problem sorted.

Thanks heaps for the quick reply, and epic tool! :)
