### ISSUE TITLE
/usr/bin for shell scripts

### ISSUE THREAD

**Issue by michalswi** [six2dez/reconftw#221]
In all you shell scripts `/bin/bash` always point to `/bin`:
https://github.com/six2dez/reconftw/blob/main/install.sh#L1
https://github.com/six2dez/reconftw/blob/main/reconftw.sh#L1

Instead of `/bin/bash` I suggest to use `/usr/bin/env bash` , it will search for bash in $PATH and then start with the first one it can find

**Comment by six2dez** [comment]
Done
