### ISSUE TITLE
Running recon with the company flag and a targets list fails to touch tracking file.

### ISSUE THREAD

**Issue by brkb4mk** [six2dez/reconftw#230]
**Describe the bug**
When running with the `-m` and `-l` flags, a touch permission denied error appears throughout the output, for example.

`touch: cannot touch '/.subtakeover': Permission denied`

**To Reproduce**
1. run `./reconftw.sh -m company -l targets.txt -r`
2. follow output and see messages similar to `touch: cannot touch '/.subtakeover': Permission denied`

**Expected behavior**
The files should be placed in the correct directory relevant to the domain at the time to track the progress.

**Desktop:**
- Architecture: x86
 - OS: Arch Linux
 - Version Rolling

**Comment by six2dez** [comment]
Fixed in dev https://github.com/six2dez/reconftw/commit/228a049f4fa898efea216863c6870739fcab7a64
In a few days in main, thanks!
