### ISSUE TITLE
Post analysis of Output 

### ISSUE THREAD

**Issue by Nittonull** [six2dez/reconftw#232]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem but when the output of the tool checks manually and there are a lot of things we had to miss out because of heavy manual work that needs to be done, which should be avoided. Could you add some kind of a post-view or some kind of an HTML Report output for the results?

**Describe the solution you'd like**
I would like to see some kind of sorted layout maybe in HTML or anything else, where I can check and easily see and understand it.

**Describe alternatives you've considered**
I don't know I have not seen any of post analyses tools.

**Additional context**
For example when we generate a report view kinda response in Owasp Zap or something in simple HTML view that s helpful

**Comment by six2dez** [comment]
Duplicated #36
