### ISSUE TITLE
Sending Whole Recon Data Through Vps to Telegram 

### ISSUE THREAD

**Issue by pager5Cx415Cx415Cx69** [six2dez/reconftw#233]
In case you want your whole Recon data to your PC/Mobile. (Low Tech way) 

Sample Code (For Telegram)

#!/bin/bash

dir=~/Recon_Output/$1
zip -r ~/Recon_Output/$1.zip ~/Recon_Output/$1
curl -d "chat_id=-1111111" -d text="Hello: Your Recon on $1 is Completed. Output Result on the way. >>>> " https://api.telegram.org/bot123456789:BLABLABLA/sendMessage
curl -v -F "chat_id=-111111" -F document=@/home/reconpad/Recon_Output/$1.zip https://api.telegram.org/bot123456789:BLABLABLA/sendDocument

Better to skip the Screenshot folder (Large programs)

**Comment by six2dez** [comment]
Thanks! Done in dev https://github.com/six2dez/reconftw/commit/ef4a291e6e7e0c4cb4127ff8d3243bb4976121de
