### ISSUE TITLE
Could not open resolvers

### ISSUE THREAD

**Issue by d1pakda5** [six2dez/reconftw#237]
I am getting error:
Running : Nuclei Medium

[FTL] Could not open resolvers file: open /root/Tools/resolvers_trusted.txt: no such file or directory

but the file exist in that directory

**Comment by six2dez** [comment]
Fixed https://github.com/six2dez/reconftw/commit/cc5dbc606ae40ae518e895cc66a91bc77126572d

**Comment by detonxx** [comment]
This issue has been fixed.
Please run ```install.sh``` updater script again
```bash
./install.sh
