### ISSUE TITLE
Hangs on JavaScript scan 3/5

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#239]
![Screenshot_20210427-015713_JuiceSSH](https://user-images.githubusercontent.com/44535257/116192792-5308ff00-a6fc-11eb-9cc6-4550a7af5e3d.jpg)

**Comment by gprime31** [comment]
Hangs on 3/5 until ctrl+c they gives error ^^^^
Tried on arm64 and amd64 same result, everything is installed.

**Comment by six2dez** [comment]
reconFTW uses LinkFinder which takes time, it is not hung, it just takes some time. About the sed expression error, a solution has been uploaded, please run ./install.sh again to get the new changes.
