### ISSUE TITLE
Verify if tools are already installed before install them again

### ISSUE THREAD

**Issue by iNoSec2** [six2dez/reconftw#247]
Hi, it is not a feature i request but you must, in your install script, verify first if tools are already installed because installing multiple time the same tool with different location isnt a good thing, and you set the go path the same way but you must verify if it is already in the bashrc/zshrc file, etc etc it isnt a hard improvement since you just need to add things like this
`
if [ $(which gf) ];then
    :    
else
   go get blabla 
fi
` 
and for go path same thing

`
user_shell = $(echo $SHELL | cut -d '/' -f 4)
if [ $user_shell == "zsh" ];then
    cat ~/.zshrc | grep -i gopath
    some processing if you need the gopath elsewhere in your script
elif [ $user_shell == "bash" ];then
    cat ~/.bashrc | grep -i gopath
    some processing if you need the gopath elsewhere in your script
fi
`

etc etc

If you are interested i can make a pull request next month (lot of work this month, move to new house etc).

Thanks for your work!!!

**Comment by six2dez** [comment]
Good enhancement, but another point on install.sh is also update those tools, anyway we can try to discuss the better solution, thanks for raise this issue!

**Comment by six2dez** [comment]
The script already updates the tools installed or install the missing one, so the workflow is correct
