### ISSUE TITLE
[Question] massdns config location?

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#248]
can't seem to find the massdns config location, with --deep it kills my internet need to set --hashmap-size 5000
thanks

**Comment by six2dez** [comment]
Hi!
According to [installer](https://github.com/six2dez/reconftw/blob/09f9b2bdde4516cf5ac5a6cb60acb2ef9b7fbbc5/install.sh#L211)  it should bin inside /usr/bin anyway I have released a new version with rate limit option in cfg file to limit the number of req/sec https://github.com/six2dez/reconftw/releases/tag/v1.5.3

Run ./install.sh to be up-to-date :)
