### ISSUE TITLE
Full axiom integration

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#256]
- [x] Ffuf
- [ ] sqlmap
- [x] dnsx
- [x] s3scanner
- [ ] ip2provider
- [ ] CMSeeK
- [ ] jschecks
- [ ] Corsy
- [ ] OpenRedireX
- [ ] ssrf
- [ ] crlfuzz
- [ ] testssl
- [ ] brutespray
- [x] dirdar

**Comment by 0-0eth0** [comment]
Reconftw(axiom) has been merged with reconftw(classic) hence closing this issue.
