### ISSUE TITLE
Flag/mode to run single functions

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#257]

**Comment by itsgudenuf** [comment]
I was thinking the exact same thing!

**Comment by bileltechno** [comment]
When function depends the output of another, we shall check the existance of this output

**Comment by itsgudenuf** [comment]
In the meantime I can facilitate this by using an alternate cfg file. I need to do a PR of the command parser changes I've made. Will get around to it today.

**Comment by jakre1234** [comment]
Hey Devs,Any updates on this? Much required functionality, it should be nested flags.
./reconftw.sh -vuln -d target.com won't work good
why? Suppose I am done with Gf part and I am particularly interested in looking for XSS only so I have to go all over the vuln part and wait for ssti LFI etc checks to finsih as well. In that case we can have module/mode based flags like, 
./reconftw.sh mode -flag  i.e; ./reconftw.sh vuln -xss -f gf/xss.txt 
I Know this is hectic task, as each file may depend upon pervious output, but we need to create a flow chart...like which thing depends upon the previous output and in which order to run these flags
