### ISSUE TITLE
Compress data and send by tg, discord or slack

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#259]
- [x] zip output folder
- [x] send it

**Comment by bileltechno** [comment]
https://www.howtogeek.com/200698/benchmarked-whats-the-best-file-compression-format/

**Comment by six2dez** [comment]
Done on dev https://github.com/six2dez/reconftw/commit/ef4a291e6e7e0c4cb4127ff8d3243bb4976121de
