### ISSUE TITLE
[Question] where is the config for NOTIFICATION=true?

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#266]
where is the config for NOTIFICATION=true?
want to hook it to slack, set to true, can't seem to find the place to put my channel and api url.
thanks.

**Comment by bileltechno** [comment]
~/.config/notify/notify.conf

**Comment by six2dez** [comment]
Also check [this](https://github.com/six2dez/reconftw/wiki/1.-Post-Installation-Guide#notify-configuration)
