### ISSUE TITLE
/home/op/recon/puredns missing

### ISSUE THREAD

**Issue by itsgudenuf** [six2dez/reconftw#268]
inside the function resolvers_update()

the last thing done after the axiom-exec is
cp /home/op/lists/resolvers.txt /home/op/recon/puredns/resolvers.txt

however, that puredns directory does not exist on my latest reconftw axiom build directory 

I double check the axiom repo and there's nothing in the provisioners/reconftw.json where that directory is created

**Comment by detonxx** [comment]
Yup, the puredns tool got updated from a python version to Go....hence the changes are left to be made to the ```reconftw_axiom.sh```

**Comment by itsgudenuf** [comment]
It looks like it should probably be named /home/op/recon/puredns/trusted.txt as that's what the nuclei checks are calling with the -r option.

What's wrong with just pointing nuclei at /home/op/lists/resolvers.txt

**Comment by six2dez** [comment]
I will fix this asap. Just pointing puredns to /home/op/lists/resolvers.txt and /home/op/lists/trusted.txt. The reason for using trusted.txt in nuclei is that trusted resolvers always be available but some dns servers on resolvers.txt may fail.

Btw @itsgudenuf DM me on any social media plz I can't find you 😂

**Comment by six2dez** [comment]
Done in dev https://github.com/six2dez/reconftw/commit/4acc5789eacbf00833b8408255e2fa5d64257821
