### ISSUE TITLE
naabu doesn't handle empty input...

### ISSUE THREAD

**Issue by itsgudenuf** [six2dez/reconftw#269]
Reference: function webprobe_full()

previously with nmap if the "cat input" command in an instance was empty because there weren't enough entries in ./subdomains/subdomains.txt for all of the axiom instances.

What happens when you have fewer entries than instances, those instances with no input will happily just sit there waiting....

Also, the axiom naabu.json doesn't run as root so it's not possible to SYN connects.

I modified the axiom/modules/naabu.json file so the instance will exit when there is no input file.

```
[{
	"command":"[ ! -s input ] && exit 1; cat input | sudo /home/op/go/bin/naabu -o output",
	"ext":"txt"
}]
```
Currently testing on a 54 instance and this seems to work nicely.

Will submit an Axiom PR if there's not a better way to handle this in reconftw

naabu is fast!

**Comment by six2dez** [comment]
Yeah! The main reason to use naabu in that step is the speed. Maybe the better option is to fix the axiom's module, anyway I will think in any workaround until the PR is accepted.

**Comment by itsgudenuf** [comment]
PR submitted for Axiom.

The code snippet above works fine for anyone who doesn't want to wait for the PR

**Comment by six2dez** [comment]
Will wait to PR acceptance and then new version release, if the PR will not be accepted in a reasonable amount of time new version will be released and this issue will be pinned

**Comment by itsgudenuf** [comment]
Axiom PR #328 was just merge into Master.

**Comment by itsgudenuf** [comment]
For anyone else who might see this... naabu will hang indefinitely under certain circumstances.  
adding a timeout could be an alternative solution in
.axiom/modules/naabu.json
```
[{
	"command":"[ ! -s input ] && exit 1; cat input | sudo timeout 300 /home/op/go/bin/naabu -o output",
	"ext":"txt"
}]
```
