### ISSUE TITLE
Add -p 8082:8082 to docker command list

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#271]
Hi,
can you add ports to the docker command  (-p 81:81)  so we have a port open to run gowitness web server? or better yet for when aquatone arrives :)
Thanks.

**Comment by gprime31** [comment]
this works now:

1.	docker pull six2dez/reconftw:main
	2.	docker run -p 85-90:85-90 -it six2dez/reconftw:main /bin/bash 
	3.	exit
	4.	docker start $(docker ps -a|grep six2dez/reconftw:main|cut -d' ' -f1)
	5.	docker exec -it $(docker ps -a|grep six2dez/reconftw:main|cut -d' ' -f1) /bin/bash
	6.	exit
	7.	docker exec -it $(docker ps -a|grep six2dez/reconftw:main|cut -d' ' -f1) /bin/bash

**Comment by six2dez** [comment]
Good tip, but depends more on how the hunter want to use the container. Anyway thanks for the tip, it has been added to the wiki.
