### ISSUE TITLE
Wifi Router is down after running scan with "-a

### ISSUE THREAD

**Issue by obreinx** [six2dez/reconftw#275]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Architecture: [e.g. x86, x64, ARM ...]
 - OS: [e.g. Ubuntu, Kali, Arch ...]
 - Version [e.g. 20.04, Rolling, 8 ...]

**Additional context**

**Comment by detonxx** [comment]
hey @obreinx 
- This issue arrives when you run reconFTW on your home network.
- As the steps like, dns bruteforcing use massdns as a base to generate a enormous amount of concurrent requets which indeed kills your wifi.
- Hence, its recommended to run a scan on VPS

### **Fix:**

- You can edit the ```reconftw.conf``` config file which helps you to come over this situation.
- Set the value of the ```PUREDNS_PUBLIC_LIMIT ```` somewhere between 2000 to 10000 (depending on your preferences)
https://github.com/six2dez/reconftw/blob/main/reconftw.cfg#L132

This will solve your issue for sure ✌

**Comment by xxxNamasteHxxx** [comment]
I just try to change PUREDNS_PUBLIC_LIMIT but the result is same while Running : Permutations Subdomain Enumeration ,my router keep going down

**Comment by six2dez** [comment]
Then you should decrease even more that value, set something between 100 and 500 and then your router should be able to handle it. Otherwise this is not a reconftw issue but your hardware's limitation and reconftw has the option to adapt to your needs
