### ISSUE TITLE
Google dorks have 0 results now on docker build.

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#276]
Google dorks have 0 results now on docker build 1.6.0.
tried a few things but can't get it to work.

**Comment by gprime31** [comment]
Also can you put Aquatone in the build? I see the option for Axiom.

**Comment by gprime31** [comment]
Fine, but just so you know dorks work fine on 1.5 still but not on 1.6. I tested both, went back to 1.5 and dorks work fine.

**Comment by six2dez** [comment]
There must be something wrong on your side:

![image](https://user-images.githubusercontent.com/24670991/117555437-74a0a980-b05f-11eb-9332-0fb924bf83f6.png)

**Comment by gprime31** [comment]
> Google Dorks depends on Google policies, sometimes it doesn't return results, the unique solution is to renew your public IP. About aquatone, is just a temporal fix until gowitness is fixed, aquatone hasn't any update since 2019, so that's not the best option.

I know aquatone is old but I still think it's the best, hope you can integrate it at some point.
