### ISSUE TITLE
function jschecks() FIX for Docker 1.6.0

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#277]
It's linkfinder.py see below... No need to change recon.sh

**Comment by gprime31** [comment]
![2021-05-07_22-50](https://user-images.githubusercontent.com/44535257/117523561-0dafc180-af87-11eb-8e44-2b8ec16ab562.png)
A test from another machine -threads 2 same outcome.

**Comment by six2dez** [comment]
Unable to reproduce, I've running js checks under Docker without errors

**Comment by gprime31** [comment]
I'll try a fresh Docker pull later and see if it works on the latest version, was on 1.6.0
