### ISSUE TITLE
[Feature Request] Add an option to alert only when scan starts and finishes

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#284]
Add an option to alert only when scan starts and finishes for each domain rather than every scan type.
Thanks.

**Comment by six2dez** [comment]
Done on dev https://github.com/six2dez/reconftw/commit/1ccd8441bfa913f7a8a765138b2fa5c50fd92b97

Added SOFT_NOTIFICATION var on cfg file, just set it to true and the older "NOTIFICATION" var to false.
