### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by anasbousselham** [six2dez/reconftw#285]
**Describe the bug**
`cat: .tmp/probed_tmp_scrap2.txt: No such file or directory
cat: .tmp/probed_tmp_scrap3.txt: No such file or directory
find: ‘.tmp/gospider/’: No such file or directory
`
I have this error with `reconftw_axiom.sh -d domain.com -a`

**Comment by six2dez** [comment]
Added control errors on dev https://github.com/six2dez/reconftw/commit/e1d62444faa21e24fc9dae10e7dea8a0e68b7789

**Comment by anasbousselham** [comment]
The same error with the latest ver.
`cat: .tmp/probed_tmp_scrap2.txt: No such file or directory
cat: .tmp/probed_tmp_scrap3.txt: No such file or directory
find: ‘.tmp/gospider/’: No such file or directory
grep: .tmp/gospider.txt: No such file or directory
`
