### ISSUE TITLE
The install.sh script can hang when installing packages from apt

### ISSUE THREAD

**Issue by d3mondev** [six2dez/reconftw#289]
Hello hello!!

The install.sh script can hang during the `install_apt()` function when apt-get expects user interaction, even though the -y argument is provided.

To reproduce, execute the install.sh script in a fresh docker image of Ubuntu 20.04. The script will hang when installing tzdata, a dependency of chromium-browser.

Thanks! 🙌

**Comment by six2dez** [comment]
Thanks for the issue and the PR! Already merged on dev https://github.com/six2dez/reconftw/pull/292/commits/eadfcb86ee6c4d3a607cd82429eed151e28c3ebb
