### ISSUE TITLE
Reconftw not giving results

### ISSUE THREAD

**Issue by Krosskid12** [six2dez/reconftw#293]
![image](https://user-images.githubusercontent.com/73221787/118388128-3c423200-b642-11eb-9335-24060b374a0c.png)
![image](https://user-images.githubusercontent.com/73221787/118388134-45330380-b642-11eb-83cb-89a0313d6a2e.png)

**Comment by detonxx** [comment]
* Theres some issue on your side.
* I recommend to run `./install.sh` again and try on some different target.

**Comment by Krosskid12** [comment]
Okay thanks for your help.
