### ISSUE TITLE
CMS Checks

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#30]
Add CMS checks for the well known: WP, Drupal, Joomla

**Comment by Anugrahsr** [comment]
Look if this works
https://github.com/Tuhinshubhra/CMSeeK

**Comment by six2dez** [comment]
Checking also Vulnx, CMSScan and CMSmap

**Comment by six2dez** [comment]
255a1a5a2866a2319a3fa37e2628698dcd6ed8ec
