### ISSUE TITLE
Replace uddup or add the option to skip.

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#301]
UDDUP is only single core and takes forever. Can it be replaced with anything else? or the option to skip.
It takes less time with it commented out, uddup takes 12+ hours on a med-large domain, 4-5 hours with it skipped.
Thanks

**Comment by six2dez** [comment]
Done here https://github.com/six2dez/reconftw/commit/e6820cea716a4a0862a929dafd515ded978ef3d1 remember to run ./install.sh again
