### ISSUE TITLE
[Feature Request] add wc check option to all checks like the ssrf check

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#302]
Hi,
can you add 
if [[ $(cat gf/ssrf.txt | wc -l) -le 1000 ]]; then
else					
end_func "Skipping SSRF: Too many URLs to test, try with --deep flag" ${FUNCNAME[0]}
to all the functions so I can set a limit of ~2000, then it will require the --deep flag, otherwise it will skip.
(for large domains, then i can run the --deep later) just so it speeds up the initial scanning.
Thanks

**Comment by six2dez** [comment]
Good feature, I will add this thanks :)

**Comment by six2dez** [comment]
Done in dev  https://github.com/six2dez/reconftw/commit/331f728a23414639c31c155bc766dab02f624ef1

**Comment by gprime31** [comment]
Awesome, thanks.
Could you also put amass enum brute option in as well?
I see there is already massdns brute list, but amass adds to it, along with the amass active and passive already in place.
