### ISSUE TITLE
Affecting Wi-Fi connectivity

### ISSUE THREAD

**Issue by praveenvishnu1997** [six2dez/reconftw#308]
while using this commands ( ./reconftw.sh -d example.com -a --deep )
my Wi-Fi connectivity getting disconnected from all connected devices, seriously why it's happenning I don't know
This is only happening when I use reconftw tool
I am using it in virtual box - offensive security kali Linux

If I stop using reconftw tool, the my Wi-Fi connectivity getting normalized.
why this happened, still I don't know
But this issues is after the new update

**Comment by sidxparab** [comment]
@praveenvishnu1997 Please check out the FAQ section for the solution:

This is happening due to massdns making a high number of concurrent DNS queries
https://github.com/six2dez/reconftw/wiki/7.-FAQs#usage
