### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by zinminphyo0** [six2dez/reconftw#316]
just like this install cd reconftw/  git clone github.com/blabla ?

![2021-06-16_21-37](https://user-images.githubusercontent.com/74085414/122317457-90fbf580-ceeb-11eb-8106-53280a0bd48b.png)

**Comment by sidxparab** [comment]
Please run `./install.sh` again.
This will install all the remaining tools which weren't installed installed.

But if still any tool is not getting installed, than try installing it manually.

Also you can the telegram group to ask your questions: 
https://t.me/joinchat/TO_R8NYFhhbmI5co
