### ISSUE TITLE
Process Getting Killed

### ISSUE THREAD

**Issue by d1pakda5** [six2dez/reconftw#318]
I am getting this error
./reconftw.sh: line 444: 563104 Broken pipe             gotator -sub subdomains/subdomains.txt -perm $tools/permutations_list.txt -depth 1 -numbers 10 -md 2>> "$LOGFILE"
     563105 Killed                  | anew -q .tmp/gotator1.txt

**Comment by six2dez** [comment]
Hi!

Probably you're running out of disk space or using a very low specs vps. Keep in mind that permutations step creates multiples files sometimes bigger than 1gb. Also check in the wiki for an option available to remove temporary files at the end of the scan.
