### ISSUE TITLE
Secretfinder

### ISSUE THREAD

**Issue by chestervdb** [six2dez/reconftw#320]
**Is your feature request related to a problem? Please describe.**
Currently, valuable information of potential secrets on webpages are missing. (nuclei doesnt cover it all) 

**Describe the solution you'd like**
Addition of SecretFinder: https://github.com/m4ll0k/SecretFinder

**Describe alternatives you've considered**
Nuclei, but this doesnt cover most keys.

**Comment by six2dez** [comment]
Hi! 

Thanks for the suggestion, but SecretFinder works really slow with massive urls, that's the reason that it was dropped in favor of nuclei.

Thanks
