### ISSUE TITLE
Failed to cd directory in start @ line 1498

### ISSUE THREAD

**Issue by IamLucif3r** [six2dez/reconftw#323]
**Describe the bug**
Upon running the script :
``` 
sudo ./reconftw.sh -d target.com -r
```
I'm getting an error saying **Failed to cd directory in start @ line 1498**

**To Reproduce**
1. Go to 'Reconftw' directory
2. Run the script using sudo command,
3. scan a target

**Expected behavior**
The script should've start the scanning

**Screenshots**
![Screenshot at 2021-07-15 10-58-11](https://user-images.githubusercontent.com/53969258/125733670-42a7f1c0-eb61-4578-a138-d2289663bcd1.png)

**Desktop (please complete the following information):**
- Architecture: x64
 - OS: Parrot oS
 - Version Debian 5.10.28-6

**Comment by six2dez** [comment]
Fixed in dev, I will release a new version today :)
