### ISSUE TITLE
Out put with params only

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#324]
Like webs/url_extreact.txt  but with only parameters

instead of 
https://example.com/stuff?value=1234
just 
?value=1234
or even
value=1234

Thanks.

**Comment by six2dez** [comment]
Hi!

You should already have that wordlist on webs/dict_params.txt and webs/dict_values.txt

**Comment by gprime31** [comment]
Not there on any of the folders, just dict_paths.txt and dict_words.txt and url_extract.txt
Using 1.7.3(latest) and -a and --deep 
What could I be missing?

**Comment by gprime31** [comment]
I also have word list=true in the config
And I see it in the wordlist_gen function
Wonder why I can't get it to work?

**Comment by gprime31** [comment]
I also have in .tmp 
url_extract_tmp.txt
url_extract_,tmp2.txt
url_extract_uddup.txt

**Comment by gprime31** [comment]
Update: I see it now, but matter what site it's always wordlist_gen finished in 0 sec

**Comment by gprime31** [comment]
If I search the reconftw.sh for dict_ the only thing that shows up are paths and words.

**Comment by six2dez** [comment]
Hi! 

I have updated the tool with a new release with some modifications. If you don't have those files, probably you don't have params or values in the url_extract file. 

If you think the files must be created, check manually with these lines if it generates any output:

```
cat .tmp/url_extract_tmp.txt | unfurl -u keys | sed 's/[][]//g' | sed 's/[#]//g' | sed 's/[}{]//g' | anew -q webs/dict_params.txt
cat .tmp/url_extract_tmp.txt | unfurl -u values  | sed 's/[][]//g' | sed 's/[#]//g' | sed 's/[}{]//g' | anew -q webs/dict_values.txt
```

Thanks
