### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#33]
Minimum: working
Desirable: Alpine Linux minimal image

**Comment by mablanco** [comment]
I've already dockerized reconftw. Just found out about this open issue, so I wanted to let you know about my repo at https://github.com/mablanco/docker-reconftw

**Comment by six2dez** [comment]
Awesome work @mablanco ! Make a Pull Request to merge with the main project please!

**Comment by mablanco** [comment]
PR opened!
