### ISSUE TITLE
Js scan fix

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#330]
For the Js scan, need to delete grep domain$ part and fix the regex to look for:
url: /path
ajax (then look for /path)
anything that is:
 /path/ 
/path1/path2/
/path1/path2/path3/
Etc all the way to 10? Or so

I manually search for these things and the Js the way it is now never finds anything. So if you can make the Js scan after it finds the .J's files, scan them and grep for the things above and print the findings to a file, that would be awesome, I can't code otherwise I would help. However I do bountys full time and this would save alot of time, Thanks.

**Comment by gprime31** [comment]
grep for the path after  POST and GET also

**Comment by six2dez** [comment]
Let me work on it and I will push the changes for this. Thanks a lot!

**Comment by six2dez** [comment]
This was be fixed long time ago XD
