### ISSUE TITLE
Sub active

### ISSUE THREAD

**Issue by ghuiramu** [six2dez/reconftw#335]
In sub active function.....for dnsx we should give subdomain list and not a domain

So it should be cat subs_no_resolved.txt rather than echo $domain

**Comment by six2dez** [comment]
Hi!

In this function, dnsx it's only used to check if the root domain is active or not, the line before is resolving with puredns the entire subdomains list (subs_no_resolved.txt).

**Comment by ghuiramu** [comment]
oh ok thanks for letting me know.
