### ISSUE TITLE
dalfox 

### ISSUE THREAD

**Issue by ghuiramu** [six2dez/reconftw#336]
line number 1030 in reconftw.sh

it is [ -s "gf/xss.txt" ] && cat gf/xss.txt | qsreplace FUZZ | Gxss -c 100 -p Xss | anew -q .tmp/xss_reflected.txt

it should be like this

[ -s "gf/xss.txt" ] && cat gf/xss.txt | qsreplace FUZZ | Gxss -c 100 -p Xss | qsreplace FUZZ | anew -q .tmp/xss_reflected.txt

**Comment by six2dez** [comment]
Hi! 

Thanks for the suggestion, but that change doesn't matter, with Gxss we are only checking reflections, the urls which contains reflected params will be passed to dalfox, so it doesn't matter the param value, anyway I will change the value "Xss" to other less "offensive" like test_reflection or something like that

**Comment by ghuiramu** [comment]
My point is not about param value..

My point is the set of urls given to dalfox will be more 

example.com?x=fuzz&y=2
example.com?x=1&y=fuzz

Gxss gives this two urls...but basically these 2 urls are same...so we can we qsreplace and make it 1 url like example.com?x=fuzz&y=fuzz

**Comment by six2dez** [comment]
Oh! Sorry I didn't get you! Good point then I will fix and push asap!

**Comment by ghuiramu** [comment]
ok sure thanks

**Comment by six2dez** [comment]
ca35ee7a734456c4d83d4eb7454ec7f9ff408258
