### ISSUE TITLE
Emailfinder

### ISSUE THREAD

**Issue by ghuiramu** [six2dez/reconftw#338]
LIne number 179 in reconftw.sh

here emailfinder is giving only emails of the root domain only like
suppose we have root domain as example.com
it gives emails like hello1@example.com, hello2@example.com 

It is missing the emails of the subdomains like hello1@xd.example.com

So what we need to do this...After gathering all the subdomains of a root domain we need to feed them to emailfinder to get all the emails of root domain as well as subdomains as well

**Comment by six2dez** [comment]
Let me think about it, but is really unusual to use subdomains as email sender. Also, emailfinder uses search engines dorking as source, so if we make a lot of queries it will stop returning results. And finally, if we use emailfinder in every subdomain, it should be run in the rest of tools like theHarvester, h8mail, pwndb...

Thanks for all your suggestions!

**Comment by six2dez** [comment]
Running emailfinder or the other tools to every subdomain could take hours, I think it's better to perform this task manually or apart to reconftw
