### ISSUE TITLE
Diff support

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#34]
Run the tool and inform only for new discoveries comparing with the existing files. 
Like "Old scan detected", then results will be "3 new subdomains added".
Beware, it may interfere with resume run support added in c78d86240ce52cdac907bfe0132a45bff092fe86

- Flag -c for Compare or Cron mode
- After subdomains, rest of steps should be done only for new subdomains not all.
- Output and notifications about new findings, so it should compare and diff before.
- This feature shouldn't remove anything, just add.
- It should be able to run 24/7 in loop without bugs.

**Comment by KarahanGuner** [comment]
While using the DIFF mode, does it run Puredns on older subdomains in case one of the previously dead subdomains come alive?
