### ISSUE TITLE
OpenRedireX not work properly

### ISSUE THREAD

**Issue by conorxx1** [six2dez/reconftw#342]
Everytime I checked the redirect module, it says redirect finihed in 0 seconds, first I though there must be no gf pattern file for redirect bu when I look in gf folder redirect pattern has around 100 urls and still it finished in 0 seconds.

**Comment by six2dez** [comment]
Try to run the following commands manually from your target folder and tell me if it returns any error:

`cat gf/redirect.txt | qsreplace FUZZ | anew -q .tmp/tmp_redirect.txt` -> This will suppress and minimize duplicated urls
`python3 ~/Tools/OpenRedireX/openredirex.py -l .tmp/tmp_redirect.txt --keyword FUZZ -p ~/Tools/OpenRedireX/payloads.txt > openredirex_output.txt`  -> Run openredirex itself
`cat openredirex_output.txt | grep "^http" > vulns/redirect.txt` -> Clean the output

**Comment by conorxx1** [comment]
Traceback (most recent call last):
  File "/home/conor/Tools/OpenRedireX/openredirex.py", line 126, in <module>
    main()
  File "/home/conor/Tools/OpenRedireX/openredirex.py", line 108, in main
    asyncio.run(redirme(args.list, args.payloads, args.keyword))
AttributeError: module 'asyncio' has no attribute 'run'

**Comment by six2dez** [comment]
Try to reinstall or git pull in openredirex folder, it's working for me:

![image](https://user-images.githubusercontent.com/24670991/127615070-c0e0ac24-9efa-4b86-8fa7-ff3c4db4a7d6.png)
