### ISSUE TITLE
error: unknown option `show-current' when executing ./install.sh

### ISSUE THREAD

**Issue by Retr02332** [six2dez/reconftw#343]
# Description

When I run ./install.sh I get the following error

>error: unknown option `show-current'.

I think the above error is responsible for the repositories not installing correctly when I try to `-r` in some target.

The version of git I am using is:

>git version 2.20.1

# Possible fix

Digging around on the internet I noticed the following workaround for people who don't have the latest version of git:

* https://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git

For git versions before 2.22 you have to use:

>git rev-parse --abbrev-ref HEAD

instead of :

>git branch --show-current

# Reason why I opened the issue

You're probably saying "why don't you upgrade to the latest version?".

Well, I tried, but this is only possible with ubuntu systems and not debian apparently. My VPS is debian, so I found it very difficult to upgrade to that version.

For compatibility reasons I think it would be good to handle this error properly as I stated in the link above.

# Information about my machine

 * Debian GNU/Linux 10 (buster)
 * Linux 4.19.0-17-cloud-amd64 `#1` SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux

**Comment by six2dez** [comment]
I will use `git rev-parse --abbrev-ref HEAD` instead `git branch --show-current` as it works in every version.

Fixed in dev 214f379a313a4ef363daa35a4b8ed91ba4706ae5 you can run `git checkout dev && git pull` to update in this branch
