### ISSUE TITLE
mv: inter-device move failed

### ISSUE THREAD

**Issue by michyweb** [six2dez/reconftw#345]
**Describe the bug**
mv: inter-device move failed: '/root/Tools/reconftw/Recon/Multi' to '/tmp/output/Multi'; unable to remove target: Directory not empty

**To Reproduce**
target.txt -> testphp.vulnweb.com
docker run -v /root/test:/tmp/output six2dez/reconftw:main ./reconftw.sh -l /tmp/output/target.txt -w -o /tmp/output

**Expected behavior**
When running the tool via Docker with those args, it runs into a error due to the use of mv. I think it should use cp and then remove the folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/18649677/127856765-48296e64-741b-44da-a12d-f1e60b386ab1.png)

Thanks in advance

**Comment by michyweb** [comment]
Thanks!

**Comment by six2dez** [comment]
This was fixed on dev
