### ISSUE TITLE
Errors in LFI SSTI and all other fuzzing related vuln scanner

### ISSUE THREAD

**Issue by conorxx1** [six2dez/reconftw#346]
I was always getting empty files in LFI/SSTI  scan, then I decided to look what's going on behind the scene and found the follwing errors
      /'___\  /'___\           /'___\       
       /\ \__/ /\ \__/  __  __  /\ \__/       
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\      
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/      
         \ \_\   \ \_\  \ \____/  \ \_\       
          \/_/    \/_/   \/___/    \/_/       

       v1.3.1-dev
________________________________________________

 :: Method           : GET
 :: URL              : http://testphp.vulnweb.com:80/listproducts.php?cat=FUZZ
 :: Wordlist         : FUZZ: /home/conor/Tools/wordlists/lfi_wordlist.txt
 :: Header           : User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/2010010
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Regexp: root:
________________________________________________

:: Progress: [255/255] :: Job [1/1] :: 0 req/sec :: Duration: [0:00:00] :: Errors: 0 ::
Encountered error(s): 1 errors occured.
        * Keyword FUZZ defined, but not found in headers, method, URL or POST data.

Encountered error(s): 1 errors occured.
        * Keyword FUZZ defined, but not found in headers, method, URL or POST data.

Encountered error(s): 1 errors occured.
        * Keyword FUZZ defined, but not found in headers, method, URL or POST data.

Encountered error(s): 1 errors occured.
        * Keyword FUZZ defined, but not found in headers, method, URL or POST data.

        /'___\  /'___\           /'___\       
       /\ \__/ /\ \__/  __  __  /\ \__/       
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\      
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/      
         \ \_\   \ \_\  \ \____/  \ \_\       
          \/_/    \/_/   \/___/    \/_/       

       v1.3.1-dev
________________________________________________

 :: Method           : GET
 :: URL              : http://testpho.vulnweb.com:80/comment.php?aid=FUZZ
 :: Wordlist         : FUZZ: /home/conor/Tools/wordlists/ssti_wordlist.txt
 :: Header           : User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/2010010
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Regexp: ssti49
________________________________________________

:: Progress: [12/12] :: Job [1/1] :: 0 req/sec :: Duration: [0:00:00] :: Errors: 12 ::
Encountered error(s): 1 errors occured.
        * Keyword FUZZ defined, but not found in headers, method, URL or POST data.

Encountered error(s): 1 errors occured.
        * Keyword FUZZ defined, but not found in headers, method, URL or POST data.

Encountered error(s): 1 errors occured.
        * Keyword FUZZ defined, but not found in headers, method, URL or POST data.

Encountered error(s): 1 errors occured.
        * Keyword FUZZ defined, but not found in headers, method, URL or POST data.

**Comment by six2dez** [comment]
Hi!

I tried to reproduce the issue, but it's working for me:

![image](https://user-images.githubusercontent.com/24670991/129316579-62bc191a-70b6-40d2-a472-a69fa33a294d.png)
