### ISSUE TITLE
403bypass FIX

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#347]
line 793:
interlace -tL webs/webs.txt -threads 10 -c "ffuf -mc all -mc 200 -ac -t ${FFUF_THREADS} -sf -s -H \"${HEADER}\" -w ${fuzz_wordlist} -maxtime ${FFUF_MAXTIME} -u  _target_/FUZZ -of csv -o _output_/_cleantarget_.csv" -o fuzzing 2>>"$LOGFILE" &>/dev/null

change to:
interlace -tL webs/webs.txt -threads 10 -c "ffuf -mc 200,401,403 -ac -t ${FFUF_THREADS} -sf -s -H \"${HEADER}\" -w ${fuzz_wordlist} -maxtime ${FFUF_MAXTIME} -u  _target_/FUZZ -of csv -o _output_/_cleantarget_.csv" -o fuzzing 2>>"$LOGFILE" &>/dev/null

the 2nd -mc 200 over rides the -mc all.

now line 1262 will work :)
cat fuzzing/*.txt 2>>"$LOGFILE" | grep -E '^4' | grep -Ev '^404' | cut -d ' ' -f3 | dirdar -threads $DIRDAR_THREADS -only-ok > .tmp/dirdar.txt

**Comment by six2dez** [comment]
Thanks for the suggestion about ffuf, that will be fixed, but 403bypasser module has been dropped out in dev branch (and soon in main) because 403 bypasses are like a unicorn only shown in ctfs and very specific scenarios, and it does not worth to run for every 403 found

**Comment by gprime31** [comment]
Ya, only admin panels on nginx that I have seen work so far.
