### ISSUE TITLE
can you add here this tool | GO111MODULE=on go get -u github.com/xm1k3/cent

### ISSUE THREAD

**Issue by 4riful** [six2dez/reconftw#348]
GO111MODULE=on go get -u github.com/xm1k3/cent
 add this tool  for update  nuceli templates

**Comment by six2dez** [comment]
Cent is used to download and keep updated a lot of third party nuclei templates, in most of the cases duplicates or not well designed causing errors. In reconFTW nuclei templates are updated on every run and I prefer to stick to the official templates for the moment, anyway you can add any template to your templates folder.
