### ISSUE TITLE
pwndb

### ISSUE THREAD

**Issue by etaylor77** [six2dez/reconftw#357]
Currently when running with -a, I am getting an error that "pwndb is currently down  :("

I check the onion site and everything is fine. Can you advice on the config settings for this?

**Comment by six2dez** [comment]
It just make a test with curl and 15s of timeout https://github.com/six2dez/reconftw/blob/01b407b094bddc325deee26f5cfed047ea3e8d33/reconftw.sh#L201 if your connection is slow or the site is overloaded, it will return false negative, I can update it to 30s
