### ISSUE TITLE
Configuration API Key

### ISSUE THREAD

**Issue by tXambe** [six2dez/reconftw#358]
Hello,

I finished the installation without problems but when I want add API Key (for example in amass) I don't have this route:

AMASS_CONFIG=~/.config/amass/config.ini

or 

$HOME/.config/subfinder/config.yaml

Where is this files ? 

A greeting and thanks

**Comment by six2dez** [comment]
It should be created on install, make sure you're running the latest version and try running installer again. Anyway running once subfinder and amass, should create that files (but installer should do itself).

**Comment by tXambe** [comment]
Hello,
I'm running the last version I have tried to install again and those folders have not been created. Can I can create those folders / files by hand ?

A greeting and thanks

**Comment by six2dez** [comment]
Yes of course, you can create them manually :)
