### ISSUE TITLE
Unable to install crobat

### ISSUE THREAD

**Issue by jonatanexe** [six2dez/reconftw#359]
The url to install crobat is wrong and returns an error in the installation, it should be:
`gotools["crobat"]="go get -u -v github.com/cgboal/sonarsearch/cmd/crobat"`
instead of:
`gotools["crobat"]="go get -u -v github.com/cgboal/sonarsearch/crobat"`

**Comment by six2dez** [comment]
Yes, it has been updated recently, I'm already pushing to the changes, thanks :)
