### ISSUE TITLE
Source code Scraping subdomain

### ISSUE THREAD

**Issue by BlasterX24** [six2dez/reconftw#362]
While doing full **recon+attacks** it always get stucked at this step. Its been 3hrs and its still not finished is it normal?

**Comment by six2dez** [comment]
Depends completely on the target size, can't help on that. What you can do is increase gospider threads on cfg file.

**Comment by sidxparab** [comment]
The execution time for source-code scraping mainly depends on how large the target is. **Gospider** is used for source code scraping.

What u can do check:
1) If `htop`  command shows gospider running, that's means the scan is running.
2) Do `ls -alpts` in the `reconftw/Recon/target.com/.tmp` directory, now check the time of the file at the top. If you see a huge difference between the current time and the last time the file was updated that means, gospider isn't running.

Moreover, if you want u can disable "source code scraping" from the config file by setting `SUBSCRAPING=false
` on line 56
