### ISSUE TITLE
sudo is not working in docker container

### ISSUE THREAD

**Issue by wtwver** [six2dez/reconftw#364]
Docker container is running as root and without sudo installed. 

```
./reconftw.sh: line 788: sudo: command not found
```

Possible Solution
1. install sudo in install.sh
2. Remove all sudo in reconftw.sh (might break in native env)

**Comment by six2dez** [comment]
Fixed in dev branch, thanks! https://github.com/six2dez/reconftw/commit/a9cbff4d5bdfc47503ebc2cba40679d2ad6eb694
