### ISSUE TITLE
OpenRedireX is too buggy

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#366]
OpeRedireX is too buggy and never works, after a lot of efforts was able to make it work then after few seconds a lot of SSL errors,
SSL error in data revived . Use some other tool for openredireX

**Comment by jakre1234** [comment]
Maybe Oralyzer https://github.com/r0075h3ll/Oralyzer

**Comment by six2dez** [comment]
Thanks! that was on my backlog for a long time, already pushed to dev here https://github.com/six2dez/reconftw/commit/142de0968df378c921332da37d94bd8c8f82d120
