### ISSUE TITLE
had to install several python modules

### ISSUE THREAD

**Issue by Costly** [six2dez/reconftw#373]
Hi, 

i had to manually install several python addons after a fresh checkout + install yesterday.

apt install python3-aiodns
apt install python3-aiohttp
apt install python3-aiosqlite
pip install orjson
apt install python3-uvloop
pip install aiomultiprocess

Got these from error messages in the .log/2021-*.txt logfile mainly from the TheHarvester script.

Also a single target -r recon got stuck several times and is not running through smoothly. I had to skips several steps with Ctrl+C for resume after hours of waiting. Are there any known issues? Maybe problems with using a digital ocean droplet?

Best Regards

**Comment by six2dez** [comment]
Fixed in dev https://github.com/six2dez/reconftw/commit/311c42b39f3fbe2c81bacdd4f352dba2849e11fc Thanks!
