### ISSUE TITLE
Very strange error

### ISSUE THREAD

**Issue by Oldman19** [six2dez/reconftw#375]
![image](https://user-images.githubusercontent.com/58176451/132277851-05a40915-eb63-4ed9-bc4d-0d10c4dc3889.png)
As shown in the picture above, I don’t know if he is running normally now or why he reported an error. How can I fix him?

**Comment by jakre1234** [comment]
That's really strange...haha lol

**Comment by gprime31** [comment]
Looks like gospider ran out of ram.

**Comment by six2dez** [comment]
Yes, seems to be more a resources problem than reconftw issue :/ sorry dude. Try to run in a host with more resources or a smaller target and let us know if it has solved.
