### ISSUE TITLE
reconftw crashes during web screenshot

### ISSUE THREAD

**Issue by evanRubinsteinIT** [six2dez/reconftw#377]
**Describe the bug**
I recently started to use reconftw in my workflow, and discovered a weird issue when I get to the web screenshot segment. For some reason, after a few seconds, my screen turns black, I am logged out of my machine, and when I log back in, there is no longer an instance of the terminal running. Every piece of information obtained during the previous stages is still accesable, but no screenshots, and nothing after that point.

**To Reproduce**
1. Go to the reconftw directory
2. Type "./reconftw.sh -d domain -r"
3. Wait until the software gets to the web screenshot stage, and the error occurs

**Expected behavior**
Based on what I read on the main page, and the video footage I've seen, I would expect 
**Screenshots**

**Desktop (please complete the following information):**
- Architecture: [Virtualbox, 64 bit]
 - OS: [Kali Linux]
 - Version [2021.2.]

**Comment by six2dez** [comment]
Seems to be more a resources/overload on your VM than a reconftw problem, can you add more information? Also, check the log file generated on your target's folder if there is any information about the crash
