### ISSUE TITLE
The file in the .tmp directory is too large during operation, resulting in insufficient storage and unable to operate normally

### ISSUE THREAD

**Issue by Oldman19** [six2dez/reconftw#380]
As shown in the figure:
![image](https://user-images.githubusercontent.com/58176451/133819738-a035c79d-dbf4-435b-a76e-0b0c2dfdef00.png)
Although I have 80g of space, it is full when I run recon. Is there any solution? Can I delete the files in the .tmp directory while the program is running?

**Comment by sidxparab** [comment]
The `gotator2.txt` is the output from the tool [Gotator](https://github.com/Josue87/gotator). This file contains the different permutations of your subdomains which later will be resolved to find the valid ones. 

But currently, you have given a target that contains a relatively large number of subdomains, and thus the permutations of those subdomains are so high that it amounted to an output file of 54 GB. 

However, the next step the reconftw performs after resolving `gotator2.txt` is to delete this heavy-size file immediately. But in your case, gotator was executing and generated such large permutations that you reached your maximum storage space in the middle of the tool execution. 

So, I guess you have left with 2 options:
1) Disable permutations by setting `SUBPERMUTE=false` in the reconftw.cfg configuration file.
2) Do not run scan with **--deep** flag
