### ISSUE TITLE
i can't install axiom and mildew

### ISSUE THREAD

**Issue by ahmedmahmoud5** [six2dez/reconftw#383]
i used gcp and heroku  to install reconftw for start recon but last update when i install tools axiom and mildew not install i tried everything but nothing i hope to solve this problem thank you

**Comment by six2dez** [comment]
If you can't install just axiom or mildew, you should try to take a look in their repositories for the correct installation methods. Anyway I've installed reconftw today and nothing fails in the installation process.

**Comment by vpsfree13** [comment]
i hope to update docker hub container for reconftw to last release v2.0.1
