### ISSUE TITLE
six2dez/reconftw:main not found

### ISSUE THREAD

**Issue by 0xhunster** [six2dez/reconftw#386]
six2dez/reconftw:main not found
![image](https://user-images.githubusercontent.com/46501627/134795545-84861f35-1b16-41f2-ae9c-460f13349c2b.png)

**Comment by six2dez** [comment]
I removed main and dev tags in DockerHub since they removed the auto build feature for free accounts. While I'm trying to find a workaround to this, please build it locally with the Docker file provided. Thanks

**Comment by 0xhunster** [comment]
Can I build it ubuntu machine?

**Comment by six2dez** [comment]
Yes, of course, you shouldn't have any problem

**Comment by wtwver** [comment]
> I removed main and dev tags in DockerHub since they removed the auto build feature for free accounts. While I'm trying to find a workaround to this, please build it locally with the Docker file provided. Thanks

The github action should be able to auto build docker image, is it working as intended?

**Comment by six2dez** [comment]
Fixed, both main and dev tags, and Github Actions auto build
