### ISSUE TITLE
git-hound replacement

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#39]
Look an alternative for git-hound, maybe GitGraber or truffleHog works

**Comment by bileleljaamiibugbounty** [comment]
What is the main problem with git-hound?

**Comment by bileltechno** [comment]
What is the main problem with git-hound?

**Comment by six2dez** [comment]
Just make some research in terms of results and speed

**Comment by hackingguy** [comment]
I think mainly time is taken in shuffleDNS Sub Domains Brute Forcing and JS Files Extractions!
Both of them are very slow!

**Comment by six2dez** [comment]
Thanks for the feedback @hackingguy can you tell us what is exactly a very small scope? How many subdomains resolved? I have been testing for a "small scope" <30 subs alive and it takes 25 min. It's right JS subs scraping takes too much and that's why we set a max time of 10m for this step.

**Comment by bileltechno** [comment]
## Target z***.com: 23 probed links
### [santaHog](https://github.com/dxa4481/santaHog)
```.js

```
output:
-
-
-
 
### [truffleHogRegexes](https://github.com/dxa4481/truffleHogRegexes)
```.js

```
output:
-
- 

### [webscreenshot](https://github.com/maaaaz/webscreenshot)
``` .js 
webscreenshot.py -o webscreenshotScrenns -w 8  -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" -i xxxx.com_probed.txt
```
- Supports HTTP parameter (Cokkies, Headers) ..
- CAN'T RUN IT, buggy, Kopfschmerzen 

### [EyeWitness](https://github.com/FortyNorthSecurity/EyeWitness)
```.js

```
output:
A lot of dependecies need to be installeed. They have a setup.sh script which shall be executed and install selenium ....

**Comment by six2dez** [comment]
- GitGot could be an option.
- GitGraber could be an option.
- Gitleaks requires target repository.
- Gitminer requires setting GitHub cookie manually.
- Trufflehog requires target repository.
- Gitrob, web interface, requires git user/organization as target.
- Git-hound requires 2FA input.

**Comment by six2dez** [comment]
Done dfbdee3bb8193f6e7d4da1d3f0f65ec33979cf56
