### ISSUE TITLE
Notify config file not working properly

### ISSUE THREAD

**Issue by v1c70r-m** [six2dez/reconftw#392]
**Describe the bug**
I'm trying to use notify to provide notification on slack or discord and it keeps throwing an error when you change line 5 to true in the yaml file.

**To Reproduce**
1. Go to .config - notify - provider-config.yaml
2. Change discord: false or slack: false in the config file to true or True and it throws an error.
3. Doesn't matter if you use lower case, uppercase, or add single or double quotes to the true option.
4. Still get the following error: 

[FTL] Could not create runner: could not parse provider config file: yaml: unmarshal errors:
  line 5: cannot unmarshal !!bool `True` into []*slack.Options

**Expected behavior**
ReconFTW usually works without errors and I'll get notifications on the app I configure.

**Comment by six2dez** [comment]
Notify has changed recently the way it handles the providers. Please, take a look [here](https://github.com/projectdiscovery/notify#provider-config) to configure it properly

**Comment by v1c70r-m** [comment]
Understood. Thank you for your help.
