### ISSUE TITLE
how much is maximun time it take to scan largest target

### ISSUE THREAD

**Issue by KAKU1234567** [six2dez/reconftw#396]
how much is maximun time it take to scan largest target

_Originally posted by @KAKU1234567 in https://github.com/six2dez/reconftw/issues/395#issuecomment-935548935_

**Comment by six2dez** [comment]
It has no "maximum" time, as I said to you in your previous issue #395 , it depends on the target, your bandwith, connection and a few more things. Even less if you are running with -a flag.
