### ISSUE TITLE
-o not working on docker scan

### ISSUE THREAD

**Issue by blackcodersec** [six2dez/reconftw#397]
![Screenshot_19](https://user-images.githubusercontent.com/72689232/136181594-b547ce6a-0702-4912-a105-01a9bbd2d212.png)
![Screenshot_20](https://user-images.githubusercontent.com/72689232/136181605-97aefc3f-a2e0-4da0-af05-340cf6aafd45.png)
![Screenshot_21](https://user-images.githubusercontent.com/72689232/136181607-90e68d01-855d-43a4-b855-82b9792dbe05.png)

the file did not save to hackbox folder. now how to find that?

**Comment by six2dez** [comment]
Ok, here there are a few things:

1. You have to run this command ```docker run -v $PWD/reconftw.cfg:/root/Tools/reconftw/reconftw.cfg -v $PWD/Recon/:/root/Tools/reconftw/Recon/ --name reconftwSCAN --rm reconftw -d hackerone.com -s``` in your reconftw directory, not inside Docker folder or any other directory.
2. You have to understand what are you running always before just execute any line, and this is well explained [here](https://github.com/six2dez/reconftw#b-docker-container--2-options).
3. When you understand every command and flag with Docker, you will realize that you have to specify your local machine output folder in the second -v flag.

I hope this image showing how it runs perfectly serves as explanation::

![image](https://user-images.githubusercontent.com/24670991/136192405-731b2d93-7899-4c89-949f-267b47a73a2d.png)
