### ISSUE TITLE
Metadata Checks

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#40]
Metadata Checks implementation with pymeta

**Comment by detonxx** [comment]
1. '**metadata**' collection is important, but in the current script its placed at a higher priority. I think the functions below metadata() yield more higher severity bugs and are more important & needed for the person doing recon in his initial stages.
2. Also metadata checks may not yield any high severity bugs and so should be placed at the end of the script.
3. Also the time for execution highly depends on the "target" specified by the user. Suppose a target contains a lot of high quality pdf and images. So **pymeta** would be doing all those images from various search engines and then checking the exif for potential information disclosures.
4. At the end I think metadata is not that useful to be included in this script. Some things that are highly scalable shouldn't be included in this script and the user should carry out on his/her own

**Comment by six2dez** [comment]
Closed for the moment, could be reopened

**Comment by bileltechno** [comment]
What about cheking metadata of files in domain_uekchechecks.txt?

**Comment by six2dez** [comment]
I think there is a typo in this file, but must measure the time it takes, with this data we can discuss it
