### ISSUE TITLE
I am unable to install reconftw

### ISSUE THREAD

**Issue by cyberasset** [six2dez/reconftw#412]
**Describe the bug**
I am unable to install reconftw

when i am try to install reconftw first i clone this repo after that i enter ./install.sh It stays like this, no process goes ahead. please help me ASAP

![Screenshot_2021-10-31_08_53_28](https://user-images.githubusercontent.com/91467979/139565926-6c1ada5f-d844-4da2-8410-c194bbd4da3a.png)

**Comment by six2dez** [comment]
This is not a bug, reconftw installer is asking for you sudo password in order to install and perform actions that needs higher privileges. If you don't know what I am talking about, please take a look to the wiki

**Comment by cyberasset** [comment]
I enter my password but after that they not working

**Comment by six2dez** [comment]
Can you provide any evidence that is not working? After entering the password, the script starts installing the tools in background, you will receive some msgs about its progress from time to time.
