### ISSUE TITLE
unable to run the script ./reconftw.sh

### ISSUE THREAD

**Issue by raghuisin** [six2dez/reconftw#413]
**Describe the bug**![image](https://user-images.githubusercontent.com/32757324/140574284-b88dc105-8287-461a-8448-54a0fa4b6312.png)A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):
- Architecture: x86[e.g. x86, x64, ARM ...] 
 - OS: MacOS 11.6[e.g. Ubuntu, Kali, Arch ...]
 - Version 11.6[e.g. 20.04, Rolling, 8 ...]

**Additional context**

**Comment by six2dez** [comment]
This software is not supported on MacOS yet
