### ISSUE TITLE
Question : is there a way to run nuclei just on a few subdomains instead of the whole list gathered through the different techniques

### ISSUE THREAD

**Issue by Bawer-Agirman** [six2dez/reconftw#415]

**Comment by six2dez** [comment]
If you want to run nuclei on a few subdomains instead using the reconftw features, why you didn't just run nuclei against them? Anyway, you could put the subdomains file under Recon/target/subdomains/ with the name "subdomains.txt" and set to false every function except nuclei on reconftw.cfg
