### ISSUE TITLE
JavaScript Scan execution step inconsistencies

### ISSUE THREAD

**Issue by Hax0rG1rl** [six2dez/reconftw#420]
Hi, 

When running the tool against a decently large domain scope, the JavaScript scan module output this: 

Note: The behavior is similar, either using a standalone VPS or axiom-ing the flow. 

![image](https://user-images.githubusercontent.com/3704868/144333276-7389d949-12d2-4af2-a5c6-ecd57cf6ec7a.png)

**Environment:** Ubuntu 20.04.3

Still not sure if, under this circumstance, the current execution step is getting finalized successfully or a time up is triggered, and the execution flow is moving further. 

Thanks!

**Comment by six2dez** [comment]
Fixed on dev
