### ISSUE TITLE
CORS Scanning doesn't works

### ISSUE THREAD

**Issue by ritik-gg** [six2dez/reconftw#433]
**Bug**
CORS Scan Output is empty even on a vulnerable subdomain.

**To Reproduce**
Run reconftw on a CORS vulnerable subdomain but the output would be empty.

**Expected behavior**
This can be because in on line 1460 in reconftw.sh (https://github.com/six2dez/reconftw/blob/main/reconftw.sh#L1460), the output is redirecred to /dev/null.
`python3 $tools/Corsy/corsy.py -i webs/webs.txt > webs/cors.txt 2>>"$LOGFILE" &>/dev/null`

**Fix**
Output flag (-o) can be appended  or output can be redirected to the cors result file.

**Desktop (please complete the following information):**
 - OS: [Kali]

**Comment by six2dez** [comment]
Try to run the command standalone in your side, maybe you have anything wrong. I have been testing, and it should work without any problem.
![image](https://user-images.githubusercontent.com/24670991/147348131-52df15d2-c866-4f99-a330-713edde9d8a2.png)

**Comment by ritik-gg** [comment]
Hello, thanks for replying. Hope you are fine.

Just wanted to let you know that this issue is caused because of the way (different) shells are interpreting the statement.
This same command works on zsh but not on bash.
I confirmed by running this on
1) zsh: Kali machine, It worked.
![zsh](https://user-images.githubusercontent.com/81664591/147356017-39b6f2d8-cf3a-4ad7-b485-b1720160a5eb.png)
2) bash: ubuntu and arch, it didn't work.
![bash](https://user-images.githubusercontent.com/81664591/147356047-adadb20f-405f-4f1b-aec6-1583a8c3a411.png)
