### ISSUE TITLE
How to use single module mode?

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#444]
Hello Devs,
I am not sure how to use the single modules, let's suppose  I am hunting on example.com and I ran a subdomain mode via ./reconftw.sh -s example.com and it gave me output now how do i run the vuln/attack mode with these outputs?
And if I am not wrong there as an option to use any custome module as well such as nuclei or port scan by using -c flag but how to use this in a flow? Like if I ran subdomain enumeration using -c flag and now I need to run port scan on these file how do I do that?
Also share some Readme for all custom functions available.

**Comment by six2dez** [comment]
The single module mode (aka -c) works by running a specific function against and already scanned target, i.e. `./recoftw.sh -d target.com -c nuclei_checks` will re-run again nuclei against your target no matter if you already scanned it or no
