### ISSUE TITLE
theHarvester config file in Docker?

### ISSUE THREAD

**Issue by cosmin91ro** [six2dez/reconftw#447]
theHarvester config file is not copied to docker image, it would be nice to add it as you do with amass config file otherwise one must manually bash into the running container and add the necessary keys in api-keys.yaml

**Comment by frost19k** [comment]
> one must manually bash into the running container and add the necessary keys

Not necessarily. You can save the `api-keys.yaml` file on your host & mount it at runtime like so:
```bash
❯ docker -it --rm \
  -v "${PWD}/api-keys.yaml":"/root/Tools/theHarvester/api-keys.yml" \
  seix2dez/reconftw -d example.com -r
```
Note:
1. The command above assumes that `api-keys.yaml` is in your working directory.
2. You can mount any config file described in the wiki in this way. Your mounted file will overwrite the existing file for that run.

**Comment by cosmin91ro** [comment]
Yep, totally makes sense. Maybe this could be added in the docs as well.
