### ISSUE TITLE
Subdommain Recursive Search - How-To Examples

### ISSUE THREAD

**Issue by Hax0rG1rl** [six2dez/reconftw#451]
Hi, 

Thanks for putting this together. Since your aim here is to make this package one shop for ppl wanting to automate stuff when assessing a domain or alike, here's what I would say can bring some more paid supporters to your side: 

- When running the tool on a large scope, often get this, which is understandable, potentially generating huge tmp files, API requests, and all sorts of other things. 

```
 Running : Subdomains recursive search

 skipped in this mode or defined in reconftw.cfg in 0 seconds.
```

However, it would be beneficial if you could add some "best practices" / examples and quickly explain them for someone who wants to play here and start exploring more this advanced alternative, like if you are going down this path, then expect those: 

1. using [one_quick_example_of_an_advenced_config], I, as a user, should have a machine with 2Tb of HDD, 8 GB RAM, wait one week, and burn 10k API requests because it is going deep to level 3 of subdomain guessing. 

2. using [second_quick_example_of_an_advenced_config], I, as a user, should have a machine with 4Tb of HDD, 32 GB RAM, wait three weeks, and burn 80k API requests because it is going deep to level 6 of subdomain guessing. 

If you feel this is a stupid idea, adding such potential scenarios, is fine, I don't take things personally :) 

Thanks!

**Comment by 0-0eth0** [comment]
Hi,
I guess in Wiki section of this tool, most of the things are explained you could check.

Hope its useful!
Link:https://github.com/six2dez/reconftw/wiki


Regards.

**Comment by six2dez** [comment]
@Hax0rG1rl anyway I've added an issue to improve the wiki with new scenarios and other things here https://github.com/six2dez/reconftw/issues/456 feel free to comment there any other ideas/needs you want

**Comment by Hax0rG1rl** [comment]
@six2dez, 

1. Your reply says somethign about your character. And this will bring you more paid supporters in the long run. 
2. Thank you for taking a second look and trying to understand if the current wiki does have any gaps. 
3. Sorry not being sorry to say this, @0-0eth0 your comment provided zero value in the context, proving the wiki section is still something that you might worth reading it once in a while. 

Thanks!

**Comment by sidxparab** [comment]
Hey, @Hax0rG1rl you can get a detailed info about what exactly is `Recursive Enumeration` at 
https://sidxparab.gitbook.io/subdomain-enumeration-guide/passive-enumeration/recursive-enumeration
