### ISSUE TITLE
Output directory can be unexpectedly deleted

### ISSUE THREAD

**Issue by nicoandmee** [six2dez/reconftw#452]
**Describe the bug**

In `reconftw.cfg`, if `dir_output` is set to the same directory as where the script is running, the output directory will be deleted as a consequence of https://github.com/six2dez/reconftw/blob/main/reconftw.sh#L1741. 

**Expected behavior**
Since output directory and working directory are the same, do nothing.

**Additional context**
I believe it could be fixed by adding a simple check like:
```shell
[[ "$dir" != "$dir_output" ]] && rm -rf "$dir"
```

**Comment by six2dez** [comment]
Fixed on dev https://github.com/six2dez/reconftw/commit/315bde87eceacafeedbf3c6cc621995d7cc8a3eb
