### ISSUE TITLE
help

### ISSUE THREAD

**Issue by vansh1** [six2dez/reconftw#453]
**Describe the bug**
WARN[0000] error instantiating commoncrawl: API responded with non-200 status code  this is error

**To Reproduce**
i just ran ./reconftw.sh -d site.com -r -s -o outputdir

**Expected behavior**
it shouldn;t give any error and go smoothly

**Desktop (please complete the following information):**
 - ubuntu 20.04.1

**Comment by six2dez** [comment]
This is an issue with gau tool reported here https://github.com/lc/gau/issues/53 please, try to reinstall the tool and check again, it should be fixed based on the comments

**Comment by vansh1** [comment]
i did, isn't it by s3scanner?

**Comment by six2dez** [comment]
I don't think so, S3scanner doesn't use commoncrawl, but gau does.
