### ISSUE TITLE
Error in Passive domain

### ISSUE THREAD

**Issue by zufan-yp** [six2dez/reconftw#455]
**Describe the bug**
Error in Passive domain

**Screenshots**
![image](https://user-images.githubusercontent.com/78656480/149908008-f02cc3f5-4fee-4758-9e0b-8231d29b71ab.png)

**Desktop (please complete the following information):**
- Architecture: [e.g. x86, x64,]
 - OS: [e.g. Kali]
 - Version [e.g. 21.04, Rolling, 8 ...]

**Comment by 0-0eth0** [comment]
Hi Seems,
Issue from Golang, can you confirm me your go version? by typing `go version` in terminal?

**Comment by zufan-yp** [comment]
i using golang, go1.17.5 linux/amd64

**Comment by zufan-yp** [comment]
seems to have been fixed, now I use the error no longer appears
