### ISSUE TITLE
Understanding Slack Notification Setup

### ISSUE THREAD

**Issue by etaylor77** [six2dez/reconftw#459]
I have tried a couple of different inputs for variable slack-auth and enabled the Notification in the configurations but unable to get any notifications sent over. 

![image](https://user-images.githubusercontent.com/12686164/151006249-7b4fa666-ee51-45d8-9a5f-10d746f4289e.png)

![image](https://user-images.githubusercontent.com/12686164/151006119-20fab8f1-e23a-41e3-b455-e367b15491c0.png)

**Comment by six2dez** [comment]
Take a look [here](https://github.com/projectdiscovery/notify#provider-config) and [here](https://slack.com/intl/es-es/help/articles/115005265063-Webhooks-entrantes-para-Slack)
