### ISSUE TITLE
Unable to install script

### ISSUE THREAD

**Issue by hhls** [six2dez/reconftw#467]
Execute the script（./install.sh）, appear
" Unable to install crlfuzz, try manually (1/31)
 Unable to install gf, try manually (2/31)
 Unable to install dalfox, try manually (3/31)
 Unable to install github-endpoints, try manually (4/31)
....
"
Too much manual installation to make it work, what should I do

**Comment by six2dez** [comment]
Seems Golang was not properly installed, try to install manually Golang and rerun again. Thanks!

**Comment by hhls** [comment]
> Seems Golang was not properly installed, try to install manually Golang and rerun again. Thanks!

wow, it's right, thank you very much for your prompt answer

**Comment by njmulsqb** [comment]
I am facing same issue on Kali Linux,
I have removed golang using `sudo apt remove golang` and then `sudo apt autoremove` and reinstalled it but still facing the same issue. Any idea how to get away with it?
