### ISSUE TITLE
Need axiom delay on axiom-ls causing 429

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#473]
Need axiom delay on axiom-ls
causing 429 ratel imiting on 25 droplets.

**Comment by gprime31** [comment]
![2022-02-23_08-57](https://user-images.githubusercontent.com/44535257/155333864-be9884cf-ae02-4435-ae43-4181e2546877.png)

**Comment by 0xtavian** [comment]
hey @gprime31 ,

how repeatable is this? Meaning after the rate limit cool down, does it happen constantly? And at what point?

Running `doctl account ratelimit` will show the current limit ( default is 5,000 an hour ) and how many you have left.

**Comment by gprime31** [comment]
Ah... that cound be it, spun up 50 back-to-back-to-back and 20 small targets. Because i didn't see it at first, then it started happening. However it does not effect the run, the droplets still spin up and shut down like they should.
Thanks, i'll close.

**Comment by 0xtavian** [comment]
Yep that sounds like it could do it. Glad we got it sorted. let us know if u run into any more issues. :)

**Comment by six2dez** [comment]
Thanks for the support @0xtavian !!!
