### ISSUE TITLE
dns zone transfers will always fail

### ISSUE THREAD

**Issue by geeknik** [six2dez/reconftw#480]
**Describe the bug**
Currently to test for zone transfers, the script is performing the following check:
`dig axfr $domain @8.8.8.8 > subdomains/zonetransfer.txt`

You can't transfer zones from resolvers. You have to query nameservers, for example, we lookup the nameservers for example.com:
```
$ dig +short ns example.com
a.iana-servers.net.
b.iana-servers.net.
```

We can then test the zone transfer against those name servers:
```
dig axfr example.com @a.iana-servers.net.

; <<>> DiG 9.16.24-RH <<>> axfr example.com @a.iana-servers.net.
;; global options: +cmd
; Transfer failed.
```

To remediate this issue, I would rework the zone transfer routine to check the name servers of $domain instead of testing against a Google resolver. 👍🏻  Something like this could work: `for ns in $(dig +short ns "$domain"); do dig axfr "$domain" @"$ns" >> subdomains/zonetransfer.txt; done`

**Comment by six2dez** [comment]
Omg, you're right! What a dumb error, fixed on dev branch https://github.com/six2dez/reconftw/commit/4dbc56a7adf8c95b31ec24b68d2cf28b8528ddde
