### ISSUE TITLE
use gitdorks_go instead of GitDorker

### ISSUE THREAD

**Issue by 1979139113** [six2dez/reconftw#481]
**Is your feature request related to a problem? Please describe.**

cause of the [github secondary rate limits](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits), the Gitdorker performance is not particularly good, and it has many errors...

![GitDorker](https://github.com/damit5/gitdorks_go/raw/d4m1ts/README.assets/image-20220316151327854.png)

**Describe the solution you'd like**

use [gitdorks_go](https://github.com/damit5/gitdorks_go/) will be better.

![gitdorks_go](https://github.com/damit5/gitdorks_go/raw/d4m1ts/README.assets/image-20220316155344201.png)

**Describe alternatives you've considered**

use gitdorks_go instead of GitDorker

**Additional context**

nil

**Comment by six2dez** [comment]
I tested and works good, I will implement it in the next release. Thanks!

**Comment by six2dez** [comment]
Done https://github.com/six2dez/reconftw/commit/efec600b9d392522b27b53424e4baf1db3c1d021
