### ISSUE TITLE
Why shoan is removed?

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#482]
Hey @six2dez ,
Why shodan is removed from, does nrich gives exact same results as compared to shodan premium key holder?

**Comment by six2dez** [comment]
Yeah, I think the relevant info is the same, and nrich works faster:

- scanme.nmap.org:

![image](https://user-images.githubusercontent.com/24670991/160214941-0fea2c10-2db8-4132-a2dd-0135a4bd742f.png)


- Google:

![image](https://user-images.githubusercontent.com/24670991/160214871-8a4e9b7b-6fe1-4235-8668-f2e498f7824b.png)
