### ISSUE TITLE
Getting 30 GB gotator1.txt file inside .tmp folder is there any workaround?

### ISSUE THREAD

**Issue by dnmrbughunter** [six2dez/reconftw#483]
**Describe the bug**
Getting 30 GB gotator1.txt file inside .tmp folder is there any workaround?

**To Reproduce**
This is the command I use:
reconftw.sh -d $TARGET -a --deep -o 

**Expected behavior**
A log not soooooooo big.

**Screenshots**
None.

**Desktop (please complete the following information):**
- Architecture: x64
 - OS: Ubuntu
 - Version 20.04

**Additional context**
Please let me know if I could collaborate

**Comment by dnmrbughunter** [comment]
Ok, thanks!

**Comment by six2dez** [comment]
Thanks @jakre1234 also skipping permutations on cfg file @dnmrbughunter
