### ISSUE TITLE
What is DIFF flag?

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#484]
What is DIFF flag and when it is to be used? On first run? Is it for difference on second run?

**Comment by six2dez** [comment]
It's explained [here](https://github.com/six2dez/reconftw/wiki/3.-Configuration-file#12-extra-option)

> Enable support to run over same targets again and again and it only advice for new findings (for cron mode and monitoring)

Basically it's useful when you want to run a previous scanned target, it will not skip the functions but runs again and notifies for new findings.

**Comment by jakre1234** [comment]
Thanks for clarifying in simple language. Much appreciated.
