### ISSUE TITLE
USe tok and ettu from TomNomNom

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#489]
Hey the other day, while watching tomnomnom's stream with nahmsec. Tom introduced to a cool tool tok which can be used to create custom wordlists from the enumerated subdomains and use it for subdomain permutation using something like ettu.
Super awesome tools, I leave a link to both of them can be really handy for subdomain permutaions.
https://github.com/tomnomnom/hacks/tree/master/tok
https://github.com/tomnomnom/hacks/tree/master/ettu

**Comment by six2dez** [comment]
Imho [gotator](https://github.com/Josue87/gotator) for permutations and [puredns](https://github.com/d3mondev/puredns) for DNS resolving/bruteforcing are much better tools with a lot of useful features
