### ISSUE TITLE
Nuclei rate-limit features

### ISSUE THREAD

**Issue by FalcoXYZ** [six2dez/reconftw#498]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
An option to add a rate-limit (and other rate-limit options) to Nuclei by adding/changing the config file. Example: NUCLEI_RATELIMIT=10 (it's the -rate-limit flag in Nuclei) 

**Describe alternatives you've considered**
NA

**Additional context**

RATE-LIMIT:
   -rl, -rate-limit int          maximum number of requests to send per second (default 150)
   -rlm, -rate-limit-minute int  maximum number of requests to send per minute
   -bs, -bulk-size int           maximum number of hosts to be analyzed in parallel per template (default 25)
   -c, -concurrency int          maximum number of templates to be executed in parallel (default 25)

**Comment by Job-de-Bruijn** [comment]
I have added the option to set it it the config file 487e81429db28fe44455f48b3cac366deee0a4af
Also for ffuf 2332b428cc53a28070938e68bf6b7ccbe7d46b3a and httpx 16810c93fcda355425a83a9c8a4bd6436ab4dffb
You will also be able to set it with an argument 30543807b49a40e9f55c2da4957a5622e9ae970e
Wich will set nuclei, ffuf and httpx rate limit to the value that u passed with the argument -q.

**Comment by six2dez** [comment]
Great job @Job-de-Bruijn I will close this issue as it's already on dev branch, during the week will be pushed to main with a  new release :)
