### ISSUE TITLE
Auto Export $HOME/go/bin to $PATH

### ISSUE THREAD

**Issue by bileltechno** [six2dez/reconftw#5]
The function  will show that all go tools are not installed if the **$HOME/go/bin** is not exported  in **$PATH**. Which will be confusing for users and this will make a doubt in the install.sh script.

I suggest to export the go/bin to $path automatically in the reconftw.sh or adding it permanently in the system via install.sh

**Comment by six2dez** [comment]
It's a tool requirement as said in Requirements section "**Golang > 1.14 installed and env vars correctly set ($GOPATH,$GOROOT)**", so I leave it to the user who I trust will be able to install and configure Golang to their liking. Anyway more error check will be added in next release :)
