### ISSUE TITLE
./reconftw.sh: line 1775: ${LOGFILE}: ambiguous redirect

### ISSUE THREAD

**Issue by ashhadali10** [six2dez/reconftw#500]
**Describe the bug**
when i run it show me this in some lines  i dont know how to solve this 

**To Reproduce**
just run tool with single domain scan  -r

**Desktop (please complete the following information):**
- Architecture: [e.g. x86, x64, ARM ...]
 - OS: [e.g. parrot]

**Comment by zwatkins15** [comment]
As best as I can tell it's an issue with handling spaces in the current path, or log patch specifically. Not sure if that's helpful, but running the script from a location without spaces in the path fixed it for me.

**Comment by six2dez** [comment]
I will test it, enclosing LOGFILE var into double quotes should do the job, I will check asap

**Comment by six2dez** [comment]
Fixed on dev https://github.com/six2dez/reconftw/commit/67c70bae05c0a34734cf255153b8e7923ff5bcd2 sorry for the delay
