### ISSUE TITLE
Subfinder Config file?

### ISSUE THREAD

**Issue by abdilahrf** [six2dez/reconftw#503]
Is the Subfinder config file really used anywhere, I can't found any reference when the file is used.
also the install scripts not even install subfinder, any thoughts?

**Comment by six2dez** [comment]
Subfinder was removed a few weeks ago from this framework, where do you find a mention to it? Just curious to completely remove everything related to it.

Thanks!

**Comment by abdilahrf** [comment]
i see, i found it here : 

Wiki post installation point 2 https://github.com/six2dez/reconftw/wiki/1.-Post-Installation-Guide 
And axiom scripts

**Comment by six2dez** [comment]
Fixed
