### ISSUE TITLE
Warning: error instantiating commoncrawl

### ISSUE THREAD

**Issue by Hax0rG1rl** [six2dez/reconftw#513]
Hi, 

Running the latest version against a target, I noticed starting getting this warning: 

```
URL Extraction
WARN[0000] error instantiating commoncrawl: commoncrawl.apiResult: decode slice: expect [ or n, but found , error found in #0 byte of ...||..., bigger context ...||...
```

While is not quite a big deal, do you have any ideas about I can debug this? :) 

Thanks!

**Comment by six2dez** [comment]
It's a msg from amass output, I will take care of it in the next version avoiding to print this kind of messages :)
