### ISSUE TITLE
Docker Image: uro, bbrf, & emailfinder not installed.

### ISSUE THREAD

**Issue by frost19k** [six2dez/reconftw#522]
**Describe the bug**
```Bash
❯ docker run -it --rm six2dez/reconftw:main

  ██▀███  ▓█████  ▄████▄   ▒█████   ███▄    █   █████▒▄▄▄█████▓ █     █░
 ▓██ ▒ ██▒▓█   ▀ ▒██▀ ▀█  ▒██▒  ██▒ ██ ▀█   █ ▓██   ▒ ▓  ██▒ ▓▒▓█░ █ ░█░
 ▓██ ░▄█ ▒▒███   ▒▓█    ▄ ▒██░  ██▒▓██  ▀█ ██▒▒████ ░ ▒ ▓██░ ▒░▒█░ █ ░█ 
 ▒██▀▀█▄  ▒▓█  ▄ ▒▓▓▄ ▄██▒▒██   ██░▓██▒  ▐▌██▒░▓█▒  ░ ░ ▓██▓ ░ ░█░ █ ░█ 
 ░██▓ ▒██▒░▒████▒▒ ▓███▀ ░░ ████▓▒░▒██░   ▓██░░▒█░      ▒██▒ ░ ░░██▒██▓ 
 ░ ▒▓ ░▒▓░░░ ▒░ ░░ ░▒ ▒  ░░ ▒░▒░▒░ ░ ▒░   ▒ ▒  ▒ ░      ▒ ░░   ░ ▓░▒ ▒  
   ░▒ ░ ▒░ ░ ░  ░  ░  ▒     ░ ▒ ▒░ ░ ░░   ░ ▒░ ░          ░      ▒ ░ ░  
   ░░   ░    ░   ░        ░ ░ ░ ▒     ░   ░ ░  ░ ░      ░        ░   ░  
    ░        ░  ░░ ░          ░ ░           ░                      ░    
                 ░                                                      
 main-v2.2.2-10-g8f30604                                 by @six2dez

 Usage: ./reconftw.sh [-d domain.tld] [-m name] [-l list.txt] [-x oos.txt] [-i in.txt] 
           	      [-r] [-s] [-p] [-a] [-w] [-n] [-i] [-h] [-f] [--deep] [-o OUTPUT]
[...]
#######################################################################
 Checking installed tools 

 [*] emailfinder	[NO]
 [*] uro		[NO]
 [*] bbrf		[NO]

 Try running the installer script again ./install.sh
 If it fails for any reason try to install manually the tools missed
 Finally remember to set the $tools variable at the start of this script
 If nothing works and the world is gonna end you can always ping me :D 

 Tools check finished
#######################################################################

```

**To Reproduce**
```Bash
docker run -it --rm six2dez/reconftw:main
```

**Expected behavior**
All tools should be installed.

**Screenshots**

**Desktop (please complete the following information):**
- Architecture: x86_64
 - OS: Manjaro
 - Version Rolling (21.2.6)

**Additional context**
Line 245 in `install.sh` which installs the Python Deps. from `requirements.txt` is failing because of `jsbeautifier`.
I suspect there is an issue with the version of Python being shipped in Kali repos.
I have opened an issue with [js-beautify](https://github.com/beautify-web/js-beautify/issues/2053) that has more context.

Until the cause is found & the issue resolved, we can implement a stop-gap solution by using multi-stage builds, installing the deps. in `python:3.10-slim` & copying the `/usr/local/lib/python3.10/dist-packages` directory or by switching to [jsbeautifier-go](https://github.com/ditashi/jsbeautifier-go) in `install.sh`.

**Comment by six2dez** [comment]
Thanks for the issue and for all the info, will work on this as soon as I can :)

**Comment by MoXiaoJian** [comment]
This is also my problem. My network is in China

**Comment by lukewegryn** [comment]
I'm also having this same issue!

**Comment by six2dez** [comment]
> This problem also occurs in local installations

I don't think, so this happens in local installations, can you provide any evidence? I'm installing reconftw almost daily on different machines and never happens this to me on local installations

**Comment by sisco0** [comment]
https://github.com/six2dez/reconftw/issues/522#issue-1235928091 Considering that `jsbeautifier` is not part of the `requirements.txt` file anymore as commit 5a2f34517370a5a2d59f8367890f76953e549ae2 from Jun 28 shows, is the issue still happening in the same line?

**Comment by frost19k** [comment]
@sisco0 
> Considering that jsbeautifier is not part of the requirements.txt file anymore...

Didn't notice that. I'll close this issue as it's no longer relevant. 

> Considering that ripgen is part of Rust environment, we should study if the cargo environment is set correctly when the application executes.

`ripgen` is properly installed & you're right in your assumption that the env is not properly set. 

In the Dockerfile the default `.bashrc` is backed up at line `56` & restored at line `97-98`. I did this in an attempt to have a cleaner `$PATH`. 
@six2dez could either remove those lines or symlink `/root/.cargo/bin/ripgen` to `/usr/local/bin`. Personally I would go with the latter, but either will fix it.
