### ISSUE TITLE
Ripgen in the flow?

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#527]
Hey devs,
Any plan of including ripgen in the recon workflow? It's awesome tool for subdomain permutation and enumeration writtern in rust. Way too fast.
https://github.com/resyncgg/ripgen

**Comment by six2dez** [comment]
Hi @jakre1234 check the latest dev branch version, it contains ripgen as a gotator alternative(not deeper as it but faster) and you can configure it on reconftw.cfg :)

**Comment by jakre1234** [comment]
Thanks man, also can you do a a blog post on these covering subdomain enumeration and permutation techniques, how they work and what are the limits of different tools out there just like you did for recon automation tools.

Thanks and Regards,

**Comment by six2dez** [comment]
Check [this](https://blog.yeswehack.com/yeswerhackers/subdomains-tools-review-full-detailed-comparison/) and also [this](https://sidxparab.gitbook.io/subdomain-enumeration-guide/)
