### ISSUE TITLE
make spent time more human readable 

### ISSUE THREAD

**Issue by bileltechno** [six2dez/reconftw#53]
After any task spent time is printed out.
This time in seconds.
This is not so readable.
Lets print it in other format: HH:MM:SS
And hoping HH is always = 00 :)

**Comment by hackingguy** [comment]
If you guys want! I can collaborate to make a front end and backend server for this whole project!

**Comment by bileltechno** [comment]
@hackingguy : What do you means by  backend server?

**Comment by hackingguy** [comment]
I meant 3 docker containers 
1. Reverse Proxy Server (NGINX)
2. Backend to manage users request
3. Execute Commands Sent By Back End And Execute Them And Share Progress!

**Comment by bileltechno** [comment]
@hackingguy   :+1:   seems wonderful.
I am not the web guy to understand perfectly those features. Waiting for @six2dez  feedback. 
Anyways you can start open feature issues. And they will be farther discussed.
Any serious collaboration is welcomed .

**Comment by hackingguy** [comment]
ohk sir! can we get it to some good platform for ex. twitter or telegram group?

**Comment by six2dez** [comment]
@hackingguy create issue [here](https://github.com/six2dez/reconftw/issues/new/choose) explain as much as you can and we think about how well it fits with the needs of the tool
