### ISSUE TITLE
Not Running Properly

### ISSUE THREAD

**Issue by d1pakda5** [six2dez/reconftw#533]
**Describe the bug**
during installation i got below error

info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

Then after running one scan i dont see any result within 1 min scan getting completed

**Expected behavior**
Should work properly 

**Desktop (please complete the following information):**
- Architecture: x64
 - OS: ubunto 20.04 LTS

**Additional context**

**Comment by six2dez** [comment]
The message you're seeing during installation is not an error, it's just information from rust installer. Can you provide any additional details, like the .log for a scan or screenshots?

**Comment by d1pakda5** [comment]
where the .log file getting stored ?

**Comment by d1pakda5** [comment]
Here is the log
command .reconftw.sh -d domain.com -a

log/2022-06-16_17\:11\:11.txt 
Start 2022-06-16 17:11:11
[ 2022-06-16 17:11:11 ] Start function : domain_info 
[ 2022-06-16 17:14:55 ] End function : domain_info 
[ 2022-06-16 17:14:55 ] Start function : emails 
[ 2022-06-16 17:15:41 ] End function : emails 
[ 2022-06-16 17:16:17 ] End function : google_dorks 
[ 2022-06-16 17:16:17 ] Start function : github_dorks 
[ 2022-06-16 17:16:17 ] End function : github_dorks 
[ 2022-06-16 17:16:17 ] Start function : metadata 
mv: cannot stat 'osint/apple.com/*.txt': No such file or directory
[ 2022-06-16 17:16:29 ] End function : metadata 
[ 2022-06-16 17:16:29 ] Start function : zonetransfer 
[ 2022-06-16 17:16:31 ] End function : zonetransfer 
[ 2022-06-16 17:16:31 ] Start function : favicon 
[ 2022-06-16 17:16:32 ] End function : favicon 
[ 2022-06-16 17:16:33 ] Start subfunction : sub_passive 
[ 2022-06-16 17:23:40 ] End subfunction : 19178 new subs (passive) 
[ 2022-06-16 17:23:40 ] Start subfunction : sub_crt 
[ 2022-06-16 17:23:53 ] End subfunction : 2635 new subs (cert transparency) 
[ 2022-06-16 17:23:53 ] Start subfunction : sub_active 
panic: runtime error: integer divide by zero

goroutine 145 [running]:
github.com/projectdiscovery/retryabledns.(*Client).QueryMultiple(0xc000197b80, {0xc000342530, 0x9}, {0xc000342270, 0x1, 0x0?})
	/root/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.13/client.go:240 +0xa4a
github.com/projectdiscovery/dnsx/libs/dnsx.(*DNSX).QueryMultiple(...)
	/root/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.0/libs/dnsx/dnsx.go:84
github.com/projectdiscovery/dnsx/internal/runner.(*Runner).worker(0xc00039e0a0)
	/root/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.0/internal/runner/runner.go:555 +0x145
created by github.com/projectdiscovery/dnsx/internal/runner.(*Runner).startWorkers
	/root/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.0/internal/runner/runner.go:541 +0xbd
[ 2022-06-16 17:23:55 ] End subfunction : 0 new subs (active resolution) 
[ 2022-06-16 17:23:55 ] Start subfunction : sub_brute 
cat: .tmp/subs_brute_valid.txt: No such file or directory
[ 2022-06-16 17:23:55 ] End subfunction : 0 new subs (bruteforce) 
[ 2022-06-16 17:23:55 ] Start subfunction : sub_permut 
cat: .tmp/permute1.txt: No such file or directory
cat: .tmp/permute2.txt: No such file or directory
[ 2022-06-16 17:23:55 ] End subfunction : 0 new subs (permutations) 
[ 2022-06-16 17:23:55 ] Start subfunction : sub_dns 
cat: .tmp/subdomains_dns_resolved.txt: No such file or directory
[ 2022-06-16 17:23:56 ] End subfunction : 0 new subs (dns resolution) 
[ 2022-06-16 17:23:56 ] Start subfunction : sub_scraping 
[ 2022-06-16 17:23:56 ] End subfunction : No subdomains to search (code scraping) 
[ 2022-06-16 17:23:56 ] Start subfunction : sub_analytics 
cat: .tmp/analytics_subs_resolved.txt: No such file or directory
[ 2022-06-16 17:23:56 ] End subfunction : 0 new subs (analytics relationship) 
[ 2022-06-16 17:23:56 ] Start subfunction : webprobe_simple 
cat: .tmp/web_full_info.txt: No such file or directory
cat: webs/web_full_info.txt: No such file or directory
[ 2022-06-16 17:23:56 ] End subfunction : 0 new websites resolved 
[ 2022-06-16 17:23:56 ] Start function : webprobe_full 
cat: .tmp/probed_uncommon_ports_tmp.txt: No such file or directory
[ 2022-06-16 17:23:56 ] End function : webprobe_full 
[ 2022-06-16 17:23:56 ] Start function : subtakeover 
[ 2022-06-16 17:24:35 ] End function : subtakeover 
[ 2022-06-16 17:24:35 ] Start function : s3buckets 
cat: .tmp/s3buckets.txt: No such file or directory
[ 2022-06-16 17:24:39 ] End function : s3buckets 
[ 2022-06-16 17:24:39 ] Start function : screenshot 
[ 2022-06-16 17:24:39 ] End function : screenshot 
[ 2022-06-16 17:24:39 ] Start function : cdnprovider 
[ 2022-06-16 17:24:39 ] End function : cdnprovider 
[ 2022-06-16 17:24:39 ] Start function : portscan 
[ 2022-06-16 17:24:39 ] End function : portscan 
[ 2022-06-16 17:24:39 ] Start function : waf_checks 
[ 2022-06-16 17:24:39 ] End function : waf_checks 
[ 2022-06-16 17:24:39 ] Start function : nuclei_check 
[ 2022-06-16 17:24:56 ] End function : nuclei_check 
[ 2022-06-16 17:24:56 ] Start function : fuzz 
[ 2022-06-16 17:24:56 ] End function : fuzz 
[ 2022-06-16 17:24:56 ] Start function : urlchecks 
[ 2022-06-16 17:24:57 ] Start function : jschecks 
[ 2022-06-16 17:24:57 ] End function : jschecks 
[ 2022-06-16 17:24:57 ] Start function : cms_scanner 
[ 2022-06-16 17:24:57 ] End function : cms_scanner 
[ 2022-06-16 17:24:57 ] Start function : url_gf 
[ 2022-06-16 17:24:57 ] End function : url_gf 
[ 2022-06-16 17:24:57 ] Start function : wordlist_gen 
[ 2022-06-16 17:24:57 ] End function : wordlist_gen 
[ 2022-06-16 17:24:57 ] Start function : wordlist_gen_roboxtractor 
[ 2022-06-16 17:24:57 ] End function : wordlist_gen_roboxtractor 
[ 2022-06-16 17:24:57 ] Start function : password_dict 
[ 2022-06-16 17:24:57 ] End function : password_dict 
[ 2022-06-16 17:24:57 ] Start function : cors 
[ 2022-06-16 17:24:57 ] End function : cors 
[ 2022-06-16 17:24:57 ] Start function : crlf_checks 
[ 2022-06-16 17:24:57 ] End function : crlf_checks 
[ 2022-06-16 17:24:57 ] Start function : prototype_pollution 
[ 2022-06-16 17:24:57 ] End function : prototype_pollution 
[ 2022-06-16 17:24:57 ] Start function : spraying 
[ 2022-06-16 17:24:58 ] End function : spraying 
[ 2022-06-16 17:24:58 ] Start function : brokenLinks 
cat: .tmp/brokenLinks_total.txt: No such file or directory
[ 2022-06-16 17:24:58 ] End function : brokenLinks 
[ 2022-06-16 17:24:58 ] Start function : test_ssl 
Fatal error: Can't read file "hosts/ips.txt"
[ 2022-06-16 17:25:03 ] End function : test_ssl 
End 2022-06-16 17:25:03

**Comment by six2dez** [comment]
Hi @d1pakda5 as you can see your box returns an error when it runs dnsx, maybe is due to a memory problem (the lack of). Probably the best solution is to test dnsx alone with a list of subdomains and open a ticket to the dnsx repository.

**Comment by six2dez** [comment]
Hi, I detected the proble, was my fault, I just released a hotfix

**Comment by d1pakda5** [comment]
@six2dez updated and tested still same issue i am facing . is it working for you ?

**Comment by d1pakda5** [comment]
Log after update 

Start 2022-06-16 20:26:12
[ 2022-06-16 20:26:12 ] Start function : domain_info 
[ 2022-06-16 20:29:20 ] End function : domain_info 
[ 2022-06-16 20:29:20 ] Start function : emails 
[ 2022-06-16 20:30:15 ] End function : emails 
[ 2022-06-16 20:30:43 ] End function : google_dorks 
[ 2022-06-16 20:30:43 ] Start function : github_dorks 
[ 2022-06-16 20:30:43 ] End function : github_dorks 
[ 2022-06-16 20:30:43 ] Start function : metadata 
mv: cannot stat 'osint/instasafe.com/*.txt': No such file or directory
[ 2022-06-16 20:30:54 ] End function : metadata 
[ 2022-06-16 20:30:54 ] Start function : zonetransfer 
[ 2022-06-16 20:30:55 ] End function : zonetransfer 
[ 2022-06-16 20:30:55 ] Start function : favicon 
[ 2022-06-16 20:30:55 ] End function : favicon 
[ 2022-06-16 20:30:55 ] Start subfunction : sub_passive 
[ 2022-06-16 20:33:22 ] End subfunction : 49 new subs (passive) 
[ 2022-06-16 20:33:22 ] Start subfunction : sub_crt 
[ 2022-06-16 20:33:30 ] End subfunction : 23 new subs (cert transparency) 
[ 2022-06-16 20:33:30 ] Start subfunction : sub_active 
panic: runtime error: integer divide by zero

goroutine 43 [running]:
github.com/projectdiscovery/retryabledns.(*Client).QueryMultiple(0xc00020fb80, {0xc0001a0230, 0xd}, {0xc0003b8280, 0x1, 0x0?})
	/root/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.13/client.go:240 +0xa4a
github.com/projectdiscovery/dnsx/libs/dnsx.(*DNSX).QueryMultiple(...)
	/root/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.0/libs/dnsx/dnsx.go:84
github.com/projectdiscovery/dnsx/internal/runner.(*Runner).worker(0xc0003581e0)
	/root/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.0/internal/runner/runner.go:555 +0x145
created by github.com/projectdiscovery/dnsx/internal/runner.(*Runner).startWorkers
	/root/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.0/internal/runner/runner.go:541 +0xbd
[ 2022-06-16 20:33:31 ] End subfunction : 0 new subs (active resolution) 
[ 2022-06-16 20:33:31 ] Start subfunction : sub_brute 
cat: .tmp/subs_brute_valid.txt: No such file or directory
[ 2022-06-16 20:33:32 ] End subfunction : 0 new subs (bruteforce) 
[ 2022-06-16 20:33:32 ] Start subfunction : sub_permut 
cat: .tmp/permute1.txt: No such file or directory
cat: .tmp/permute2.txt: No such file or directory
[ 2022-06-16 20:33:32 ] End subfunction : 0 new subs (permutations) 
[ 2022-06-16 20:33:32 ] Start subfunction : sub_dns 
cat: .tmp/subdomains_dns_resolved.txt: No such file or directory
[ 2022-06-16 20:33:33 ] End subfunction : 0 new subs (dns resolution) 
[ 2022-06-16 20:33:33 ] Start subfunction : sub_scraping 
[ 2022-06-16 20:33:33 ] End subfunction : No subdomains to search (code scraping) 
[ 2022-06-16 20:33:33 ] Start subfunction : sub_analytics 
cat: .tmp/analytics_subs_resolved.txt: No such file or directory
[ 2022-06-16 20:33:33 ] End subfunction : 0 new subs (analytics relationship) 
[ 2022-06-16 20:33:33 ] Start subfunction : webprobe_simple 
cat: .tmp/web_full_info.txt: No such file or directory
[ 2022-06-16 20:33:33 ] End subfunction : 0 new websites resolved 
[ 2022-06-16 20:33:33 ] Start function : webprobe_full 
cat: .tmp/probed_uncommon_ports_tmp.txt: No such file or directory
[ 2022-06-16 20:33:33 ] End function : webprobe_full 
[ 2022-06-16 20:33:33 ] Start function : subtakeover 
[ 2022-06-16 20:33:37 ] End function : subtakeover 
[ 2022-06-16 20:33:37 ] Start function : s3buckets 
cat: .tmp/s3buckets.txt: No such file or directory
[ 2022-06-16 20:33:40 ] End function : s3buckets 
[ 2022-06-16 20:33:40 ] Start function : screenshot 
[ 2022-06-16 20:33:40 ] End function : screenshot 
[ 2022-06-16 20:33:40 ] Start function : cdnprovider 
[ 2022-06-16 20:33:40 ] End function : cdnprovider 
[ 2022-06-16 20:33:40 ] Start function : portscan 
[ 2022-06-16 20:33:40 ] End function : portscan 
[ 2022-06-16 20:33:40 ] Start function : waf_checks 
[ 2022-06-16 20:33:40 ] End function : waf_checks 
[ 2022-06-16 20:33:40 ] Start function : nuclei_check 
[ 2022-06-16 20:33:52 ] End function : nuclei_check 
[ 2022-06-16 20:33:52 ] Start function : fuzz 
[ 2022-06-16 20:33:52 ] End function : fuzz 
[ 2022-06-16 20:33:52 ] Start function : urlchecks 
[ 2022-06-16 20:33:52 ] Start function : jschecks 
[ 2022-06-16 20:33:52 ] End function : jschecks 
[ 2022-06-16 20:33:52 ] Start function : cms_scanner 
[ 2022-06-16 20:33:52 ] End function : cms_scanner 
[ 2022-06-16 20:33:52 ] Start function : url_gf 
[ 2022-06-16 20:33:52 ] End function : url_gf 
[ 2022-06-16 20:33:52 ] Start function : wordlist_gen 
[ 2022-06-16 20:33:52 ] End function : wordlist_gen 
[ 2022-06-16 20:33:52 ] Start function : wordlist_gen_roboxtractor 
[ 2022-06-16 20:33:52 ] End function : wordlist_gen_roboxtractor 
[ 2022-06-16 20:33:52 ] Start function : password_dict 
[ 2022-06-16 20:33:52 ] End function : password_dict 
[ 2022-06-16 20:33:52 ] Start function : cors 
[ 2022-06-16 20:33:52 ] End function : cors 
[ 2022-06-16 20:33:52 ] Start function : crlf_checks 
[ 2022-06-16 20:33:52 ] End function : crlf_checks 
[ 2022-06-16 20:33:52 ] Start function : prototype_pollution 
[ 2022-06-16 20:33:52 ] End function : prototype_pollution 
[ 2022-06-16 20:33:52 ] Start function : spraying 
[ 2022-06-16 20:33:52 ] End function : spraying 
[ 2022-06-16 20:33:52 ] Start function : brokenLinks 
cat: .tmp/brokenLinks_total.txt: No such file or directory
[ 2022-06-16 20:33:52 ] End function : brokenLinks 
[ 2022-06-16 20:33:52 ] Start function : test_ssl 
Fatal error: Can't read file "hosts/ips.txt"
[ 2022-06-16 20:33:55 ] End function : test_ssl

**Comment by d1pakda5** [comment]
Yes already done that . after running the installer also i am getting this

**Comment by d1pakda5** [comment]
Tried in a fresh machine same issue i got

**Comment by six2dez** [comment]
Tested right now in a fresh Ubuntu machine and everything is working as expected

**Comment by d1pakda5** [comment]
I am getting same issue in here is the log

Start 2022-06-17 21:24:44
[ 2022-06-17 21:24:44 ] Start function : domain_info 
[ 2022-06-17 21:27:33 ] End function : domain_info 
[ 2022-06-17 21:27:33 ] Start function : emails 
[ 2022-06-17 21:28:18 ] End function : emails 
[ 2022-06-17 21:28:40 ] End function : google_dorks 
[ 2022-06-17 21:28:40 ] Start function : github_dorks 
[ 2022-06-17 21:28:40 ] End function : github_dorks 
[ 2022-06-17 21:28:40 ] Start function : metadata 
mv: cannot stat 'osint/safehats.com/*.txt': No such file or directory
[ 2022-06-17 21:28:52 ] End function : metadata 
[ 2022-06-17 21:28:52 ] Start function : zonetransfer 
[ 2022-06-17 21:28:52 ] End function : zonetransfer 
[ 2022-06-17 21:28:52 ] Start function : favicon 
[ 2022-06-17 21:28:53 ] End function : favicon 
[ 2022-06-17 21:28:53 ] Start subfunction : sub_passive 
[ 2022-06-17 21:41:23 ] End subfunction : 10012 new subs (passive) 
[ 2022-06-17 21:41:23 ] Start subfunction : sub_crt 
[ 2022-06-17 21:41:36 ] End subfunction : 11 new subs (cert transparency) 
[ 2022-06-17 21:41:36 ] Start subfunction : sub_active 
panic: runtime error: integer divide by zero

goroutine 43 [running]:
github.com/projectdiscovery/retryabledns.(*Client).QueryMultiple(0xc0000fdb80, {0xc0000342f0, 0xc}, {0xc000316340, 0x1, 0x0?})
	/root/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.13/client.go:240 +0xa4a
github.com/projectdiscovery/dnsx/libs/dnsx.(*DNSX).QueryMultiple(...)
	/root/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.0/libs/dnsx/dnsx.go:84
github.com/projectdiscovery/dnsx/internal/runner.(*Runner).worker(0xc0002c4140)
	/root/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.0/internal/runner/runner.go:555 +0x145
created by github.com/projectdiscovery/dnsx/internal/runner.(*Runner).startWorkers
	/root/go/pkg/mod/github.com/projectdiscovery/dnsx@v1.1.0/internal/runner/runner.go:541 +0xbd
[ 2022-06-17 21:41:38 ] End subfunction : 0 new subs (active resolution) 
[ 2022-06-17 21:41:38 ] Start subfunction : sub_brute 
cat: .tmp/subs_brute_valid.txt: No such file or directory
[ 2022-06-17 21:41:38 ] End subfunction : 0 new subs (bruteforce) 
[ 2022-06-17 21:41:38 ] Start subfunction : sub_permut 
cat: .tmp/permute1.txt: No such file or directory
cat: .tmp/permute2.txt: No such file or directory
[ 2022-06-17 21:41:38 ] End subfunction : 0 new subs (permutations) 
[ 2022-06-17 21:41:38 ] Start subfunction : sub_dns 
cat: .tmp/subdomains_dns_resolved.txt: No such file or directory
[ 2022-06-17 21:41:38 ] End subfunction : 0 new subs (dns resolution) 
[ 2022-06-17 21:41:38 ] Start subfunction : sub_scraping 
[ 2022-06-17 21:41:38 ] End subfunction : No subdomains to search (code scraping) 
[ 2022-06-17 21:41:38 ] Start subfunction : sub_analytics 
cat: .tmp/analytics_subs_resolved.txt: No such file or directory
[ 2022-06-17 21:41:38 ] End subfunction : 0 new subs (analytics relationship) 
[ 2022-06-17 21:41:38 ] Start subfunction : webprobe_simple 
cat: .tmp/web_full_info.txt: No such file or directory
[ 2022-06-17 21:41:39 ] End subfunction : 0 new websites resolved 
[ 2022-06-17 21:41:39 ] Start function : webprobe_full 
cat: .tmp/probed_uncommon_ports_tmp.txt: No such file or directory
[ 2022-06-17 21:41:39 ] End function : webprobe_full 
[ 2022-06-17 21:41:39 ] Start function : subtakeover 
[ 2022-06-17 21:42:15 ] End function : subtakeover 
[ 2022-06-17 21:42:16 ] Start function : s3buckets 
cat: .tmp/s3buckets.txt: No such file or directory
[ 2022-06-17 21:42:21 ] End function : s3buckets 
[ 2022-06-17 21:42:21 ] Start function : screenshot 
[ 2022-06-17 21:42:21 ] End function : screenshot 
[ 2022-06-17 21:42:21 ] Start function : cdnprovider 
[ 2022-06-17 21:42:21 ] End function : cdnprovider 
[ 2022-06-17 21:42:21 ] Start function : portscan 
[ 2022-06-17 21:42:21 ] End function : portscan 
[ 2022-06-17 21:42:21 ] Start function : waf_checks 
[ 2022-06-17 21:42:21 ] End function : waf_checks 
[ 2022-06-17 21:42:21 ] Start function : nuclei_check 
[ 2022-06-17 21:42:32 ] End function : nuclei_check 
[ 2022-06-17 21:42:32 ] Start function : fuzz 
[ 2022-06-17 21:42:32 ] End function : fuzz 
[ 2022-06-17 21:42:32 ] Start function : urlchecks 
[ 2022-06-17 21:42:32 ] Start function : jschecks 
[ 2022-06-17 21:42:32 ] End function : jschecks 
[ 2022-06-17 21:42:32 ] Start function : cms_scanner 
[ 2022-06-17 21:42:32 ] End function : cms_scanner 
[ 2022-06-17 21:42:32 ] Start function : url_gf 
[ 2022-06-17 21:42:32 ] End function : url_gf 
[ 2022-06-17 21:42:32 ] Start function : wordlist_gen 
[ 2022-06-17 21:42:32 ] End function : wordlist_gen 
[ 2022-06-17 21:42:32 ] Start function : wordlist_gen_roboxtractor 
[ 2022-06-17 21:42:32 ] End function : wordlist_gen_roboxtractor 
[ 2022-06-17 21:42:32 ] Start function : password_dict 
[ 2022-06-17 21:42:32 ] End function : password_dict 
[ 2022-06-17 21:42:32 ] Start function : cors 
[ 2022-06-17 21:42:32 ] End function : cors 
[ 2022-06-17 21:42:32 ] Start function : crlf_checks 
[ 2022-06-17 21:42:32 ] End function : crlf_checks 
[ 2022-06-17 21:42:32 ] Start function : prototype_pollution 
[ 2022-06-17 21:42:32 ] End function : prototype_pollution 
[ 2022-06-17 21:42:32 ] Start function : spraying 
[ 2022-06-17 21:42:32 ] End function : spraying 
[ 2022-06-17 21:42:32 ] Start function : brokenLinks 
cat: .tmp/brokenLinks_total.txt: No such file or directory
[ 2022-06-17 21:42:32 ] End function : brokenLinks 
[ 2022-06-17 21:42:32 ] Start function : test_ssl 
Fatal error: Can't read file "hosts/ips.txt"
[ 2022-06-17 21:42:35 ] End function : test_ssl 
End 2022-06-17 21:42:35
