### ISSUE TITLE
./install.sh: Line 36：[: (x86_64-apple-darwin21：Integer expression expected

### ISSUE THREAD

**Issue by cqrlhz** [six2dez/reconftw#538]
mac (macOs Monterey12.4)install report errors “./install.sh: Line 36：[: (x86_64-apple-darwin21：Integer expression expected” or "./install.sh: 第 36 行：[: (x86_64-apple-darwin21：需要整数表达式"

**Comment by six2dez** [comment]
Added bash check on dev version, you have to install bash before running reconftw on MacOS with `brew install bash`
