### ISSUE TITLE
dsieve is not installed with go install -v github.com/trickest/dsieve@latest

### ISSUE THREAD

**Issue by cyberindia1** [six2dez/reconftw#543]
****Describe** the bug**
dsieve is not installing by default.

**To Reproduce**
go install -v github.com/trickest/dsieve@latest
go: github.com/trickest/dsieve@latest: github.com/trickest/dsieve@v1.0.1: parsing go.mod:
        module declares its path as: dsieve
                but was required as: github.com/trickest/dsieve

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Architecture: [e.g. x86, x64, ARM ...]
 - OS: [e.g. Ubuntu, Kali, Arch ...]
 - Version [e.g. 20.04, Rolling, 8 ...]

**Additional context**

**Comment by six2dez** [comment]
Hey! I just released a fix on dev branch and pushed a PR to fix this into dsieve (https://github.com/trickest/dsieve/pull/7) and replaced the repo to my own already fixed (https://github.com/six2dez/reconftw/commit/4542718d2f3cb24700d768f544e5727b7e5195fa).

Soon will be fixed on main branch!

**Comment by cyberindia1** [comment]
Great! thanks.

**Comment by Manish4531** [comment]
Bhai camand
