### ISSUE TITLE
Config files are overwritten with every install.sh run

### ISSUE THREAD

**Issue by sumgr0** [six2dez/reconftw#544]
Hi!

I've been using Notify and Amass outside of the reconftw as well as most others shall be too. I've noticed that with every run of install.sh the config files for these at least are getting over write with the basic content.

Maybe we can check if the config file exists then need not download and over write to fix the issue.

Best,
sumgr0

**Comment by sumgr0** [comment]
PR done, hopefully it'll help fix the issue for others as well.

**Comment by six2dez** [comment]
PR accepted, "apparently" with `wget -q -O` only download the file is it doesn't exist, but anyway the solution purposed is valid too :) thanks man!

**Comment by sumgr0** [comment]
ah okay.. .thank you for accepting the change :)
