### ISSUE TITLE
Download precompiled Go tools

### ISSUE THREAD

**Issue by bileltechno** [six2dez/reconftw#55]
If any tool owner provide a compiled binary, the install script can be enhanced .

**Comment by hackingguy** [comment]
I just made a tar of precompiled Binaries. Please cross verify if you want!
All it need is to:
```bash
#Tar is already precompiled (Size is 1.5 GB, includes Tools,Nuclei  ,Go Binaries)
FILEID="1Tjw7NXw80TI1l40_8_hjEXwwMmwT-S7R"
confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id='$FILEID -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$confirm&id=$FILEID" -O ~/ins.tar.gz && rm -rf /tmp/cookies.txt
tar -xf ~/ins.tar.gz -C ~/ && mv ~/ins/* ~/ && rm -rf ~/ins
```
Also added it to [Bug Hunting Colab](https://github.com/hackingguy/Bug-Hunting-Colab), it's a powerful machine with 24 GB RAM (Completely Free).
Addition in google collab is a one-click execution without any issue!
You can add it to the readme section, easy to use, also I used compiled binaries in it.

**Comment by six2dez** [comment]
Sorry @hackingguy, I don't think this is an option. Personally I wouldn't trust a bunch of binaries (1,5gb!) from a third party source, I think everyone (or most at least) would prefer to get the binaries from the original sources and compile them themselves, anyway we will look at the possibility of get the latest compiled version from the vendors directly if they give this option which is the main purpose of this issue. Thanks :)

**Comment by hackingguy** [comment]
No issue, I will remove it from the collab, Keep it for personal use!
I will try to increase transparency as much as I can!

**Comment by hackingguy** [comment]
Trying to use a folder instead of a tar! but then repository size will increase too much! if you don't have an issue we can go further with making a folder inside the repo containing binaries!

**Comment by hackingguy** [comment]
Ohk we can't use binaries I understood! 😅

**Comment by bileltechno** [comment]
| Go Tool       | bin exist?     | 
| :------------- | :----------: | 
| [gf](github.com/tomnomnom/gf) | []   | 
| [qsreplace](github.com/tomnomnom/qsreplace) | []   | 
| [ffuf](github.com/ffuf/ffuf) | []   | 
| [assetfinder](github.com/tomnomnom/assetfinder) | []   | 
| [naabu](github.com/projectdiscovery/naabu/v2/cmd/naabu) | []   | 
| [waybackurls](github.com/tomnomnom/hacks/waybackurls) | []   | 
| [nuclei](github.com/projectdiscovery/nuclei/v2/cmd/nuclei) | []   |
| [aquatone](github.com/michenriksen/aquatone) | []   | 
| [anew](github.com/tomnomnom/anew) | []   |
| [subjack](github.com/haccer/subjack) | []   | 
| [httpx](github.com/projectdiscovery/httpx/cmd/httpx) | []   | 
| [subfinder](github.com/projectdiscovery/subfinder/v2/cmd/subfinder) | []   | 
| [dalfox](github.com/hahwul/dalfox) | []   |

**Comment by bileltechno** [comment]
@six2dez : This will  add at least 10 code lines per package (only supporting armv6 and linux 64).
So this issue will add at least **130** lines of code. which increase the complexity of code .
I don't think it worth this effort and complexity.

**Comment by six2dez** [comment]
Then we close this issue, nice research @bileltechno
