### ISSUE TITLE
dns enumeration not saved/resolved

### ISSUE THREAD

**Issue by hitem** [six2dez/reconftw#555]
**Describe the bug**
When i run the tool, im unable to get any resolved domains to be stored into the subdomains.txt file. It seems like pureDNS is unable to resolve anything.
![image](https://user-images.githubusercontent.com/8977898/183305603-97967c72-759c-47a1-ac3b-d22c2a643c3b.png)

If i pipe the same stuff list of urls through httpx instead i do get them resolved. (30 of them)
![image](https://user-images.githubusercontent.com/8977898/183305671-3f170fea-5dda-4ba4-a287-57d7f36f2130.png)

This might be an issue with PureDNS but ill try here first. I cant be the only one?
This results in almost no tools running as i cant get a working URL/subdomain file (even tho it finds 400+ subdomains for my target, but unable to resolve them so file gets removed). 

![image](https://user-images.githubusercontent.com/8977898/183306051-bce38636-5243-4d87-9551-be3b41550db9.png)

**Desktop (please complete the following information):**
- Architecture: x64
- OS: Kali
- Version 2022.3

**Additional context**
I also tried switching all the variables in reconftw.sh from 
```/home/op/lists/resolvers.txt``` 
```/home/op/lists/resolvers_trusted.txt``` 
to instead be 
```/root/Tools/resolvers.txt```
```/root/Tools/resolvers_trusted.txt``` 
That was my first step when resolving seems to not work, but it didnt help (however the path is correct now for my setup).

My current workaround is to run my own reconphase through **recon-ng**, check if its up with **httpx** and my own tool **isitup.sh**, then manually copy the results (**subdomains.txt**) into folder **/reconftw/recon/xxxx/subdomains/subdomains.txt** and then run modules individualy (-w etc).

Any advice welcome.
Greatly appreciated !

**Comment by six2dez** [comment]
Seems that you changed the necessary values for puredns, I would suggest you to download the default cfg file and reinstall the tool
