### ISSUE TITLE
go Installation Can't make it according to the environment variable set

### ISSUE THREAD

**Issue by Trapshell** [six2dez/reconftw#559]
System：Kali linux
I read the installation documentation and changed the environment variable configuration of the `reconftw.cfg`
But this didn't work, the `install.sh` didn't read the information I set, it still used the built-in settings.

because not according to the go environment variable I set
As a result, the go file will be created in the /home/ directory, and all programs will be in the go folder.
I just want to be able to install to the environment variable path I set, and apparently this aspect of the installer is not working properly, which is causing me problems.

This is the content of `reconftw.cfg`
<img width="598" alt="Snipaste_2022-08-10_21-52-26" src="https://user-images.githubusercontent.com/106905547/183918850-8ecdf44c-a13c-4bd1-9000-7a80d7b669c2.png">

This is the content of the system environment variables

`sudo vim /etc/profile`

##go Environment Variables
export GOROOT=/opt/go
export GOPATH=/home/trapshell/go-workspace
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export GOPROXY=https://proxy.golang.com.cn

Since I am using kde desktop, I am using konsole terminal (zsh)
so i try to modify the `.zshrc`

`sudo vim ~/.zshrc`

##go Environment Variables
export GOROOT=/opt/go
export GOPATH=/home/trapshell/go-workspace
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export GOPROXY=https://proxy.golang.com.cn

Apparently there was nothing wrong with my setup and the installer didn't execute the installer based on my system's environment variables.

If it's my problem, please bother to point out what the problem is.

**Comment by six2dez** [comment]
Hey @Trapshell ! let me try to help you with this.

The installer performs the following operations:

1. Check for go installation with `type go`
2. If 1 is true (aka `go is installed`), it checks if the go version is the latest, comparing `go version | cut -d " " -f3` against `curl -L -s https://golang.org/VERSION?m=text`.
3. If 1 and 2 are true, it doesn't perform any operation on the Golang environment, otherwise it installs Golang from zero on the default paths.

**Comment by six2dez** [comment]
Hey!
 I deployed a fix for this https://github.com/six2dez/reconftw/commit/beb548181f7123e0169cd7e12de38254d62b8c04, on dev branch, run installer or update by git pull making sure you have the latest reconftw.cfg file, there you can find a `install_golang` var, set it to `false` to skip all the golang installation and configuration. Let me know if this works for you :)
