### ISSUE TITLE
Python 3.10 temp fixes.

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#561]
1. Interlace fix see my thread: https://github.com/codingo/Interlace/issues/167

2. for  RequestsDependencyWarning: urllib3 (1.26.11) or chardet (3.0.4) doesn't match a supported version!
    warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported ":
     pip3 install --upgrade requests
     I upgraded to 2.28.1 and the error went away.

i'll post more fixes as I come across them.

**Comment by six2dez** [comment]
I'm planning to fully replace Interlace with https://github.com/shenwei356/rush almost everything replaced at https://github.com/six2dez/reconftw/commit/3c43c7e6ebc10d75beac9214a445b60e44a40ad2 so no need to maintain this issue
