### ISSUE TITLE
Facing multiple issue on installation on ARM based Kali Linux

### ISSUE THREAD

**Issue by coolerspeex** [six2dez/reconftw#562]
**Describe the bug**
<img width="812" alt="image" src="https://user-images.githubusercontent.com/56903633/184569102-05367b68-b839-40f6-a495-05f47622da8e.png">

**Additional context**
I think need improvements for the ARM based OS in reconftw

**Comment by six2dez** [comment]
Hey!  Sorry for the bug, it's now fixed and deployed both to dev and main branch https://github.com/six2dez/reconftw/pull/563/commits/cd9c18f2b08054e1c8bd2729563471560a47331b

![image](https://user-images.githubusercontent.com/24670991/184723916-d573bd4c-7069-46a1-940b-fb9b8ddab908.png)
