### ISSUE TITLE
Faster search speed

### ISSUE THREAD

**Issue by ptgeft** [six2dez/reconftw#564]
Any ideas on replacing grep / egrep with [rg](https://github.com/BurntSushi/ripgrep)? As the test results they mentioned, I think it will improve the search speed of reconftw.

**Comment by six2dez** [comment]
Hey! thanks for the suggestion, I like the idea but the regex applied in reconftw are not too heavy I think, also grep is installed by default on all *nix-like systems, so I wonder if it's worth installing it

**Comment by six2dez** [comment]
Do you think there is any special regex that could be improved in terms of speed?

**Comment by ptgeft** [comment]
Hi! This idea came to me when I was reviewing the code, I found that there are 100K or even 1000K lines of files `cat` and pipe them to `grep`, so I think whether there would be a speed impact, but after local testing, you are right, it looks fine:

```
$ wc -l .tmp/url_extract_tmp.txt
11194931 .tmp/url_extract_tmp.txt

$ time cat .tmp/url_extract_tmp.txt | grep -aEi "\.(${t})($|\/|\?)" >> /dev/null

real    0m1.281s
user    0m0.128s
sys     0m0.961s
```

As for the regex optimization, I don't have any idea yet, I will PR or open new issue when I find some better regex

Thanks for the quick response

**Comment by six2dez** [comment]
Maybe for some huge URL lists `rg` could show the impact, also if you want to replace `cat file | grep` lines with just `grep .... file.txt` feel free to do so, or even replace grep with `rg` directly, cleaner code and improved performance if the files are huge :)
