### ISSUE TITLE
Add -no-subs to waybackurls if subdomain enumeration is done

### ISSUE THREAD

**Issue by bthrx** [six2dez/reconftw#565]
**Is your feature request related to a problem? Please describe.**
Running on a t2 AWS instance and it crashes every time it gets to waybackurls. 

**Describe the solution you'd like**
Since the script has already completed subdomain enumumertation by that point, the list sent by cat already includes validated subdomains it doesn't feel necessary and lessens the load on anyone running on a smaller VPS instance.

**Describe alternatives you've considered**
Just a suggestion, I have modified the script to my liking in this regard but thought it was worth considering but not necessary to send a pull request.

**Additional context**
Running on an AWS t2.micro. Waybackurls doesn't have a way to set the threads.

**Comment by six2dez** [comment]
You're totally right! Fixed on dev https://github.com/six2dez/reconftw/commit/c50c9265a1cdb5321b75b46d07a0a6c21b6f33a6 soon on main ;)

**Comment by bthrx** [comment]
I ended up using xargs to slow it down even more because it still crashed my vps. Thinking about adding an option for running on small resources. will send pull request when done if you are interested. I am a beginner at scripting

**Comment by bthrx** [comment]
After some further testing on my local machine rather than my VPS I've come to discover that waybackurls -no-subs simply won't pull any url that has a subdomain, and did not work as intended with results. I do not recommend pushing this into the main branch after all. In order to slow I changed the script to  xargs -a .tmp/webs_all.txt -I % bash -c 'echo "%" | waybackurls | anew -q .tmp/urls_extract_tmp.txt'. This could be added to the config settings because with xargs you could set how many run at once with -P
