### ISSUE TITLE
Stuck at "Github Dorks in process"

### ISSUE THREAD

**Issue by spidyhackx** [six2dez/reconftw#566]
hi, the scan always gets stuck at ```Github Dorks in process```. It has been here for about 20mins

1. ```docker pull six2dez/reconftw:main```
2. ```docker run -it --rm -v "${PWD}/OutputFolder/":'/reconftw/Recon/' six2dez/reconftw:main -d example.com -a```

![image](https://user-images.githubusercontent.com/40536205/186926829-c0fbd3c5-8aeb-4398-ad28-c0a55659da0c.png)

OS: Debian GNU/Linux 11 (bullseye) x86_64
 - Version 2.3.2

**Comment by six2dez** [comment]
The time taken by this technique depends on the target, the number of GitHub tokens provided, your network.... being slow does not mean it is not working, sorry
