### ISSUE TITLE
Github Recon Upgradation

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#567]
Hey Devs,
The github recon currently used seems pretty brief and not bearing any useful results. It will be great if a deeper approach is implemented and not a high level dork system. Needs something which looks more deeply and produces more useful results. One way is finding company github profile, targeting employees and scanning the employees. 
Also some more dorks needs to be added, the complex ones. basic dorks like auth, login never return useful results. Needs to look for API regex in the dorks this can be achieved using tools like GitHound.

Thanks

**Comment by jakre1234** [comment]
TruffleHog*

**Comment by six2dez** [comment]
I love the idea <3

**Comment by six2dez** [comment]
I will use [enumerepo](https://github.com/trickest/enumerepo) + [Trufflehog](https://github.com/trufflesecurity/trufflehog)

**Comment by six2dez** [comment]
Done https://github.com/six2dez/reconftw/commit/848e70d92d52a63adfc17ca01cbce5c2ccae3b04

**Comment by jakre1234** [comment]
Thanks man. You are the best <3
