### ISSUE TITLE
Target list not scanned

### ISSUE THREAD

**Issue by MuhammadUsman-coder** [six2dez/reconftw#568]
Hi, 
I am trying to pass a list of targets and perform web checks only on those domains ,
but reconftw only scans the last target of the list . I tried multiple ways but its not working:

- ./reconftw.sh -l targetlist.txt -w
- ./reconftw.sh -m company -l targetlist.txt -w

It only scans the last target from list and exists and does not scan the rest of the targets from file.
Am i doing something wrong here?
Kindly help.

Thanks

**Comment by six2dez** [comment]
Confirmed bug, will fix soon

**Comment by six2dez** [comment]
Fixed in dev branch, will push to main during the week https://github.com/six2dez/reconftw/commit/93fcd299abe9173ee5429d4f2b00425e43895c7c
