### ISSUE TITLE
-o output directory not working

### ISSUE THREAD

**Issue by MuhammadUsman-coder** [six2dez/reconftw#569]
Hi ,
I tried saving the output of scan in custom directory but it still saves it in the 'Recon' folder  instead of mentioned folder.
I used the below commands:

- ./reconftw.sh -d domain.com -a -o outputfolder/
- ./reconftw.sh -d domain.com -w -o /root/output

Kindly look into it.
Thanks

**Comment by six2dez** [comment]
It moves to the custom output at the end of the scan
