### ISSUE TITLE
when running install command,  ./install.sh , I always get ripgen error:

### ISSUE THREAD

**Issue by adam9901** [six2dez/reconftw#570]
[*] ripgen             [NO]

 Try running the installer script again ./install.sh
 If it fails for any reason try to install manually the tools missed
 Finally remember to set the $tools variable at the start of this script
 If nothing works and the world is gonna end you can always ping me :D

**Comment by six2dez** [comment]
As the help message has suggested, have you tried to install ripgen by yourself?

**Comment by adam9901** [comment]
yes ripgen works in my ubuntu machine but i still get the error

**Comment by six2dez** [comment]
the it is not on your $PATH var which is the output of `which ripgen` ?

**Comment by adam9901** [comment]
it is definitely in my $PATH and ripgen works fine in my system however installation gives error, I am not sure why

**Comment by adam9901** [comment]
I have closed the terminal and opened and run the install command and it seems to be working now
