### ISSUE TITLE
Some Pre Installation Requirements

### ISSUE THREAD

**Issue by HackerAndya** [six2dez/reconftw#575]
Whenever I try to install some tools fail to install. And I need to install those manually.  I install GCC, python, pip3, and also some installation commands for go lang tools like @latest is a new way to install tools. If we add these things to requirement.txt or somewhere else then anyone can easily install reconFTW without any error.

**Comment by sidxparab** [comment]
It's interesting that `python` `pip` & `GCC` are not getting installed. As these are installed through your own package manager.

Morever, I guess you have a misconception about the `requirements.txt` file. The requirements.txt files only contains those tools which are shipped as python-packages. Inshort only those that are written in python.

Also, there are times, when 1-2 Go tools fail to get installed. But in that case you have no other option but to run the `install.sh` script again or install those tools manually.

Also, make sure you are having a stable connection while running the installer script.

Can you mention what system are you using?

**Comment by HackerAndya** [comment]
AWS ubuntu VPS

**Comment by six2dez** [comment]
Have you tried to run `./install.sh`?

**Comment by HackerAndya** [comment]
Yes, I've tried. But maybe we can add somewhere that the gcc and pip3 are prerequisites. So it'll save effort. Moreover, the tool is great.

**Comment by six2dez** [comment]
Both packages are included to be installed on the OS. No idea why it's not working for you
