### ISSUE TITLE
ripgen not installed 

### ISSUE THREAD

**Issue by wtwver** [six2dez/reconftw#577]
cargo is not installed on docker kali image default 

https://github.com/six2dez/reconftw/blob/5448e7cfd063ab107e2eacfc4e23143f22d0d670/install.sh#L133

Would be nice to add line to install cargo or install ripgen alternatively

**Comment by six2dez** [comment]
Tested and installed properly. Eventually some tools may fall to install, you can enter on the Docker container and run the installer again. Also, the Docker container is running the reconftw's installer itself so there is no need to add a line to install cargo or ripgen.
