### ISSUE TITLE
Default small value for PUREDNS_PUBLIC_LIMIT 

### ISSUE THREAD

**Issue by wtwver** [six2dez/reconftw#578]
Would it be nice to set PUREDNS_PUBLIC_LIMIT as small value like 500 as default, add new flag to unleash the unlimited power instead.

From my experience, i blow up many router. Not sure if thats common issue.

https://github.com/six2dez/reconftw/blob/5448e7cfd063ab107e2eacfc4e23143f22d0d670/reconftw.cfg#L152

**Comment by six2dez** [comment]
Most of the ppl using reconftw uses it on VPS, where there is no problem with this value. That's why by default there is no limit on this tool.
