### ISSUE TITLE
Error during Web Directory Fuzzing

### ISSUE THREAD

**Issue by kleozzy** [six2dez/reconftw#579]
**Describe the bug**
An error thrown while in web directory fuzzing stage

`parse error: Invalid numeric literal at line 2, column 0`

**To Reproduce**
Just run the script with -r flag and error is thrown after Nuclei scan at web directory fuzzing stage.
Was stuck for 13 hours for me and then thrown error.

**Expected behavior**
Web directory fuzzing script executes and discovers dirs and file i guess.

**Desktop (please complete the following information):**
- Architecture: x64
 - OS: WSL 2 Ubuntu 22.04.1 LTS

**Comment by six2dez** [comment]
Hi! I fixed a bug on web fuzzing https://github.com/six2dez/reconftw/commit/28b1c23bd42e0da2bd072029447150127c2a2e9c , please update and try again. Thanks!
