### ISSUE TITLE
why does my internet connection die after the brute force subdomain is running?

### ISSUE THREAD

**Issue by zufan-yp** [six2dez/reconftw#583]
**Describe the bug**
so I tried to scan as usual but when I was in the bruteforce subdomain menu, my internet suddenly died, and it was like being stuck in the bruteforce subdomain, I had tried it many times by changing the recon config etc., until I waited for hours, still stuck in the bruteforce subdomain. is there any solution about this?

**Screenshots**
![image](https://user-images.githubusercontent.com/78656480/190942247-106e45cf-4a74-4398-ba53-3da0ea83f19f.png)

**Desktop (please complete the following information):**
- Architecture: [e.g. x86, x64, ARM]
 - OS: [e.g. Kali,Debian in WSL2]
 - Version [e.g.Rolling]

**Comment by six2dez** [comment]
https://github.com/six2dez/reconftw/wiki/7.-FAQs#usage
