### ISSUE TITLE
[docs] Mention support for large files

### ISSUE THREAD

**Issue by nicoandmee** [six2dez/reconftw#597]
@six2dez I guess github doesn't have the ability to create a PR for wiki content, so please add this snippet on the `FAQ` page if you think it would be helpful!

## Support for larger files

* Discord by default limits uploads from bots to [8MB](https://stackoverflow.com/questions/66377217/is-it-possible-to-attach-a-file-bigger-than-150mb-in-discord-py-using-my-bot#:~:text=As%20a%20regular%20user%20or,I%20have%20tested%20this%20myself).
* If the size of your result set exceeds this size, the script will use [transfer.sh](https://transfer.sh/) to do the upload, and will send the link instead of the raw zip to all notify providers (including discord, and telegram if configured as such).
* You can even use [notify](https://github.com/projectdiscovery/notify) to `POST` this to a custom webhook/endpoint like <https://pipedream.com/> for example, and have the file saved and unpacked in your preferred cloud drive if desired. 🤓

**Comment by six2dez** [comment]
Done! Thanks man!!!!
