### ISSUE TITLE
yum is called under ubuntu 20.04

### ISSUE THREAD

**Issue by bileltechno** [six2dez/reconftw#6]
yum is called under **ubuntu 20.04** and this call is caused by

``` .sh
test -f /etc/os-release && install_yum
```
Is  the first check of yum not enough ? 
``` .sh
test -f /etc/redhat-release && install_yum
```

**Comment by bileltechno** [comment]
I suggest to make those tests in **if .. else if .. else** so when it detects apt it will call install_apt and exit the if condition or continue checking for yum, emerge, pacman ....

**Comment by six2dez** [comment]
Commented for the moment 5ab041fee9d5980df700c1a4489c3f8889be23b0 I will improve this part soon, thanks!
Will close when it's completely fixed :)

**Comment by six2dez** [comment]
Done 06dd5e36facd4fe0e186ca5cad12226ee94d4f24
