### ISSUE TITLE
Progress bar for subdomain enumeration

### ISSUE THREAD

**Issue by bileltechno** [six2dez/reconftw#61]
Subdomain enumeration is so time consuming.
A progress bar can tell the user that things are moving.

**Comment by six2dez** [comment]
[Garud](https://github.com/R0X4R/Garud) has progress bar in bash, maybe it deserves a look

**Comment by bileltechno** [comment]
@six2dez  : 
Sorry Graus developers but the progress bar is fully static 
``` .js
check_xss() {
    echo -ne "${NORMAL}${BOLD}${YELLOW} ● Scanning is in progress:${NORMAL}${BOLD} Checking for xss in $domain [${GREEN}${BLINK}85%${NORMAL}] \r"
    
```

**Comment by KathanP19** [comment]
have you tried pv command?

**Comment by six2dez** [comment]
Tried with shuffledns and other tools, but the results are not what I expected

**Comment by KathanP19** [comment]
can you share what command you tried?
