### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by Abdelrahmanibrahim-prog** [six2dez/reconftw#610]
when URL EXTRACTION work i have permission denied and it did not work, how could i solve this problem ?

**Comment by six2dez** [comment]
As suggested during the installation, add your user to sudoers

**Comment by Abdelrahmanibrahim-prog** [comment]
iam sorry but could you explain in detail how to do that ?

**Comment by Abdelrahmanibrahim-prog** [comment]
> As suggested during the installation, add your user to sudoers

iam sorry but could you explain in detail how to do that ?
