### ISSUE TITLE
Missing "emailfinder" , but what is the "emailfinder" and how to install it ?

### ISSUE THREAD

**Issue by cokeBeer** [six2dez/reconftw#611]
**Describe the bug**
After installed the reconftw, I ran `./reconftw.sh -d some.com -r`, and got
<img width="664" alt="image" src="https://user-images.githubusercontent.com/70683161/198948935-991b8b69-b00f-4d6e-afb1-da7bcc8d8ee8.png">
I can install other tools, but I don't know what is the "emailfinder".
I searched on github and your install.sh, but still could not get ideal solution.

**Comment by six2dez** [comment]
You can find it in the readme and the source code itself ;)  https://github.com/Josue87/EmailFinder
