### ISSUE TITLE
Docker domain enumeration wget: missing URL

### ISSUE THREAD

**Issue by sven-hash** [six2dez/reconftw#613]
**Describe the bug**
In docker the domain enumaration doesn't work, wrong parameter in wget

```
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```

**To Reproduce**
1. Pull docker image `docker pull  six2dez/reconftw:main`
2. Start the scan `docker run -it --rm  six2dez/reconftw:main -d test.com -a` 
3. Scroll down to ` Subdomain Enumeration test.com`

**Expected behavior**
List of detected domain

**Desktop (please complete the following information):**
- Architecture:  [x64]
 - OS: [e.g. Ubuntu]
 - Version [e.g. 20.04.]
 - Docker [Docker version 20.10.17, build 100c701]

**Comment by six2dez** [comment]
Closed due inactivity
