### ISSUE TITLE
How to install reconftw in ARCH Linux ? It not installing in ARCH Linux :-(

### ISSUE THREAD

**Issue by CyberGhazi786** [six2dez/reconftw#615]
Dear Sir,

I am trying to install reconftw in my arch linux but its not working.
Latest Go language is installed already.
Go Version:
[root@cyberghazi786-vmwarevirtualplatform reconftw]# go version
go version go1.19.3 linux/amd64
Go Path is:
root@cyberghazi786-vmwarevirtualplatform reconftw]# which go
/usr/local/bin/go
Amass Path is:
[root@cyberghazi786-vmwarevirtualplatform reconftw]# which amass
/usr/bin/amass

ReconFTW erros details:

[root@cyberghazi786-vmwarevirtualplatform reconftw]# bash install.sh

#######################################################################
 reconFTW installer/updater script 

 This may take time. So, go grab a coffee! 

 Running: Looking for new reconFTW version

 reconFTW is already up to date!

 Running: Installing system packages 

 Running: Installing/Updating Golang 

go: cannot find GOROOT directory: /usr/local/go
 Running: Installing requirements 

 Running: Installing Golang tools (37)

 inscope installed (1/37)
 puredns installed (2/37)
 waybackurls installed (3/37)
 interactsh-client installed (4/37)
 nuclei installed (5/37)
 analyticsrelationships installed (6/37)
 ipcdn installed (7/37)
 dnsx installed (8/37)
 dalfox installed (9/37)
 gitdorks_go installed (10/37)
 roboxtractor installed (11/37)
 Unable to install gau, try manually (12/37)
 Unable to install Gxss, try manually (13/37)
 Unable to install mapcidr, try manually (14/37)
 Unable to install qsreplace, try manually (15/37)
 Unable to install notify, try manually (16/37)
 Unable to install dsieve, try manually (17/37)
 Unable to install gotator, try manually (18/37)
 Unable to install gospider, try manually (19/37)
 Unable to install subfinder, try manually (20/37)
 Unable to install smap, try manually (21/37)
 Unable to install crlfuzz, try manually (22/37)
 Unable to install Web-Cache-Vulnerability-Scanner, try manually (23/37)
 Unable to install httpx, try manually (24/37)
 Unable to install gowitness, try manually (25/37)
 Unable to install ffuf, try manually (26/37)
 Unable to install subjs, try manually (27/37)
 Unable to install github-endpoints, try manually (28/37)
 Unable to install unfurl, try manually (29/37)
 Unable to install anew, try manually (30/37)
 Unable to install rush, try manually (31/37)
 Unable to install gf, try manually (32/37)
 Unable to install Amass, try manually (33/37)
 Unable to install tlsx, try manually (34/37)
 Unable to install github-subdomains, try manually (35/37)
 Unable to install enumerepo, try manually (36/37)
 Unable to install dnstake, try manually (37/37)

 Running: Installing repositories (26)

install.sh: line 291: /root/nuclei-templates/ssrf_nagli.yaml: No such file or directory
install.sh: line 292: /root/nuclei-templates/sap-redirect_nagli.yaml: No such file or directory
install.sh: line 294: cd: /root/nuclei-templates/extra_templates: No such file or directory
 Unable to install dnsvalidator, try manually (1/26)
 Unable to install wafw00f, try manually (2/26)
 Unable to install ultimate-nmap-parser, try manually (3/26)
 Unable to install Corsy, try manually (4/26)
 Unable to install CMSeeK, try manually (5/26)
 Unable to install gitdorks_go, try manually (6/26)
 Unable to install dorks_hunter, try manually (7/26)
 Unable to install brutespray, try manually (8/26)
 Unable to install JSA, try manually (9/26)
 Unable to install trufflehog, try manually (10/26)
package .: no Go files in /root/Tools
 Unable to install pydictor, try manually (11/26)
 Unable to install smuggler, try manually (12/26)
 Unable to install cloud_enum, try manually (13/26)
 Unable to install testssl, try manually (14/26)
 Unable to install Web-Cache-Vulnerability-Scanner, try manually (15/26)
 Unable to install Oralyzer, try manually (16/26)
 Unable to install theHarvester, try manually (17/26)
 Unable to install ctfr, try manually (18/26)
 Unable to install fav-up, try manually (19/26)
 Unable to install massdns, try manually (20/26)
 Unable to install xnLinkFinder, try manually (21/26)
 Unable to install gf, try manually (22/26)
 Unable to install commix, try manually (23/26)
 Unable to install urless, try manually (24/26)
 Unable to install pwndb, try manually (25/26)
 Unable to install Gf-Patterns, try manually (26/26)
chmod: cannot access '/usr/local/bin/ppfuzz': No such file or directory

 Running: Downloading required files 

install.sh: line 395: /root/nuclei-templates/extra_templates/ssrf.yaml: No such file or directory
install.sh: line 396: /root/nuclei-templates/extra_templates/sap-redirect.yaml: No such file or directory
 Running: Double check for installed tools 

mkdir: cannot create directory ‘/root/.bbrf/’: No space left on device
 Running: Performing last configurations 

 Remember set your api keys:
 - amass (~/.config/amass/config.ini)
 - subfinder (~/.config/subfinder/provider-config.yaml)
 - GitHub (~/Tools/.github_tokens)
 - SSRF Server (COLLAB_SERVER in reconftw.cfg or env var) 
 - Blind XSS Server (XSS_SERVER in reconftw.cfg or env var) 
 - notify (~/.config/notify/provider-config.yaml) 
 - theHarvester (~/Tools/theHarvester/api-keys.yaml or /etc/theHarvester/api-keys.yaml)
 - H8mail (~/Tools/h8mail_config.ini)
 - WHOISXML API (WHOISXML_API in reconftw.cfg or env var)

 Finished!

#######################################################################
[root@cyberghazi786-vmwarevirtualplatform reconftw]#

**Comment by six2dez** [comment]
Seems that you lost network connectivity after installing `roboxtractor` based on the info provided

**Comment by six2dez** [comment]
Closed due inactivity
