### ISSUE TITLE
Please add the ability to change BBRF program

### ISSUE THREAD

**Issue by h3xitsec** [six2dez/reconftw#616]
I think it'd be nice to be able to customise the BBRF program name to store multiple domains into a single program

**Comment by anasbousselham** [comment]
The idea is to add a cli args like `--bbrf-name` and update the line 2287 `program_bbrf=$(echo $domain | awk -F. '{print $1"_"$2}') 2>>"$LOGFILE" &>/dev/null` to accept the variable.

**Comment by jakre1234** [comment]
We can close this issue as bbrf is no longer supported with reconftw @six2dez

**Comment by six2dez** [comment]
Thanks @jakre1234
