### ISSUE TITLE
ripgen Rust Cargo installation and running errors

### ISSUE THREAD

**Issue by CyberGhazi786** [six2dez/reconftw#617]
Dear Sir,

After spending 10 days I have successfully installed reconFTW in my new parrotsec Os machine but ripgen is not working :-(
These are the steps that I followed but alas after all these steps ripgen works but upon closing the same terminal window, all goes wrong :-(
I got many errors about Rust Cargo so I removed all Rust and Cargo packages and reinstalled them.
Here are command sequence I followed.

# apt remove rustc
# rustc --version
bash: /usr/bin/rustc: No such file or directory
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1
root@cyberghazi-vmwarevirtualplatform:/# cargo install ripgen
    Updating crates.io index
     Ignored package `ripgen v0.1.3` is already installed, use --force to override
root@cyberghazi-vmwarevirtualplatform:/# cargo install ripgen --force
root@cyberghazi-vmwarevirtualplatform:/# source $HOME/.cargo/env
root@cyberghazi-vmwarevirtualplatform:/# source $HOME/.bashrc  // This is only for bash shell users 
root@cyberghazi-vmwarevirtualplatform:/# source $HOME/.profile

Now please guide how to fix this problem.

Thanks,

**Comment by six2dez** [comment]
Seems that your environment is broken, I strongly recommend you to install it in a new fresh machine
