### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gprime31** [six2dez/reconftw#618]
.

**Comment by gprime31** [comment]
same with function sub_crt()

**Comment by sidxparab** [comment]
@gprime31 Hope you found it !!! Anyways if you didn't below is the explanation:

The[ line 416](https://github.com/six2dez/reconftw/blob/main/reconftw.sh#L416) of reconftw.sh contains a find command which finds for files matching the pattern `*_subs.txt`. The functions `sub_passive()` and `sub_crt()` produces  **passive_subs.txt** and **crtsh_subs.txt** respectively.

Hence, the find command catches theses files and cats' the contents into a single file, which sent for DNS resolution.

**Comment by gprime31** [comment]
I did, that's why I deleted it, 
Thanks though.
