### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by a-oneil** [six2dez/reconftw#62]
**Describe the bug**
Hey there, currently having issues with the latest pull of the install script. I am running this on Kali 2020.4 as root with the GOPATH / GOROOT path as seen in the screenshot below. During install, I get an error message:
```
  Using /usr/local/lib/python3.9/dist-packages/EditorConfig-0.12.3-py3.9.egg
Finished processing dependencies for LinkFinder==1.0
Traceback (most recent call last):
  File "/root/Tools/pymeta/setup.py", line 3, in <module>
    with open("README.md", "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md
```

And left with a bunch of tools uninstalled. While I understand the README.md says installer is as is, I did not have this error message on a pull I did last week of this app. Any help would be much appreciated as to what I am missing. Thank you!

**To Reproduce**
1. Run the install script.

**Expected behavior**
Tools being installed when running the install script.

**Screenshots**
![image](https://user-images.githubusercontent.com/18233106/105667300-fc93e680-5ea8-11eb-8a1c-902244ee4e5e.png)
![image](https://user-images.githubusercontent.com/18233106/105667078-af177980-5ea8-11eb-91e7-c93286bd771b.png)
![image](https://user-images.githubusercontent.com/18233106/105667263-ed149d80-5ea8-11eb-97a4-80bc470502c6.png)

**Desktop (please complete the following information):**
- Architecture: x64
 - OS: Kali
 - Version 2020.4

**Comment by detonxx** [comment]
I guess this issue is occurring due to the Go _PATH_ not set correctly  
try adding these to your `.bashrc`
and then run the `./install.sh` again 
```
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
```

**Comment by a-oneil** [comment]
Hey @detonxx 

That fixed my issue. Thank you. I submitted a pull request to get that added into the readme.md to prevent further confusion for those who are unfamiliar with path. #63

**Comment by detonxx** [comment]
Sure.... @six2dez is working on the "Wiki" part, which may include all these steps for installation and post installation.
It would be up soon. Do check it out later !

**Comment by c-cube007** [comment]
I did the ./install.sh on my parrot os terminal, it ran well but the tools required did not install and I was told to install them manually which I don't know how. Please can someone assist me?

**Comment by virus0699** [comment]
everytime i run the ./install.sh command, my installation stucks after completing the repositories installation.i have waite for 4-5 hours, but it doesn't help

**Comment by bileltechno** [comment]
> I did the ./install.sh on my parrot os terminal, it ran well but the tools required did not install and I was told to install them manually which I don't know how. Please can someone assist me?

Can you please provide more information about the non installed tools?

**Comment by bileltechno** [comment]
> everytime i run the ./install.sh command, my installation stucks after completing the repositories installation.i have waited for 4-5 hours, but it doesn't help

Could you please share the error from the terminal?
