### ISSUE TITLE
Installer hangs after `brew is already installed` (Macbook Pro M1)

### ISSUE THREAD

**Issue by mrtnrdl** [six2dez/reconftw#624]
**Describe the bug**
After cloning the repository I want to install `reconftw`. When I run the installer, it never goes further than `brew is already installed`, no matter how long I wait. 

**To Reproduce**
1. Go to 'reconftw' folder
2. Execute './install.sh'
3. Wait - and see nothing happening

**Expected behavior**
The installer should continue to install the necessary tools and dependencies

**Screenshots**
<img width="502" alt="image" src="https://user-images.githubusercontent.com/1167062/208650720-8d05f883-ec3f-4201-be4b-b4db99f3418a.png">

**Desktop (please complete the following information):**
- Architecture: AARM (Apple M1 Max)
 - OS: macOS Ventura
 - Version 13.1

**Comment by six2dez** [comment]
Hi, I currently do not have access to a Mac OS device, can you modify the following lines in `reconftw.cfg` and run the installer again? It will print out all the tasks performed, then you can check where it is stuck:

Change this 2 lines:
https://github.com/six2dez/reconftw/blob/cd7fd961e87bb7484fd128ba24972cc35f957186/reconftw.cfg#L38
https://github.com/six2dez/reconftw/blob/cd7fd961e87bb7484fd128ba24972cc35f957186/reconftw.cfg#L39

And set them as:

```
DEBUG_STD="" # Skips STD output on installer
DEBUG_ERROR="" # Skips ERR output on installer
```

Let me know where it is stuck, thanks!

**Comment by mrtnrdl** [comment]
Thanks for the reply! 

It seems to work when the errors are not piped to `/dev/null`. 

After the first run i got  

```
Error: Formula `tor` is not installed.
```

which i just manually `brew install tor`'ed. The installer then succeeded. 

Afterwards I reverted the config - and same behaviour again. Hangs for over 20 minutes on `brew is already installed`. 

I _suspect_ it's `rustup`. The installer asks wether or not you want to continue the installation, modify or cancel it. So if you just wait for a while after it appears to be hanging, it continues the installation.

**Comment by six2dez** [comment]
Ok, so I will not pipe to /dev/null both `brew install rustup` and `rustup-init` in case they need user interaction on next release. Thanks!

**Comment by six2dez** [comment]
Fixed! https://github.com/six2dez/reconftw/releases/tag/v2.5.1
