### ISSUE TITLE
Nuclei Template Issue - [FTL] Could not run nuclei: no valid templates were found

### ISSUE THREAD

**Issue by rado685** [six2dez/reconftw#634]
**Describe the bug**
[FTL] Could not run nuclei: no valid templates were found 

**To Reproduce**
./reconftw.sh -d testphp.vulnweb.com -a

#######################################################################
#######################################################################
 Templates based web scanner 

 Running : Nuclei info 

[FTL] Could not run nuclei: no valid templates were found

 Running : Nuclei low 

[FTL] Could not run nuclei: no valid templates were found

 Running : Nuclei medium 

[FTL] Could not run nuclei: no valid templates were found

 Running : Nuclei high 

[FTL] Could not run nuclei: no valid templates were found

 Running : Nuclei critical 

[FTL] Could not run nuclei: no valid templates were found

**Expected behavior**
Nuclei should run and show the results

**Screenshots**
Attached

**Desktop (please complete the following information):**
VPS

<img width="612" alt="Screenshot 2023-01-09 at 2 26 02 PM" src="https://user-images.githubusercontent.com/64378951/211278878-e3cdfe0a-6fa5-45a7-83ec-2f2521e2837d.png">

**Comment by six2dez** [comment]
Update to the latest version and make sure you have sudo permissions (if you're not running as root you should run this command `echo "${USERNAME}  ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/reconFTW`)

**Comment by rado685** [comment]
Yes I'm running as a root "sudo ./reconftw.sh -d testphp.vulnweb.com -a" 
I have updated reconftw to the latest version using ./install.sh and still that error is showing.

Please support!

 Running : Nuclei info 

[FTL] Could not run nuclei: no valid templates were found

 Running : Nuclei low 

[FTL] Could not run nuclei: no valid templates were found

 Running : Nuclei medium 

[FTL] Could not run nuclei: no valid templates were found

 Running : Nuclei high 

[FTL] Could not run nuclei: no valid templates were found

 Running : Nuclei critical 

[FTL] Could not run nuclei: no valid templates were found

**Comment by six2dez** [comment]
It's already fixed, upgrade and reinstall
