### ISSUE TITLE
Wrong filename in wiki for The Harvester config file

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [six2dez/reconftw#636]
[The wiki section for The Harvester](https://github.com/six2dez/reconftw/wiki/1.-Post-Installation-Guide#7-theharvester-config) says that the config file is at `~/Tools/theHarvester/api-keys.yml`, but as of v2.5.1 the config file is at `~/Tools/theHarvester/api-keys.yaml`

**Comment by six2dez** [comment]
Fixed!
