### ISSUE TITLE
how to order :

### ISSUE THREAD

**Issue by mjulda** [six2dez/reconftw#643]
how to order :
GOROOT
GOPATH
PATH

#golang vars
export GOROOT=/usr/local/go
export GOPATH=\$HOME/go
export PATH=\$GOPATH/bin:\$GOROOT/bin:\$HOME/.local/bin:\$PATH

[ -n "$GOPATH" ] || { printf "${bred} GOPATH env var not detected, add Golang env vars to your \$HOME/.bashrc or \$HOME/.zshrc:\n\n export GOROOT=/usr/local/go\n export GOPATH =\$HOME/go\n export PATH=\$GOPATH/bin:\$GOROOT/bin:\$PATH\n\n"; exit 1; ,
[ -n "$GOROOT" ] || { printf "${bred} GOROOT env var not detected, add Golang env vars to your \$HOME/.bashrc or \$HOME/.zshrc:\n\n export GOROOT=/usr/local/go\n export GOPATH =\$HOME/go\n export PATH=\$GOPATH/bin:\$GOROOT/bin:\$PATH\n\n"; exit 1; ,

di Windows

When I try to find the location of ./go, I get an error like this: cannot find GOROOT directory: C:\Program Files\Git\usr\local\go
Although I have already added environment.

**Comment by six2dez** [comment]
reconFTW is not supported on Windows
