### ISSUE TITLE
Add default tools

### ISSUE THREAD

**Issue by forkbombruler** [six2dez/reconftw#648]
Great job, I've been using it as a mini virtual OS (docker run --entrypoint '/bin/bash' -idt $IMAGE_ID -c "tail -f /dev/null") but would like to install some other nice tools by default,thanks::
https://github.com/tomnomnom/unfurl
https://github.com/guelfoweb/knock
https://github.com/projectdiscovery/naabu
https://github.com/projectdiscovery/katana
https://github.com/lcvvvv/kscan

**Comment by six2dez** [comment]
Hi, the toolset for reconftw is manually curated in a daily basis, some of the tools you mention are already used, others will not.
