### ISSUE TITLE
3 tools not being installed in Mac M1

### ISSUE THREAD

**Issue by Aviral2642** [six2dez/reconftw#650]
ERROR:- 

 [*] Massdns			[NO]
 [*] jq				[NO]
 [*] ppfuzz			[NO]

 Try running the installer script again ./install.sh
 If it fails for any reason try to install manually the tools missed
 Finally remember to set the $tools variable at the start of this script
 If nothing works and the world is gonna end you can always ping me :D

 Tools check finished

I can't install these tools in Mac M1  

I tried installing ppfuzz and this error occurred 

sudo cargo install ppfuzz
    Updating crates.io index
  Installing ppfuzz v1.0.1
   Compiling proc-macro2 v1.0.51
   Compiling quote v1.0.23
   Compiling unicode-ident v1.0.6
   Compiling syn v1.0.107
   Compiling autocfg v1.1.0
   Compiling libc v0.2.139
   Compiling version_check v0.9.4
   Compiling cfg-if v1.0.0
   Compiling memchr v2.5.0
   Compiling futures-core v0.3.26
   Compiling pin-project-lite v0.2.9
   Compiling futures-io v0.3.26
   Compiling slab v0.4.7
   Compiling value-bag v1.0.0-alpha.9
   Compiling crossbeam-utils v0.8.14
   Compiling log v0.4.17
   Compiling waker-fn v1.1.0
   Compiling parking v2.0.0
   Compiling event-listener v2.5.3
   Compiling typenum v1.16.0
   Compiling fastrand v1.9.0
   Compiling concurrent-queue v2.1.0
   Compiling generic-array v0.14.6
   Compiling futures-lite v1.12.0
   Compiling polling v2.5.2
   Compiling itoa v1.0.5
   Compiling serde_derive v1.0.152
   Compiling async-io v1.12.0
   Compiling serde v1.0.152
   Compiling futures-channel v0.3.26
   Compiling tinyvec_macros v0.1.1
   Compiling futures-task v0.3.26
   Compiling tinyvec v1.6.0
   Compiling async-lock v2.6.0
   Compiling getrandom v0.2.8
   Compiling socket2 v0.4.7
   Compiling signal-hook v0.3.15
   Compiling once_cell v1.17.1
   Compiling futures-util v0.3.26
   Compiling pin-utils v0.1.0
   Compiling serde_json v1.0.93
   Compiling async-task v4.3.0
   Compiling futures-sink v0.3.26
   Compiling unicode-normalization v0.1.22
   Compiling block-buffer v0.10.3
   Compiling crypto-common v0.1.6
   Compiling rand_core v0.6.4
   Compiling async-channel v1.8.0
   Compiling signal-hook-registry v1.4.1
   Compiling async-process v1.6.0
   Compiling percent-encoding v2.2.0
   Compiling ryu v1.0.12
   Compiling thiserror v1.0.38
   Compiling ppv-lite86 v0.2.17
   Compiling unicode-bidi v0.3.10
   Compiling httparse v1.8.0
   Compiling atomic-waker v1.1.0
   Compiling idna v0.3.0
   Compiling blocking v1.3.0
   Compiling rand_chacha v0.3.1
   Compiling form_urlencoded v1.1.0
   Compiling digest v0.10.6
   Compiling async-executor v1.5.0
   Compiling aho-corasick v0.7.20
   Compiling ctor v0.1.26
   Compiling futures-macro v0.3.26
   Compiling thiserror-impl v1.0.38
   Compiling cpufeatures v0.2.5
   Compiling fnv v1.0.7
   Compiling either v1.8.1
   Compiling regex-syntax v0.6.28
   Compiling bytes v1.4.0
   Compiling kv-log-macro v1.0.7
   Compiling http v0.2.8
   Compiling regex v1.7.1
   Compiling async-global-executor v2.3.1
   Compiling sha-1 v0.10.1
   Compiling async-attributes v1.1.2
   Compiling url v2.3.1
   Compiling rand v0.8.5
   Compiling indexmap v1.9.2
   Compiling byteorder v1.4.3
   Compiling heck v0.4.1
   Compiling base64 v0.13.1
   Compiling utf-8 v0.7.6
   Compiling async-std v1.12.0
   Compiling tungstenite v0.17.3
   Compiling futures-executor v0.3.26
   Compiling atty v0.2.14
   Compiling linked-hash-map v0.5.6
   Compiling hashbrown v0.12.3
   Compiling os_str_bytes v6.4.1
   Compiling clap_lex v0.2.4
   Compiling yaml-rust v0.4.5
   Compiling chromiumoxide_types v0.3.5
   Compiling chromiumoxide_pdl v0.3.5
   Compiling futures v0.3.26
   Compiling which v4.4.0
   Compiling chromiumoxide_cdp v0.3.5
   Compiling async-tungstenite v0.17.2
   Compiling strsim v0.10.0
   Compiling termcolor v1.2.0
   Compiling lazy_static v1.4.0
   Compiling bitflags v1.3.2
   Compiling textwrap v0.16.0
   Compiling futures-timer v3.0.2
   Compiling clap v3.2.23
   Compiling colored v2.0.0
   Compiling chromiumoxide v0.3.5
   Compiling ppfuzz v1.0.1
error[E0432]: unresolved imports `clap::crate_authors`, `clap::crate_description`, `clap::crate_name`, `clap::crate_version`
 --> /Users/aviralsrivastava/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:5:3
  |
5 |         crate_authors,
  |         ^^^^^^^^^^^^^ no `crate_authors` in the root
6 |         crate_description,
  |         ^^^^^^^^^^^^^^^^^ no `crate_description` in the root
7 |         crate_name,
  |         ^^^^^^^^^^ no `crate_name` in the root
8 |         crate_version,
  |         ^^^^^^^^^^^^^ no `crate_version` in the root

error: cannot determine resolution for the macro `crate_name`
  --> /Users/aviralsrivastava/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:30:4
   |
30 |             crate_name!(), "FILE", "[OPTIONS]"
   |             ^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_authors`
  --> /Users/aviralsrivastava/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:33:12
   |
33 |             .author(crate_authors!())
   |                     ^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_description`
  --> /Users/aviralsrivastava/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:34:11
   |
34 |             .about(crate_description!())
   |                    ^^^^^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_name`
  --> /Users/aviralsrivastava/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:35:10
   |
35 |             .name(crate_name!())
   |                   ^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_version`
  --> /Users/aviralsrivastava/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:36:13
   |
36 |             .version(crate_version!())
   |                      ^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error[E0308]: mismatched types
  --> /Users/aviralsrivastava/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:32:23
   |
32 |         let app = App::from(yaml)
   |                   --------- ^^^^ expected struct `App`, found `&yaml_rust::yaml::Yaml`
   |                   |
   |                   arguments to this function are incorrect
   |
note: associated function defined here
  --> /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/convert/mod.rs:548:8

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `ppfuzz` due to 7 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `ppfuzz v1.0.1`, intermediate artifacts can be found at `/tmp/cargo-installhR6czQ`

Just like this the other 2 tools are also not being installed and I can't use the reconFTW without them

**Comment by six2dez** [comment]
Maybe the installer didn't detected your right OS and processor, could you check what's the output of the following commands in your OS?

```bash
echo $OSTYPE
bash --version
cat /proc/cpuinfo
cat /usr/bin/arch
```

**Comment by p3stR** [comment]
Hello,
I was able to install all the tools on a Mac M1. I had some issues in some of them but unfortunately I don't have any logs kept and cannot remember if I had any specific issue with ppfuzz. I do remember that the PATH was missing and I had to add it manually in order the reconfwt be able to recognise that is installed.

In my case the reconftw is not picking any target and after checking the list it just stops. Can you please assist on that?
Please let me know if I should open a new issue.

`bash -x /opt/GITs/reconftw/reconftw.sh -d asdasdasd
...
 Good! All installed!

+ printf '\033[1;34m Tools check finished\n'
 Tools check finished
+ printf '\033[1;32m#######################################################################\n\033[0m'
#######################################################################
+ exit 1`

**Comment by six2dez** [comment]
Hey, sorry for the late reply, this happens because MacOs is not handling properly the getopt on reconftw, for this issue, I added the following lines on reconftw some time ago, could you check if you have `gnu-getopt/bin` on your path?:

![image](https://github.com/six2dez/reconftw/assets/24670991/7c50d952-6eab-4743-b731-509a05713863)

**Comment by six2dez** [comment]
Closing this, following the issue here https://github.com/six2dez/reconftw/issues/673
