### ISSUE TITLE
Uninstalling reconftw

### ISSUE THREAD

**Issue by rmRizki** [six2dez/reconftw#659]
Hi, it would be helpful if you have a script to also uninstall reconftw

**Comment by six2dez** [comment]
Reconftw installs more than 50 tools on `$HOME/Tools` by default and the default `GOPATH`, as many of us use the installer script to maintain the tools updated and uninstalling them would cause a major disruption on some systems I will not provide an uninstaller script. If you want to keep your OS clean, you can also try the Docker version
