### ISSUE TITLE
Active Subdomain Enumeration doesn't work after the last update

### ISSUE THREAD

**Issue by Hacktus** [six2dez/reconftw#660]
**To Reproduce**
Run Active Subdomain Enumeration

the code will terminate with an output of :

sed: no input files

**Comment by kleozzy** [comment]
Yes i can confirm it broke

**Comment by six2dez** [comment]
Fixed ! https://github.com/six2dez/reconftw/commit/b3939791f8cb6469ac73293a4537c0400c8a173c
