### ISSUE TITLE
stuck at GitHub Recon

### ISSUE THREAD

**Issue by parvbarot** [six2dez/reconftw#664]
I'm experiencing an issue with the latest version of Reconftw Docker where it gets stuck at GitHub Recon and doesn't proceed. Previously, it was working fine 10 days ago. Some tools such as BBRF, EmailFinder, DNSValidator, and WAFW00F are not installed.

**Comment by six2dez** [comment]
Hi, Github Recon module didn't receive any changes lately, I would rebuild the docker container as it didn't has any changes in the latests updates
