### ISSUE TITLE
Subdomain Enumertion Is not happening and some tools throws errors as Module Not Found

### ISSUE THREAD

**Issue by hawkshk** [six2dez/reconftw#666]
**Describe the bug**
I installed by following all the steps on installation guide and when I run the subdomain enumeration tools seperately .. they are running fine and giving output , but when I run the ./reconftw script there is only 0 or 1 only subdomains found as shown below 
![image](https://user-images.githubusercontent.com/70468506/221856424-b5e0f6fb-9e6b-48f2-a897-68893b532ddb.png)

but after the script executes , I cannot able to run the tools individually also ... and I used ReconFTW before but and it worked fine , but after I update to the new version 2.5.2 I face these errors! . Is it due to the new version or anything wrong with mine ? 

Im using kali linux 22.4 in virtual box , can somebody help me with this

**Comment by hawkshk** [comment]
Hi , Thankyou for responding!!
* ReconFTW main ( I downloaded using git clone )
*  ./ReconFTW -d REDACTED.COM -r -q 5
*   I Tried running the installer more that 5 times from yesterday 
* Yes I have Network Connectivity 

Thankyou

**Comment by hawkshk** [comment]
Hi There , 
I think I have found the potential problem here . The resolvers.txt and resolvers_trusted.txt are empty even after running the ./install and ./reconftw scripts . I also tried to manually wget then from trickest but after running ./reconftw they again become empty as shown below. What can I do to resolve this issue
![image](https://user-images.githubusercontent.com/70468506/222066310-f9065642-1091-4cb2-90c3-8a76db1ae4e4.png)

**Comment by six2dez** [comment]
Hey! Thanks for the info provided, reconftw runs the following code in order to update the resolvers list:

https://github.com/six2dez/reconftw/blob/c8dfd2e7b944bb9806af76be7b5c7158d3f7292a/reconftw.sh#L2121-L2126

I recommend you to check if:
1. These commands run well if you run it manually (the wget commands).
2. Check your `resolvers_url` and `resolvers_trusted_url` in your reconftw.cfg, (lines 12 and 13).
3. There is also a `update_resolvers` flag on reconftw.cfg that you can set to `false` in order to skip the resolvers update within reconftw.

Check these steps and tell me the results, thanks!

**Comment by hawkshk** [comment]
Hi , 
Thankyou , I looked into it .... now it seem running perfectly (just the resolvers part) . but i also get this following error which I mentioned during my first message above.. It throws errors during "Permutations by regex analysis" part
![image](https://user-images.githubusercontent.com/70468506/222087604-cedd199c-9899-43a7-b5db-755d9c43e308.png)
I tried installing. It using pip, apt and also pipx .. but i cannot install it
![image](https://user-images.githubusercontent.com/70468506/222087825-9c042b53-4379-4845-9acf-2933fa4a6764.png)

**Comment by six2dez** [comment]
Hi! I think the right package for editdistance via apt is `python3-edlib`, however I can install it via `pip3 install editdistance`. It should be installed via the installer :(
