### ISSUE TITLE
Any updates on reconFTw 3.0 :)

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#669]
Hey Devs, wondering if we have any updates on reconFTW 3.0 and if we can contribute somehow. Also if you can share more details how you plan to implement it and make it more moduler like a flow diagram or mindmap thing.

Thanks and Regards,

**Comment by six2dez** [comment]
Hey! reconftw v3.0 will be released when the web ui (already in dev branch) and the modular branch are finished. If you want to help in the development of this you can check here https://github.com/six2dez/reconftw/blob/modular/collab.md or throwing me a DM on any social media (Twitter, Telegram, Discord...)

**Comment by jakre1234** [comment]
Sounds great, I have gone through the attached link and I guess I got the core idea and your point of view, I will try to implement these modular scripts and update you :)
