### ISSUE TITLE
Why are crawled/archived/fuzzed urls being added to bbrf urls ?

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#672]
Hello Devs, not sure why all the urls are being added to the brrf urls, why not we only limit the urls to httpx results so that record remains clean to test for certain vulnerability type next time?
Meanwhile, I have came with a solution to add a tag ```httpx:true``` to the urls added via httpx results so that I can run nuclei on seed urls only next time using something like ```bbrf urls where httpx is true|nuclei``` .

Thanks and Regards,

**Comment by six2dez** [comment]
Bbrf is removed on dev branch and will be removed on main branch on the next release, so closing this issue

**Comment by jakre1234** [comment]
Damn...why is bbrf being removed from main branch :fearful: , any particular reason for this @six2dez ? I just started using bbrf and it is super helpful to accumulate recon data.

Thanks and Regards,

**Comment by six2dez** [comment]
Hi @jakre1234 sorry for the inconveniences this could cause. I want to prioritize the usage of the web interface as well as a way to import projects in to the web UI, I know bbrf is super useful, but it's not possible to import all the data, the development of this project is going super slow and contains some bugs that remains there for a long time, so I took this decision as I thought nobody was using it. Also, I asked on the Telegram and Discord reconftw groups and nobody answered.

Probably is better to write an external reconftw2bbrf importer that you can run after each scan. I can help with that if you're interested on do it.
