### ISSUE TITLE
Apple M1 - unable to parse arguments 

### ISSUE THREAD

**Issue by Desiprox** [six2dez/reconftw#673]
Hello 👋

All the tool requirement has been installed successfully, but I have a problem the bash script is unable to parse the argument
both domain and opt_mode variables are empty which prevents the tool to run properly.
`
PROGARGS=$(getopt -o 'd:m:l:x:i:o:f:q:c:rspanwvh::' --long 'domain:,list:,recon,subdomains,passive,all,web,osint,deep,help,vps' -n 'reconFTW' -- "$@")
eval set -- "$PROGARGS"
unset PROGARGS
`

Thanks

**Comment by six2dez** [comment]
I'm merging another issue with this one, so copying the same answer here:

> Hey, sorry for the late reply, this happens because MacOs is not handling properly the getopt on reconftw, for this issue, I added the following lines on reconftw some time ago, could you check if you have gnu-getopt/bin on your path?:
> 
> ![image](https://github.com/six2dez/reconftw/assets/24670991/0eb4b0d2-a169-4ea1-b483-40024c764ca6)

**Comment by six2dez** [comment]
Will remove MacOS official support in next release, so closing this issue
