### ISSUE TITLE
. /install gives the error go: cannot find GOROOT directory: /usr/local/go

### ISSUE THREAD

**Issue by JacHeiuang** [six2dez/reconftw#676]
**Describe the bug**

**To Reproduce**
Hi, I'm having a bit of trouble installing reconftw, it says it can't find the /usr/local/go path because my go path is in /usr/bin/go, I tried to move go to the /usr/ I tried to move go to /usr/local and change the GOROOT environment variable, but it failed, it still says go: cannot find GOROOT directory: /usr/local/go

I also tried to change the GOROOT path in the reconftw.cfg file, but maybe I made a mistake and the installation didn't work, I hope you can help me solve this problem and provide a working statement, I would be grateful!

**Expected behavior**
I want to be able to install the dependencies properly and without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/107828648/227187864-45bf2aaf-2b09-43cf-8b23-15d73fe95ed2.png)
![image](https://user-images.githubusercontent.com/107828648/227192028-1ecb9187-fdd8-4586-bee0-aebb1e552cf0.png)
![image](https://user-images.githubusercontent.com/107828648/227188083-b8571a54-935d-4cf1-ba14-810dc0a9334b.png)
![image](https://user-images.githubusercontent.com/107828648/227188214-461baa8c-0fb5-4ffe-a914-bde2269656ba.png)

**Desktop (please complete the following information):**
- Architecture: [AMD64]
 - OS: Kali
 - Version 2022.4
golang1.20.2

**Comment by TerickJojo** [comment]
same.

install.sh append the Go ENV into .zshrc which already contain the Go ENV and throw the error(go: cannot find GOROOT directory: /usr/local/go) while installing.

Architecture: ARM M1
OS:Mac
Version: Golang 1.20.2

<img width="716" alt="image" src="https://user-images.githubusercontent.com/24235319/227465598-4a8ce835-dccf-4e31-87c3-b0b402102248.png">
<img width="654" alt="image" src="https://user-images.githubusercontent.com/24235319/227466328-5a23d88f-4592-430c-b6e1-db6f72c67580.png">

**Comment by six2dez** [comment]
To detect if golang is installed the next validation is performed `type go | grep -o 'go is'` if it's true the installer doesn't perform the Golang installation, otherwise it installs it. If you don't want installer performs Golang installation, you can change the following line on reconftw.cfg:


https://github.com/six2dez/reconftw/blob/0647612b58c0ab780f872e937ba419a7aa8b10c8/reconftw.cfg#L15
