### ISSUE TITLE
Docker image cannot find any tools and some other errors

### ISSUE THREAD

**Issue by sausagenoods** [six2dez/reconftw#692]
**Describe the bug**
There are no tools found during "Checking installed tools" phase.

**To Reproduce**
1. `docker pull six2dez/reconftw:main`
2. `docker run -it --rm -v "${PWD}/out/":'/reconftw/Recon/' six2dez/reconftw:main -d kernal.eu -r`
3. Observe that there are no installed tools. These errors are printed upon exit:
```
./reconftw.sh: line 219: anew: command not found
./reconftw.sh: line 223: cd: /root/Tools/Infoga: No such file or directory
Failed to cd directory in emails @ line 223
```

**Expected behavior**
Installed tools to be found and ran without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/84454107/235652002-efac5aa8-bc32-4a5f-be3f-e2307184b5be.png)

**Desktop (please complete the following information):**
 - Host Architecture: x86_64
 - Host OS: Ubuntu 22.04.2 LTS
 - Docker version: Docker Engine - Community 23.0.3

**Additional context**
Old image (main-v2.5.2-20-gc8dfd2e) still works. It would be immensely helpful to have proper tags on images such as `:2.6` instead of only `:main` and `:dev`. I was lucky I had the old image locally and was able to use it.

**Comment by sam5epi0l** [comment]
I think this issue occurred due new interactive prompt in `install.sh` script.
I've tried different ways to go with one option from the prompt in Dockerfile;

- `sh -c 'echo 1 | sudo apt install zsh'` (working) (Created Pull Request using this method)
- `(echo 1 && cat) | ./install.sh` (working)
- `echo 1 | ./install.sh` (**not** working)

After using first method for specifying reconFTW installation. The docker image is working fine as previous versions.

**Comment by six2dez** [comment]
Hey! Sorry about that, the automatic generation and push to DockerHub was completely broken, by now it should works fine!
