### ISSUE TITLE
Feature Request to support ShadowClone 

### ISSUE THREAD

**Issue by abdilahrf** [six2dez/reconftw#696]
**Is your feature request related to a problem? Please describe.**
I heard ShadowClone have better in speed from axiom 

**Describe the solution you'd like**
Support https://github.com/fyoorer/ShadowClone

https://twitter.com/infosec_au/status/1652525328223600640

**Comment by six2dez** [comment]
ShadowClone only provides 15 minutes of free scan, most of the tasks not meet that requirement
