### ISSUE TITLE
Add support for Docker Compose

### ISSUE THREAD

**Issue by AnonymousWP** [six2dez/reconftw#697]
**Is your feature request related to a problem? Please describe.**

There's no Docker Compose file, and because of that, it's not possible to get the web interface up and running.

**Describe the solution you'd like**

Make a Docker Compose file that builds the image and runs the webserver.

**Comment by AnonymousWP** [comment]
> https://github.com/six2dez/reconftw/blob/main/Docker/Dockerfile
> 
> ??

I said Docker Compose, not a Dockerfile. Besides, when following https://github.com/six2dez/reconftw#b-docker-image--3-options, the web interface obviously doesn't work, so I'm trying to do that now on my own fork.

**Comment by six2dez** [comment]
There is a recent pull request merged that may solve that issue. Anyway, if it doesn't work for you, when you find a fix please make a pull request. Thanks!

**Comment by AnonymousWP** [comment]
> There is a recent pull request merged that may solve that issue. Anyway, if it doesn't work for you, when you find a fix please make a pull request. Thanks!

Just wanted to mention that the pull request did not fix it. After all, the `docker run` is not a continuous process, unlike when using a Docker Compose file.
