### ISSUE TITLE
Enuqiry regarding the new Web based interface

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#703]
Hey Devs,
I was interested to know if the new web interface is just for the scanned results or we can actually start scans from the web interface itself?

Also I would like to request a feature such as subdomain monitoring or scheduled scans for users running it on VPS, so that the scans for any programs can scheduled just like crontab

Thanks and Regards,

**Comment by six2dez** [comment]
Hi, the idea behind the web is to bring a way to visualize the data, but also you can run scans from it. It also has a pending feature to schedule scans from it, meanwhile you can just use your crontab :)
