### ISSUE TITLE
Install error sh: 1: ./install.sh: not found

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#704]
Hello Devs,
I am trying to install the latest version of reconFTW with webserver. After all the installation I get this error in the last,
```
 Running: Performing last configurations 

sh: 1: ./install.sh: not found
```
![reconFTWerror](https://github.com/six2dez/reconftw/assets/89703702/222dd0bc-e741-4a3d-b1e1-fc6e7eea9c9b)

This seems to be raising from the line no 663 in install.sh
```
eval $SUDO cp "$HOME"/go/bin/* /usr/local/bin/ $DEBUG_STD

if [ "$web" = true ]; then
    sh -c 'echo 3 | ./install.sh'
fi
```

**Comment by six2dez** [comment]
Hi! thanks for rising this issue, fixed and pushed to main branch! https://github.com/six2dez/reconftw/pull/705/commits/e70faa38d09cf6fc287aa987f0a2c570d5df5e5f
