### ISSUE TITLE
Reconftw hangs at nuclei scan.

### ISSUE THREAD

**Issue by plavanabond** [six2dez/reconftw#711]
**Nuclei scans hanging a lot**
Nuclei scan running through reconftw hangs a lot. Is it because of thread settings. Mostly it hangs all the time. I have VPS with 4 GB Ram and 4 core CPU.

**Comment by six2dez** [comment]
I never saw this kind of behavior, keep in mind how large is your target. From reconftw there is no specific thread settings for nuclei, but you can specify it by yourself at https://github.com/six2dez/reconftw/blob/6fb0ae52f105fdc331f832e8ccba46671bc52c1a/reconftw.cfg#L100
