### ISSUE TITLE
SecretFinder open new browser tab for every finding

### ISSUE THREAD

**Issue by bileltechno** [six2dez/reconftw#72]
**Describe the bug**
SecretFinder open new browser tab for every finding

**To Reproduce**

**Expected behavior**
1. SecretFinder create output.html
2. Open it in new browser tab
3. delete output.html
4. Go to 1

**Desktop (please complete the following information):**
- Linux 
- Brave browser

**Comment by ccsdscs** [comment]
S

**Comment by bileltechno** [comment]
@six2dez : I think this was resolved by :
https://github.com/six2dez/reconftw/commit/c907d9f428b5977bbd433ce96dce8393edcf82e6

and need to be closed

**Comment by six2dez** [comment]
Yup, closed with c907d9f428b5977bbd433ce96dce8393edcf82e6
