### ISSUE TITLE
result

### ISSUE THREAD

**Issue by Sunny81599-cybe** [six2dez/reconftw#720]
Running : Nuclei info                                                       

[ERR] failed to load provider keys got yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `/root/....` into sources.Provider

 Running : Nuclei low                                                        

[ERR] failed to load provider keys got yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `/root/....` into sources.Provider

 Running : Nuclei medium                                                     

[ERR] failed to load provider keys got yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `/root/....` into sources.Provider

 Running : Nuclei high                                                       

[ERR] failed to load provider keys got yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `/root/....` into sources.Provider

 Running : Nuclei critical                                                   

[ERR] failed to load provider keys got yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `/root/....` into sources.Provider

**Comment by AnonymousWP** [comment]
It's fixed now in https://github.com/projectdiscovery/nuclei/releases/tag/v2.9.6.
