### ISSUE TITLE
Idea: Replace UnaPibaGeek/ctfr with cemulus/crt

### ISSUE THREAD

**Issue by Azathothas** [six2dez/reconftw#721]
1. https://github.com/UnaPibaGeek/ctfr/ hasn't been updated in ~ 3 years and rarely works:
> ![image](https://github.com/six2dez/reconftw/assets/58171889/cad33870-f7d0-468c-b167-381c7e0e679a)
> See : https://github.com/UnaPibaGeek/ctfr/issues/38
2. https://github.com/cemulus/crt is a Better, Faster & Modern alternative written in go.

An example implementation: 
```bash
crt -s -json -l 99999 github.com | jq -r '.[].subdomain' | sed -e "s/^\\*\\.//" | sort -u 
```
![image](https://github.com/six2dez/reconftw/assets/58171889/3ba521c3-9b26-43d0-a456-9194bfa7e017)

Benchmarks:
![image](https://github.com/six2dez/reconftw/assets/58171889/f757e373-d71a-4b46-931d-d8724f3e29c6)

Results:
![image](https://github.com/six2dez/reconftw/assets/58171889/01a83c96-6fcd-4a6f-9656-91cdd9276a93)

**Comment by six2dez** [comment]
Done! Thanks for the suggestion!! https://github.com/six2dez/reconftw/commit/145164c52ba3a0c68f2e1a7d4f862aa60569a3c2
