### ISSUE TITLE
Reconftw and Axiom Integration Fails with Nuclei

### ISSUE THREAD

**Issue by parvbarot** [six2dez/reconftw#722]
**Describe the bug**
Whenever I use Reconftw with Axiom, I couldn't find any findings with Nuclei

**Comment by six2dez** [comment]
Hi, when using Axiom is not possible to pipe nuclei results to reconftw standard output, but the file with the findings at `reconftw/Recon/yourdomain[.]com/nuclei_output` should be there, check it. Also I will add a clear message on reconftw's output for this :)

**Comment by parvbarot** [comment]
Thank you for your message. I have verified the contents of the reconftw/Recon/mydomain/nuclei_output folder, and unfortunately, I found that it is empty. It appears that the expected data from Axiom's nuclei results are not present in that location

**Comment by six2dez** [comment]
Can you check the log file under `reconftw/Recon/mydomain/.log/` in order to check if something is printing an error?

**Comment by davidfegyver** [comment]
Hey, currently new reconftw images are failing because nucleis new requirement of go 20. you can install a correct version manually with axiom-exec. ` axiom-exec "go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@v2.9.4"`

I hope this solves the issue. 

David

**Comment by parvbarot** [comment]
└─$ cat 2023-06-05_05:38:42.txt
Start 2023-06-05 05:38:42
[ 2023-06-05 05:38:42 ] Start function : domain_info
[ 2023-06-05 05:38:43 ] End function : domain_info
[ 2023-06-05 05:38:43 ] Start function : emails
./reconftw.sh: line 220: emailfinder: command not found
[ 2023-06-05 05:44:45 ] End function : emails
[ 2023-06-05 05:46:05 ] End function : google_dorks
[ 2023-06-05 05:46:05 ] Start function : github_dorks
[ 2023-06-05 05:46:05 ] End function : github_dorks
[ 2023-06-05 05:46:05 ] Start function : github_repos
[ 2023-06-05 05:46:05 ] End function : github_repos
[ 2023-06-05 05:46:05 ] Start function : metadata
mv: cannot stat 'osint/assetdynamic.in/*.txt': No such file or directory
[ 2023-06-05 05:46:05 ] End function : metadata
[ 2023-06-05 05:46:05 ] Start function : zonetransfer
[ 2023-06-05 05:46:06 ] End function : zonetransfer
[ 2023-06-05 05:46:06 ] Start function : favicon
[ 2023-06-05 05:46:06 ] End function : favicon
[ 2023-06-05 05:46:06 ] Start function : axiom_lauch
[ 2023-06-05 05:52:57 ] End function :
[ 2023-06-05 05:52:59 ] Start subfunction : sub_passive
[ 2023-06-05 05:54:35 ] End subfunction : 0 new subs (passive)
[ 2023-06-05 05:54:35 ] Start subfunction : sub_crt
[ 2023-06-05 05:55:09 ] End subfunction : 2 new subs (cert transparency)
[ 2023-06-05 05:55:09 ] Start subfunction : sub_active
[ 2023-06-05 05:56:33 ] End subfunction : 2 subs DNS resolved from passive
[ 2023-06-05 05:56:33 ] Start subfunction : sub_noerror
[ 2023-06-05 06:10:01 ] End subfunction : 49 new subs (DNS noerror)
[ 2023-06-05 06:10:01 ] Start subfunction : sub_brute
[ 2023-06-05 06:12:15 ] End subfunction : 0 new subs (bruteforce)
[ 2023-06-05 06:12:15 ] Start subfunction : sub_permut
[ 2023-06-05 06:14:32 ] End subfunction : 0 new subs (permutations)
[ 2023-06-05 06:14:32 ] Start subfunction : sub_regex_permut
[ 2023-06-05 06:15:05 ] End subfunction : 0 new subs (permutations)
[ 2023-06-05 06:15:05 ] Start subfunction : sub_dns
cat: .tmp/subdomains_dns_resolved.txt: No such file or directory
[ 2023-06-05 06:16:34 ] End subfunction : 0 new subs (dns resolution)
[ 2023-06-05 06:16:34 ] Start subfunction : sub_scraping
cat: .tmp/web_full_info3.txt: No such file or directory
[ 2023-06-05 06:20:12 ] End subfunction : 0 new subs (code scraping)
[ 2023-06-05 06:20:12 ] Start subfunction : sub_analytics
cat: .tmp/analytics_subs_resolved.txt: No such file or directory
[ 2023-06-05 06:20:45 ] End subfunction : 0 new subs (analytics relationship)
[ 2023-06-05 06:20:45 ] Start subfunction : webprobe_simple
[ 2023-06-05 06:21:35 ] End subfunction : 4 new websites resolved
[ 2023-06-05 06:21:35 ] Start function : webprobe_full
cat: .tmp/probed_uncommon_ports_tmp.txt: No such file or directory
[ 2023-06-05 06:22:26 ] End function : webprobe_full
[ 2023-06-05 06:22:26 ] Start function : s3buckets
cat: .tmp/s3buckets_tmp2.txt: No such file or directory
cat: .tmp/output_cloud.txt: No such file or directory
[ 2023-06-05 06:23:16 ] End function : s3buckets
[ 2023-06-05 06:23:16 ] Start function : screenshot
[ 2023-06-05 06:24:12 ] End function : screenshot
[ 2023-06-05 06:24:12 ] Start function : cdnprovider
[ 2023-06-05 06:24:13 ] End function : cdnprovider
[ 2023-06-05 06:24:13 ] Start function : portscan
[ 2023-06-05 06:24:13 ] End function : portscan
[ 2023-06-05 06:24:13 ] Start function : waf_checks
[ 2023-06-05 06:25:03 ] End function : waf_checks
[ **2023-06-05 06:25:03 ] Start function : nuclei_check
[ 2023-06-05 06:29:08 ] End function : nuclei_check**
[ 2023-06-05 06:29:08 ] Start function : fuzz
[ 2023-06-05 06:32:24 ] End function : fuzz
[ 2023-06-05 06:32:24 ] Start function : urlchecks
[ 2023-06-05 06:34:28 ] End function : urlchecks
[ 2023-06-05 06:34:28 ] Start function : jschecks
[ 2023-06-05 06:36:08 ] End function : jschecks
[ 2023-06-05 06:36:31 ] Start function : cms_scanner
TIMEOUT cmseek.py - investigate manually for /home/kali/reconftw/Recon/assetdynamic.in
[ 2023-06-05 06:36:31 ] End function : cms_scanner
[ 2023-06-05 06:36:31 ] Start function : url_gf
[ 2023-06-05 06:36:31 ] End function : url_gf
[ 2023-06-05 06:36:31 ] Start function : wordlist_gen
[ 2023-06-05 06:36:31 ] End function : wordlist_gen
[ 2023-06-05 06:36:31 ] Start function : wordlist_gen_roboxtractor
[ 2023-06-05 06:37:04 ] End function : wordlist_gen_roboxtractor
[ 2023-06-05 06:37:04 ] Start function : password_dict
[ 2023-06-05 06:37:04 ] End function : password_dict
[ 2023-06-05 06:37:04 ] Start function : url_ext
[ 2023-06-05 06:37:05 ] End function : url_ext

I have verified the results both with and without Axiom and without axiom I can find nuclei result but without I can't

**Comment by six2dez** [comment]
> Hey, currently new reconftw images are failing because nucleis new requirement of go 20. you can install a correct version manually with axiom-exec. ` axiom-exec "go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@v2.9.4"`
> 
> I hope this solves the issue.
> 
> David

Hey! Thanks for pointing this out! I'll update golang on reconftw axiom image asap!

**Comment by six2dez** [comment]
Upgraded axiom image, waiting for approval https://github.com/pry0cc/axiom/pull/728
