### ISSUE TITLE
Help needed with using the ``-c`` flag

### ISSUE THREAD

**Issue by 0xPugazh** [six2dez/reconftw#724]
Hello, @six2dez.
How to use the ``-c Launches particular function against target``.
Could you perhaps offer a sample command that executes the required function against the targets?
for example i want to run only nuclei scan against urls with ``-v`` axiom in reconftw. how to use the ``-c`` flag.

**Comment by six2dez** [comment]
The `-c` flag is an undocumented function that will be replaced in following releases. If you only want to run nuclei scans against a list of urls why you don't just run `axiom-scan urls.txt -m nuclei`?

In case you still want to try the `-c` flag, it is used to run specific reconftw modules, for example `./reconftw.sh -d yourdomain.com -c nuclei_checks` and it will call the nuclei function
