### ISSUE TITLE
The list feature in the web interface doesn't appear to work

### ISSUE THREAD

**Issue by Viss** [six2dez/reconftw#728]
Fresh install (two days old) out of git.
Running a single domain works as expected, however using the 'list' part of the web interface to start a scan causes several issues:

1) if you put more than one domain, the modal for the input goes away as though it's started a job but nothing happens and no scans are performed
2) if you put no domains in, you get very verbose error messages (probably not great for publicly accessible instances)
3) if you put a single domain into the list feature, it seems to work

I spent some time trying to figure out if the list needed to be in a specific format, like all domains on new lines, or separated by spaces, or commas, but nothing I tried worked.

**Comment by lur1el** [comment]
Hello @Viss, how are you?!! 

Thank you very much for getting in touch! This feature is still in development. As we know that users are in need of it, we will change our priority and focus on the add list functionality.

If all goes well, we will perform the upload to /dev/ this week.

**Comment by Viss** [comment]
Hi!

that's awesome news! ill keep an eye out!

**Comment by six2dez** [comment]
Web server will not be maintained nor deployed with reconftw anymore
