### ISSUE TITLE
Fix gitlab-subdomains

### ISSUE THREAD

**Issue by mastercho** [six2dez/reconftw#740]
**Describe the bug**
Checking logs of scan i see issue with gitlab-subdomains

```
[ 2023-06-29 05:41:52 ] Start subfunction : sub_passive 
flag provided but not defined: -o
Usage of gitlab-subdomains:
  -d string
    	domain you are looking for (required)
  -debug
    	debug mode
  -e	extended mode, also look for <dummy>example.com
  -t string
    	gitlab token (required), can be:
    	  • a single token
    	  • a list of tokens separated by comma
    	  • a file (.tokens) containing 1 token per line
    	if the options is not provided, the environment variable GITLAB_TOKEN is readed, it can be:
    	  • a single token
    	  • a list of tokens separated by comma
```

seems that tool is updated and doesn't  support -o flag anymore, you should update the script
**To Reproduce**
./reckonftw -d site.com -a

**Expected behavior**
To run without issue

**Desktop (please complete the following information):**
- Architecture: x86
 - OS: Ubuntu
 - Version 20.04

**Comment by six2dez** [comment]
Fixed! https://github.com/six2dez/reconftw/pull/743/commits/5e17af52774c413bbebdde6e2b0e93b802c74456
