### ISSUE TITLE
Issues with Reconftw on OS X 

### ISSUE THREAD

**Issue by hackingmess** [six2dez/reconftw#744]
**Describe the bug**
Perform the installation according to documentation for OS X Ventura 13.4.1, install all the apps, try to run any command, 

**Expected behavior**
Help to fix this loop behavior on my Mac 

**Screenshots**
![Captura de Tela 2023-07-12 às 22 44 54](https://github.com/six2dez/reconftw/assets/63216405/752cf966-7601-4b3d-895d-c7d025a0729b)

**Desktop (please complete the following information):**
<img width="510" alt="Captura de Tela 2023-07-12 às 22 51 12" src="https://github.com/six2dez/reconftw/assets/63216405/786ac1aa-45df-43ba-b122-8cce19d8672e">
 - OS: OSX Ventura 13.4.1,

**Additional context**
It goes to the same start menu when running any command eg  ./reconftw.sh -d owasp.org  -r

**Comment by hackingmess** [comment]
I reinstall and update to the latest version, still same behavior :/

**Comment by six2dez** [comment]
MacOS is not supported anymore

**Comment by hackingmess** [comment]
Thanks, Understood I will give it a try on Kali Linux
