### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jakre1234** [six2dez/reconftw#747]
Lots of tools not installed on latest distros running python 3.11
```
Checking installed tools 

 [*] dnsvalidator               [NO]
 [*] interlace                  [NO]
 [*] emailfinder                [NO]
 [*] ripgen                     [NO]
 [*] ghauri                     [NO]
 [*] subgpt                     [NO]
 [*] trufflehog                 [NO]

 Try running the installer script again ./install.sh
 If it fails for any reason try to install manually the tools missed         
 Finally remember to set the $tools variable at the start of this script     
 If nothing works and the world is gonna end you can always ping me :D       

 Tools check finished
```

**Comment by jakre1234** [comment]
With the latest version of pip, it won't allow to install tools maintained by an external repo, this needs to have pipx or you need to use the flag --break0system-packages

**Comment by jakre1234** [comment]
Hey @six2dez are you going to work on this? I am trying to fix it on my end will share if I get it to work with latest debian 12 and python 3.11

**Comment by six2dez** [comment]
Yes please, I can't work on this currently, if you have made any progress on the fix please feel free to send PR

**Comment by Harsh-Navgale** [comment]
@jakre1234 can you tell me how to install the full tool

**Comment by six2dez** [comment]
Upgrade python to latest version
