### ISSUE TITLE
How to run the vulnerability scans within a defined scope?

### ISSUE THREAD

**Issue by rrehlert** [six2dez/reconftw#748]
Heyo guys,

I want to find a way to run the web and vulnerability checks within a list of given subdomains, without the subdomain enumeration, the command in the examples (  ./reconftw.sh -d example.com -l targets.txt -w ) just executes the web checks.

**Comment by six2dez** [comment]
I think it should work like that. But the `-w` flag is supposed to process websites, not subdomains :/ Maybe your use case is not covered yet
