### ISSUE TITLE
NMAP_WEBPROBE field looks like never used

### ISSUE THREAD

**Issue by foo233** [six2dez/reconftw#750]
**Describe the bug**
It looks like `NMAP_WEBPROBE` field never used.

**To Reproduce**
`NMAP_WEBPROBE` declared in
https://github.com/six2dez/reconftw/blob/4d5718fe78e61d2e3d6e7629bd1554ce60ba64b7/reconftw.cfg#L88
but in the `webprobe_full` function, we just use httpx to do the job
https://github.com/six2dez/reconftw/blob/4d5718fe78e61d2e3d6e7629bd1554ce60ba64b7/reconftw.sh#L943-L956

So any idea to implement that?

**Comment by six2dez** [comment]
This is part of some legacy code that is not working anymore, will remove that line on next release
