### ISSUE TITLE
Web Server Not starting

### ISSUE THREAD

**Issue by BlasterX24** [six2dez/reconftw#751]
**Describe the bug**
Hostname issue / Server  IP address Not found

**To Reproduce**
1. reconftw.sh --web-server start 

But it doesnot start instead it gives me error such as :- 

```
hostname: invalid option -- 'I'
Try 'hostname --help' or 'hostname --usage' for more information.

Server IP address not found.
![recon](https://github.com/six2dez/reconftw/assets/41836236/4d330a7e-3ccb-4abb-b5cc-f253286083f8)


Check if the server has internet connection.
```

I have working Internet Connection.
I have tried running script 3 times and all tools are installed perfectly!

![recon](https://github.com/six2dez/reconftw/assets/41836236/65a72c01-56dc-4a14-ac2b-ec4955f2bb97)

OS : Garuda Linux Based on Arch!

**Comment by A-khateeb** [comment]
Same on my end

**Comment by six2dez** [comment]
Hey guys I guess it should work by now, https://github.com/six2dez/reconftw/pull/754/commits/b8f05b3ad1af5868e230d4de669e730b6f1308bc

**Comment by cryptovert** [comment]
its happening again after last update. On both VPS's I've tried it on, fresh install. Thanks for sharing the line, I'm going to revise it.
