### ISSUE TITLE
Updating reconFTW will update and overwrite config files of other 3rd party tools.

### ISSUE THREAD

**Issue by Hasan-Z** [six2dez/reconftw#759]
Whenever updating reconFTW, when there's an update to 3rd party tools like amass, theHarvester, etc... it will override config files of those 3rd party apps including any API_KEYs that were entered.

If the update process include any mechanism for a backup or update 3rd party apps without overwriting their respective config files it will be great.

**Comment by six2dez** [comment]
Currently, if amass or notify config file exists, it will skip getting the latest version, this should be enough but feel free to reopen this bug if it continues rewriting the config files
![image](https://github.com/six2dez/reconftw/assets/24670991/c65a42d9-e9fe-4dc0-b39d-8f5742b9401c)
