### ISSUE TITLE
ASN/CIDR/Name Target allowed

### ISSUE THREAD

**Issue by six2dez** [six2dez/reconftw#76]
Allows ASN/CIDR/Name as target.

Tools suggestion:

[metabigor](https://github.com/j3ssie/metabigor)
[asnlookup](https://github.com/yassineaboukir/Asnlookup)
[asnip](https://github.com/harleo/asnip)
[mapcidr](https://github.com/projectdiscovery/mapcidr)
[3klector](https://github.com/eslam3kl/3klector)
[HostHunter](https://github.com/SpiderLabs/HostHunter)

**Comment by bileltechno** [comment]
shifted to v0.4.0 milestone

**Comment by six2dez** [comment]
This is better to make a manual research than automate
