### ISSUE TITLE
Incorrect Path for $tools/urless/urless.py

### ISSUE THREAD

**Issue by Azathothas** [six2dez/reconftw#760]
![image](https://github.com/six2dez/reconftw/assets/58171889/e0e5b0a2-438a-48dd-80c7-3ec69054019e)
Code: https://github.com/six2dez/reconftw/blob/f0eb4c84ee192b89665ffa3ac213cc370a213d05/reconftw.sh#L60C11-L60C14

![image](https://github.com/six2dez/reconftw/assets/58171889/9b9c47f5-1a8b-48ce-a53a-31e38944cfad)

Actual Path: `"$tools/urless/urless/urless.py"`

Git: https://github.com/xnl-h4ck3r/urless/tree/main/urless
![image](https://github.com/six2dez/reconftw/assets/58171889/dc8c4fcf-1685-44ab-a073-39845e0cd076)

---
For anyone looking for a temp fix:
```bash
sed -i 's|$tools/urless/urless.py|$tools/urless/urless/urless.py|g' "./reconftw.sh"
```

**Comment by Hasan-Z** [comment]
Confirmed the correct path is "$tools/urless/urless/urless.py".

**Comment by six2dez** [comment]
Done :) https://github.com/six2dez/reconftw/commit/8b65b97c7a2c9a196ce7b1440591785ae6fea6ba
