### ISSUE TITLE
Linux ARM64 install fail

### ISSUE THREAD

**Issue by edspiner** [six2dez/reconftw#761]
https://github.com/six2dez/reconftw/blob/f0eb4c84ee192b89665ffa3ac213cc370a213d05/install.sh#L361

According to this line when installing on Linux on ARM64 other than RPI4, it will use golang for adm64, which causes issues. Overall I think other parts of the script also use only ARM64 arch if the device is recognised as RPI4

**Comment by six2dez** [comment]
Fixed in https://github.com/six2dez/reconftw/commit/c9143bd98c850ecf89efa608f0c0ca08a0e7be57
