### ISSUE TITLE
Allow custom nuclei-templates installation location/Fix custom installations breaking tool checks.

### ISSUE THREAD

**Issue by Thy-GoD** [six2dez/reconftw#763]
**Is your feature request related to a problem? Please describe.**
No. In the configuration file, the NUCLEI_FLAG configuration allows the changing of nuclei-template's location, but the actual installation location will always be in `$HOME/nuclei-templates.`

![image](https://github.com/six2dez/reconftw/assets/123708601/6ed61d42-6ab8-4a54-b97f-3598911eb5e8)
![image](https://github.com/six2dez/reconftw/assets/123708601/424daf85-0849-4951-a8bd-a26afcd1993c)

**Describe the solution you'd like**
Allow for the install.sh to install the nuclei-templates into a directory specified from configuration file to match the changes in configuration flag.

**Describe alternatives you've considered**
Manually editing it myself.

**Additional context**
I don't want nuclei-templates to be in my home directory.

In addition to this, I've also noticed that a couple of the Configurations don't actually transfer over to the main script while it's checking for tool installations.

For example, if I configure any of the list configurations in the configuration file, while checking for installed tools, Reconftw will not check the custom-installation path.

![image](https://github.com/six2dez/reconftw/assets/123708601/a5f709c7-33de-40b4-b62f-79c6d1b12c16)
![image](https://github.com/six2dez/reconftw/assets/123708601/84a82d3d-4646-4617-9f7b-8d240bdd9669)
![image](https://github.com/six2dez/reconftw/assets/123708601/f494819b-8959-4217-94d2-4f9c2fe201d6)

This also applies to nuclei-templates.

**Comment by six2dez** [comment]
Fixed with https://github.com/six2dez/reconftw/commit/eb6117db9963c1504221c3eaaa49026e8f8d2459

**Comment by Thy-GoD** [comment]
Thanks alot for the fix!
