### ISSUE TITLE
A flag for checking dependencies upgrades before running the scan

### ISSUE THREAD

**Issue by kleozzy** [six2dez/reconftw#766]
I notice a few repos have very frequent updates, like trufflehog, nuclei and some others, would be nice to be able to check somehow the repo before run and quickly update them if needed. Maybe it can be set as a flag for those who wanna skip this. Its a shame to miss some easy bugs etc. because you didn't update before running.

**Comment by AnonymousWP** [comment]
You can update reconFTW by running `install.sh` again, see https://github.com/six2dez/reconftw/tree/main#extras

**Comment by kleozzy** [comment]
That's not what i am talking about, what i am saying is to add a repo check before the actual run (reconftw.sh file) and only update the repos needed since last run.

Running install before every run is not efficient.

**Comment by AnonymousWP** [comment]
In that case, why not just create an `update.sh` script?
