### ISSUE TITLE
Infoga installation does not exist anymore.

### ISSUE THREAD

**Issue by Thy-GoD** [six2dez/reconftw#768]
**Describe the bug**
Infoga does not exist.

**To Reproduce**

1.Run the install script.

**Expected behavior**
Infoga is installed (it no longer exists, so an alternative should be found, or it should be removed.)

**Screenshots**
![image](https://github.com/six2dez/reconftw/assets/123708601/9e73743f-d8dd-45d7-9c58-e941cecfd39a)
![image](https://github.com/six2dez/reconftw/assets/123708601/7c29ff7f-56f4-4bd5-8386-13cbd6eca86c)

**Desktop (please complete the following information):**
- Architecture: x86
 - OS: Kali
 - Version Latest

**Additional context**
😭

**Comment by six2dez** [comment]
https://github.com/six2dez/reconftw/commit/423d64eba0f02fcdc20a9e420a135bad54c209a1 Done
