### ISSUE TITLE
Installation error Failed to cd directory '/root/Tools'

### ISSUE THREAD

**Issue by ikarann** [six2dez/reconftw#773]
I am trying to install the tool in 2 diffrent ubuntu server.

I am getting same error in both pcs. tried installing multiple times. cant seem to find the soultion for this.

Reproduction: 

follow the installation steps on fresh installed linux:

git clone https://github.com/six2dez/reconftw
cd reconftw/
./install.sh

![image](https://github.com/six2dez/reconftw/assets/37656554/8d3a6f36-6461-43e6-acc8-e6e6207080b1)

![image](https://github.com/six2dez/reconftw/assets/37656554/4643e587-c595-4a3f-ba21-d842afbcf6c9)

same error on both machines. can you help in this?

**Comment by ikarann** [comment]
Due to this error when i start recon it instantly stops after 5 minutes with this same error.

**Comment by six2dez** [comment]
Infoga has been removed from repo a few minutes again, update the tool and run it again

**Comment by ikarann** [comment]
Thanks. i replaced install.sh and reconftw.sh from your changed files. 
now the error is gone thanks for this bro. i was stressed due to this from yesterday. thanks again. :)
