### ISSUE TITLE
Docker image missing metafinder

### ISSUE THREAD

**Issue by hupfis** [six2dez/reconftw#788]
**Describe the bug**
I followed the instructions from the readme to run reconftw's docker image:
`sudo docker pull six2dez/reconftw:main`
`docker run -it --rm -v "${PWD}/OutputFolder/":'/reconftw/Recon/' six2dez/reconftw:main -d mydomain.com -r`

The process stopped/failed at the following step:

> Scanning metadata in public files
> metafinder command failed

I checked the OutputFolder/mydomain.com/.log/ file. It shows:
> Start 2023-10-20 00:43:14
> [ 2023-10-20 00:43:14 ] Start function : domain_info 
> [ 2023-10-20 00:43:53 ] End function : domain_info 
> [ 2023-10-20 00:43:53 ] Start function : emails 
> ./reconftw.sh: line 251: emailfinder: command not found
> [ 2023-10-20 00:43:53 ] End function : emails 
> [ 2023-10-20 00:45:22 ] End function : google_dorks 
> [ 2023-10-20 00:45:22 ] Start function : github_dorks 
> [ 2023-10-20 01:18:35 ] End function : github_dorks 
> [ 2023-10-20 01:18:35 ] Start function : github_repos 
> [ 2023-10-20 01:18:35 ] End function : github_repos 
> [ 2023-10-20 01:18:35 ] Start function : metadata 
> ./reconftw.sh: line 207: metafinder: command not found

**To Reproduce**
1. Run `sudo docker pull six2dez/reconftw:main`
2. Run `docker run -it --rm -v "${PWD}/OutputFolder/":'/reconftw/Recon/' six2dez/reconftw:main -d mydomain.com -r`
3. See error

**Expected behavior**
I would expect the docker image to contain all the toolings required to run the sample test script provided in the readme file, which uses -d and -r parameters.

**Screenshots**
![image](https://github.com/six2dez/reconftw/assets/106848/a0379da1-452f-4acf-9b5e-f57e603db555)

**Additional context**
- Docker Image hash: "sha256:faf781ba336689480700fbfb0b10679fb276b10578a4c140dbbddbd3a1cef5ea"
- RepoDigest: "six2dez/reconftw@sha256:be27ccd805b513a281a93879358afb816142b226483e9aada5ce8dbad0d8145f"

**Comment by six2dez** [comment]
Metafinder on Docker image is installed by running the installer, this could be some kind of temporal issue, could you rebuild the container and tell me the results please?

**Comment by cerontrustly** [comment]
Same here...Container was rebuilt several times...

**Comment by jsis483** [comment]
same issue using build via source non docker as well:

**Comment by cerontrustly** [comment]
Managed to solve it by installing the missing _metafinder_ command: `pip3 install metafinder`

**Comment by hupfis** [comment]
I investigated a bit further and it seems the 
`pip3 install -I -r requirements.txt`
fails due to 
`ERROR: Could not find a version that satisfies the requirement postleaksNeg (from versions: none)
ERROR: No matching distribution found for postleaksNeg`
This dependency was added recently - but it cannot be resolved.
I assume this results in many other python-tools not being installed as well.

**Comment by six2dez** [comment]
Fixed requirements
