### ISSUE TITLE
Stuck Http probing non standard ports 

### ISSUE THREAD

**Issue by Ahmadzdddd** [six2dez/reconftw#792]
Http probing non standard ports lasting hours

**To Reproduce**
![image](https://github.com/six2dez/reconftw/assets/142327125/fbf31b17-3f1e-4e53-9bbb-617f2dd36ebd)

**Expected behavior**

**Screenshots**

**Comment by yarovit-developer** [comment]
I thought it was just at  me, now I’m experiencing the same thing...  At this point the scanning stops.

**Comment by six2dez** [comment]
Hey have you checked the process running on your machine? Keep in mind that this process tries to perform http probing on multiple ports and depending the number of subdomains found on your target this could take a long time

**Comment by Ahmadzdddd** [comment]
As a total process it tooks around 2 days to finish one scanning! I guess i modified all according a well scanning!

**Comment by six2dez** [comment]
Well, this depends on multiple factors like your bandwith, the number of assets to scan, etc, not seems to be a bug tbh

**Comment by Ahmadzdddd** [comment]
How can be modified to minimize this time or scanning ports.. as well as for nuclei it tooks around 1 day also!
