### ISSUE TITLE
Why reconftw is only working on this type of IP 192.168.0.1

### ISSUE THREAD

**Issue by spiritboy47** [six2dez/reconftw#793]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- Architecture: [e.g. x86, x64, ARM ...]
 - OS: [e.g. Ubuntu, Kali, Arch ...]
 - Version [e.g. 20.04, Rolling, 8 ...]

**Additional context**

**Comment by six2dez** [comment]
Please provide a more detailed description of the bug or the issue will be closed
