### ISSUE TITLE
specify out of scope on web interface / CLI scans dont show up in web interface

### ISSUE THREAD

**Issue by v4yne1** [six2dez/reconftw#797]
is there a way to specify out of scope on the web interface?

or:

i ran:

`screen -dmS programName bash -c './reconftw.sh -l ~/programs/programName/inscope.txt -x ~/programs/programName/outofscope.txt -r'`

but it doesnt show up in the web-interface. is there a way to achieve CLI ran scans to show up on the web interface, or they show up after the scan has finished?

**Comment by six2dez** [comment]
Hey, web interface is discontinued, in next release it will be removed from the project. Also for the out of scope domains you can define them with `-x` flag, check the help menu ;)

![image](https://github.com/six2dez/reconftw/assets/24670991/a02dc22a-02c1-4995-8297-576f76e175cc)
