### ISSUE TITLE
hakrawler -insecure option not defined

### ISSUE THREAD

**Issue by bileltechno** [six2dez/reconftw#8]
The **-insecure** option in **hakrawler** is disabled.
so the line bellow will fail: 
``` .sh
cat ${domain}_probed.txt | hakrawler -depth 2 -scope subs -insecure -plain | anew -q ${domain}_url_extract.txt
```

My hakrawler version is: beta11

``` .sh
/informationGathering/reconftw$ hakrawler -v
beta11
```

So you need to delete the -insecure option or install hakrawler with -insecure option activated.

**Comment by six2dez** [comment]
I think there is something on your side because -insecure works perfectly for me
![image](https://user-images.githubusercontent.com/24670991/105053973-cce07b00-5a71-11eb-9530-7a75472ff17c.png)
