### ISSUE TITLE
Ideas to improve the result of ffuf scan

### ISSUE THREAD

**Issue by abdilahrf** [six2dez/reconftw#805]
**Is your feature request related to a problem? Please describe.**
Current result of ffuf is missing some of valid result since its using `-ac` (automatic calibration) from ffuf and we can prevent this by using https://github.com/Damian89/ffufPostprocessing

**Describe the solution you'd like**
Using this https://github.com/Damian89/ffufPostprocessing

What do you think about this @six2dez?
 i can create pull request for this one if you don't mind.

**Comment by six2dez** [comment]
I don't dislike the idea, however I would add this as an optional feature, disabled by default, actionable from the reconftw.cfg. Feel free to propose the changes, otherwise I will do it at some point :) Thanks for the idea!

**Comment by kleozzy** [comment]
This has been implemented
