### ISSUE TITLE
Web interface not working for me

### ISSUE THREAD

**Issue by fornitechibi** [six2dez/reconftw#808]
**Describe the bug**
Web interface not working

**To Reproduce**
1. Go to reconftw
2. run ./reconftw --web-server start
3. web sever started with ip address  

**Expected behavior**
ip address should working popping up a login page

**Unexpected behaviour**
But ip address not working, it's getting timeout

**Comment by six2dez** [comment]
Web interface is not working anymore and will be removed on next release
