### ISSUE TITLE
Smuggler results go into the wrong folder

### ISSUE THREAD

**Issue by kleozzy** [six2dez/reconftw#818]
Ive noticed that several results from the smuggler tool , go into the wrong target folder. 

For example when checking the folders of target a1.com , i see smuggler results under vulns/smuggler for domain b1.com.

**Comment by 0-0eth0** [comment]
Strange, i haven't faced this issue! Let me check on a fresh installation

**Comment by kleozzy** [comment]
its fixed for quite a while now :)
