### ISSUE TITLE
nmap scanned ports documentation inconsistent

### ISSUE THREAD

**Issue by roman-mueller** [six2dez/reconftw#824]
**Describe the bug**
On the output files wiki page (https://github.com/six2dez/reconftw/wiki/6.-Output-files) it states that the top-ports 1000 ports are being scanned with nmap.
But in the code only 200 are set: https://github.com/six2dez/reconftw/blob/85f17a01f23def73e5e6bf8e65fbb7930d9e1396/reconftw.sh#L1523 
and
https://github.com/six2dez/reconftw/blob/85f17a01f23def73e5e6bf8e65fbb7930d9e1396/reconftw.sh#L1525
I'm unable to modify the wiki.
Can you update the wiki?
Or should the 200 limit be changed to 1000?

**To Reproduce**
Check above links.

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by six2dez** [comment]
Hey, thanks for this, the wiki needs a complete rewrite :) Fixed the wiki
