### ISSUE TITLE
 Issue with Metafinder Command Failure in Recon Mode 

### ISSUE THREAD

**Issue by VarmaKollu** [six2dez/reconftw#827]
**Describe the bug**
I encountered an issue with the Metafinder command in Recon Mode, where the command failed to execute as expected. This problem prevents me from obtaining recon results.

when I run metafinder separately it works fine but doesn't work on the tool

**Screenshots**
![image](https://github.com/six2dez/reconftw/assets/82416847/66ad7b30-453a-41cd-bc1d-48dd9fd4097d)

![image](https://github.com/six2dez/reconftw/assets/82416847/9c93a2cf-c6cb-49bb-95ec-a0d53ad25522)

**Desktop (please complete the following information):**
 - OS:  Kali Linux

**Comment by six2dez** [comment]
Which branch and version of reconftw are you using? Which is your python3 version?

**Comment by six2dez** [comment]
Try again switching to dev version, reinstall on dev branch and let me know the exact reconftw command running if that does not works

**Comment by jakre1234** [comment]
True, metafinder failing every time. I added the comment on a previously closed issue and was about to create a new issue but saw this one.
Metafinder works fine when ran manually but fails every time in reconftw

**Comment by jakre1234** [comment]
main branch, latest version. Tried twice with different domains and happens everytime. On tapping ctrl+c whole reconftw exits.

**Comment by six2dez** [comment]
There might be something with your OS, nobody is reporting me this issue :/

**Comment by jakre1234** [comment]
I am on debian

**Comment by jakre1234** [comment]
Every single time :/
![reconFTWetaFail](https://github.com/six2dez/reconftw/assets/89703702/863093d1-b75b-449b-927d-49031075a7cb)

**Comment by rohsec** [comment]
I think they got a point, but this seems like a metafinder's problem. The tool seems to be causing errors when supplied with the baidu -ba flag 
This is from a manual metafinder run replicating reconftw's command ```metafinder example.com -l 20 -o osint -go -bi -ba```
```
|_ Usage: metafinder -d domain.com -l 50 -o /tmp -go -bi

Searching in google
[+] Done

Searching in bing
[+] Done

Searching in baidu
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err

```
And I think it's primarily due to local ISP, if you are in India and running reconFTW locally then try removing the ```-ba``` flag from the command in the ```reconftw.sh``` file 

Happy Hacking :)
