### ISSUE TITLE
error during install reconftw

### ISSUE THREAD

**Issue by cybersecuz** [six2dez/reconftw#828]
Failed to fetch updates.

![Screenshot from 2024-02-04 13-22-44](https://github.com/six2dez/reconftw/assets/61209486/fac89964-9e43-43a9-9a49-d10c3cbb48d0)
![Screenshot from 2024-02-04 13-23-15](https://github.com/six2dez/reconftw/assets/61209486/9c64f45e-f943-4114-bffa-fdf3e61626f0)

**Comment by six2dez** [comment]
Do not run with sudo, also spotted a bug and fixed on dev

**Comment by six2dez** [comment]
Are you sure you have access to GitHub and public network access? Because your problem is a bit strange
