### ISSUE TITLE
instalation problems

### ISSUE THREAD

**Issue by Lolles132** [six2dez/reconftw#829]
Checking installed tools

 [*] emailfinder                [NO]
 [*] ripgen                     [NO]
 [*] trufflehog                 [NO]
 [*] porch-pirate                       [NO]

 Try running the installer script again ./install.sh
 If it fails for any reason try to install manually the tools missed
 Finally remember to set the ${tools} variable at the start of this script
 If nothing works and the world is gonna end you can always ping me :D
 
using wls2 ubuntu
 also
 `Traceback (most recent call last):
  File "/root/Tools/dorks_hunter/dorks_hunter.py", line 7, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'
dorks_hunter command failed`
Python 3.12.1, pip 24.0

**Comment by six2dez** [comment]
WSL is not supported by anyway or form

**Comment by Lolles132** [comment]
had same problem while use debian 11, python 3.11.5...
