### ISSUE TITLE
reconFTW: invalid option -- 'w' but --web is working

### ISSUE THREAD

**Issue by muX1337** [six2dez/reconftw#831]
**Describe the bug**

Running the script as described in the usage:
 Perform Web based scanning on a subdomains list:
 ./reconftw.sh -d example.com -l targets.txt -w
and 
 ./reconftw.sh -l targets.txt -w

Isn't working and only shows the usage again. As a Workaround the following command is working:
 ./reconftw.sh -l targets.txt --web

**To Reproduce**
1. Create any subdomain-list
2. Start recon with either ./reconftw.sh -l targets.txt -w or  ./reconftw.sh -d example.com -l targets.txt -w
3. reconFTW: invalid option -- 'w'

**Expected behavior**
Same as --web is doing

**Screenshots**
./reconftw.sh -l example.txt -w
![grafik](https://github.com/six2dez/reconftw/assets/9527130/25248e9d-5b61-4a37-9789-577fc0100788)

./reconftw.sh -l example.txt --web
![grafik](https://github.com/six2dez/reconftw/assets/9527130/2725504f-dabd-4dc4-a6f6-03e7bbe3e6f2)

**Desktop (please complete the following information):**
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

**Additional context**

I just skipped throught the code and the case got both in it:
`'-w' | '--web')
		opt_mode='w'
		shift
		continue
		;;`

It looks more like an issue with order of the params in combination with the shift at the cases but no clue so far why --web is working but not -w

I have also added -d and any name but with the same result.

//Edit:
Somehow the argument -w is interpreted as --, here the output of the current argument before the case:
 ./reconftw.sh -l example.txt -w                                                                                                                                                                       reconFTW: invalid option -- 'w'
argv is -l
argv[3] is --
argv is --
argv[3] is
#############################################
./reconftw.sh -l example.txt --w
argv is -l
argv[3] is --web
argv is --web
argv[3] is
argv is --
argv[3] is
##############################################
 ./reconftw.sh -l example.txt -r                                                                                                                                                                       argv is -l
argv[3] is -r
argv is -r
argv[3] is
argv is --
argv[3] is

Same issue on Ubuntu 22.04.3 LTS (jammy):
./reconftw.sh -l example.txt -w
reconFTW: invalid option -- 'w'

**Comment by six2dez** [comment]
Fixed https://github.com/six2dez/reconftw/commit/71f6150b9803fe5a428e25c2b4103ea9efe5d0ef
