### ISSUE TITLE
##### ERROR [628][domain_info|recon|all|main] timeout -k 1m ${AMASS_INTEL_TIMEOUT}m amass intel -d ${domain} -whois -timeout $AMASS_INTEL_TIMEOUT -o osint/domain_info_reverse_whois.txt 2>> "$LOGFILE" >> /dev/null #####

### ISSUE THREAD

**Issue by black-arch7** [six2dez/reconftw#845]
![image](https://github.com/six2dez/reconftw/assets/61597442/2a5fbbc5-973f-4aef-bd6b-5c49c771fb83)

Having this issue , please suggest .
Website is UP . My internet is working, even all other tools are properly installed.

**Comment by six2dez** [comment]
Fixed a few mins ago, please do git pull and rerun
