### ISSUE TITLE
running install.sh wipes .zshrc file

### ISSUE THREAD

**Issue by reevesy1** [six2dez/reconftw#851]
Trying to update using install.sh wipes your .zshrc file replacing it with only 

```
# Golang vars
export GOROOT=/usr/local/go
export GOPATH=\$HOME/go
export PATH=\$GOPATH/bin:\$GOROOT/bin:\$HOME/.local/bin:\$PATH
```
Now this quite possibly could've been something I accidentally done while getting some tools to work, but i'm leaning more towards something that was updated as it happened straight after it said there was an update available and ran the install.sh file.

**To Reproduce**
1. cd to reconftw folder
2. Run install file ```./install.sh```
3. Notice your terminal is different and it asks you repeatedly to make password for new keyring ( thats possibly once you run reconftw.sh )
4. Wonder WTF happened and check your .zshrc file to see all your settings etc are gone
5.  Think you had a back up until you realise you don't and end up copy pasting roots .zshrc contents.
6. Deal with now having lost all your history, auto complete, terminal look like crap. 
7. Start googling to see if there is a way to get the file back to however it was before it got replaced.
8. I haven't made it to step 8 yet. Will let you know.

**Expected behavior**
Running install.sh updates any tools that need updating and doesn't modify/overwrite important files that it doesnt need to touch 

**Desktop (please complete the following information):**
Linux 6.6.9-rt-amd64 #1 SMP PREEMPT_RT Kali 6.6.9-1kali1 (2024-01-08) x86_64 GNU/Linux

**Additional**
If someone could confirm it is an update that is doing it and not something I done, that would be great.

**Comment by thechiragjogani** [comment]
Something you have done, working fine for me.
