### ISSUE TITLE
Missing `grep $domain` Command in `webprobe_full()` Function

### ISSUE THREAD

**Issue by borhanDZ** [six2dez/reconftw#859]
I would like to point out that what is stated here might not be of utmost importance or is considered a mistake, in my opinion.
### Details:

- **Function Assigned :** `webprobe_full()` at line 1432.
- **Issue:** The `grep $domain` code snippet is missing.
- **Observation:** 
    - In the function `webprobe_simple()` at line 1395, a similar command semantic is present.
    - However, this command is missing in `webprobe_full()` at line 1432.
 `... cat .tmp/web_full_info_uncommon.txt | jq -r 'try . |"\(.url) [\(.status_code)] [\(.title)] [\(.webserver)] \(.tech)"' | anew -q webs/web_full_info_uncommon_plain.txt`
    
### Suggestion:

It might be beneficial to apply the `grep $domain` filter to multiple domains, rather than just `example.com`. For instance, in the target, there could be variations like `example.com|net|de|io|co`. 

### Conclusion:

Thank you for creating this wonderful script. This feedback is provided with the intention of improving it further.

**Comment by six2dez** [comment]
Thx! Fixed on dev branch, I will push to main soon :)
