### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by yaahiaa** [six2dez/reconftw#86]
how to add ssrf server env var?

**Comment by detonxx** [comment]
Please checkout the Installation guide in wiki
[SSRF Server](https://github.com/six2dez/reconftw/wiki#SSRF-Server)
Please make an account any of those 3-party websites and then add your server in your terminal's configuration as an environment variable value.(.bashrc,.zshrc)
`COLLAB_SERVER=<your server address>`

**Comment by yaahiaa** [comment]
thanks
