### ISSUE TITLE
/root/reconftw/reconftw.cfg: line 56: 3RD_PARTIES=true: command not found

### ISSUE THREAD

**Issue by GDATTACKER-RESEARCHER** [six2dez/reconftw#873]
/root/reconftw/reconftw.cfg: line 56: 3RD_PARTIES=true: command not found

**Comment by six2dez** [comment]
Your Reconftw.cfg file is outdated, please update it and run again

**Comment by GDATTACKER-RESEARCHER** [comment]
Nah using the latest one i though the same earlier but later redownloaded and check but same issue

**Comment by six2dez** [comment]
Done :) I just forgot only valid beginning character types for bash variables are letters and underscores :D fixed here https://github.com/six2dez/reconftw/pull/874
