### ISSUE TITLE
tool stuck on "searching for 3rd party misconfigurations"

### ISSUE THREAD

**Issue by atharvak95** [six2dez/reconftw#877]
after running ./reconftw.sh on target, it runs fe OSINT steps & then gets stuck on "searching for 3rd party misconfigurations"

**To Reproduce**
just run the tool from kali linux WSL on a target like "./reconftw.sh -d redacted.com -r" after adding all the API keys

**Expected behavior**
if it's unable to find data after a certain time, it should skip & move to the next step.

refer to this - ![image](https://github.com/six2dez/reconftw/assets/85757680/4f3042ec-31e1-4e16-82dd-9e4972c35b3b)

**Am running kali linux WSL**

**Comment by six2dez** [comment]
The tool for checking third parties misconfigurations already has a default timeout of 7000 ms per request but it performs a bunch of requests, not seems to be related to reconftw or misconfig-mapper if you're not able to provide more info.
