### ISSUE TITLE
p1radup script is missing in ./install.sh and ./reconftw don't warn of missing p1radup tool before launch.

### ISSUE THREAD

**Issue by rahisec** [six2dez/reconftw#878]
**Describe the bug**
p1radup is a tool which deduplicates urls which is used in ./reconftw.sh . but its missing in install script. upon running the `./reconftw.sh -d web.com -r ` at the deduplication phase it throw error.

**Comment by six2dez** [comment]
p1radup is is installed during the installation scripts run, is included at the requirements.txt file and it's installed by pip
