### ISSUE TITLE
Add IP2WHOIS API as an option to query WHOIS data

### ISSUE THREAD

**Issue by ip2location** [six2dez/reconftw#879]
**Is your feature request related to a problem? Please describe.**
Good to give options to users so that they can utilize other API for WHOIS data such as [IP2WHOIS API](https://www.ip2whois.com/).

**Describe the solution you'd like**
More API options will give users more flexibility.

**Describe alternatives you've considered**

**Additional context**

**Comment by six2dez** [comment]
Thanks for the suggestion but it's more about offering the option I find suit better for most of the users other than giving multiple options for the same goal.
