### ISSUE TITLE
Not having /root/Tools/.github_tokens 

### ISSUE THREAD

**Issue by 18CE047** [six2dez/reconftw#880]
Hello sir, I have installed ReconFTW and when I am running it I am getting these 2 errors

1. whois command failed 
2. [2024-05-30 18:47:05] Required file /root/Tools/.github_tokens not exists or empty 

For the first error I tried "apt-get install whois" but it is not working
and for error 2, I don't know how to proceed further. Do I need to make a file with "nano .github_tokens" and just need to put my API tokens or something else?

Kindly help me in this troublesome situation.

**Comment by six2dez** [comment]
Hi, 

sometimes whois command fails for a various number of reasons, try to run it strandalone by yourself to check the error.

About the .github_tokens issue check the docs https://github.com/six2dez/reconftw/wiki/1.-Post-Installation-Guide#2-github-tokens

**Comment by 18CE047** [comment]
hey I have followed all of the steps mentioned here https://github.com/six2dez/reconftw/wiki/1.-Post-Installation-Guide#2-github-tokens. But there is no file name like /root/Tools/.github_tokens

what should I do? Do I need to make a file name .github_tokens and adding my tokens inside that file?

**Comment by six2dez** [comment]
Yes, you have to create it by your own :)
