### ISSUE TITLE
Third parties misconfigurations: Invalid Escape Sequence

### ISSUE THREAD

**Issue by boffman** [six2dez/reconftw#881]
**Describe the bug**
I just tried out the tool for the first time and got this error message along the way (./reconftw.sh -d <domain> -r):

```
[2024-06-02 12:36:26] Searching for third parties misconfigurations
panic: regexp: Compile(`Illuminate\Foundation\Bootstrap\HandleExceptions::handleError`): error parsing regexp: invalid escape sequence: `\F`

goroutine 1 [running]:
regexp.MustCompile({0xc0000f6240, 0x3d})
        /usr/local/go/src/regexp/regexp.go:317 +0xb4
main.checkResponse(0xc000246280, 0xc0004d7bb0, 0xc000094a80)
        /home/kali/Tools/misconfig-mapper/main.go:353 +0xbd1
main.main()
        /home/kali/Tools/misconfig-mapper/main.go:608 +0x1390
```

**To Reproduce**
`./reconftw.sh -d <redacted> -r`

**Expected behavior**
no error about invalid escape sequence

**Screenshots**
n/a

**Desktop (please complete the following information):**
as of 2024-06-02:
fresh Kali Linux in VirtualBox
newly cloned reconFTW

**Additional context**
n/a

**Comment by six2dez** [comment]
I can't reproduce this error, try running the misconfig-mapper tool standalone. From the misconfig-mapper path ($HOME/Tools/misconfig-mapper) run `./misconfig-mapper -target COMPANYNAME_OR_DOMAIN -service "*"` and check if the error still occurs, if so please report the error to the following repository https://github.com/intigriti/misconfig-mapper

**Comment by gearcapitan** [comment]
i have the same errror :S 
![imagen](https://github.com/six2dez/reconftw/assets/13740942/100908c4-7a71-49b3-82e8-01d91e7af7aa)

**Comment by gearcapitan** [comment]
![imagen](https://github.com/six2dez/reconftw/assets/13740942/4ebe51b3-6839-40c0-8739-288f4a282d1d)

**Comment by six2dez** [comment]
Please report this issue to misconfig-mapper repository at https://github.com/intigriti/misconfig-mapper as reconftw cannot fix anything here
