### ISSUE TITLE
install.sh: line 137: go: command not found

### ISSUE THREAD

**Issue by littlAcen** [six2dez/reconftw#893]
i tried to install ur tool on my ionos vserver and everytime i start the script it says:

install.sh: line 137: go: command not found
 Unable to install inscope, try manually (1/46)
 Unable to install hakip2host, try manually (2/46)
 Unable to install puredns, try manually (3/46)
 Unable to install interactsh-client, try manually (4/46)
 Unable to install nuclei, try manually (5/46)
 Unable to install analyticsrelationships, try manually (6/46)
 Unable to install crt, try manually (7/46)
 Unable to install nmapurls, try manually (8/46)
 Unable to install dnsx, try manually (9/46)
 Unable to install gitlab-subdomains, try manually (10/46)
 Unable to install dalfox, try manually (11/46)
 Unable to install gitdorks_go, try manually (12/46)
 Unable to install roboxtractor, try manually (13/46)
 Unable to install gau, try manually (14/46)
 Unable to install Gxss, try manually (15/46)
 Unable to install katana, try manually (16/46)
 Unable to install mapcidr, try manually (17/46)
 Unable to install brutespray, try manually (18/46)
 Unable to install sns, try manually (19/46)
 Unable to install qsreplace, try manually (20/46)
 Unable to install notify, try manually (21/46)
 Unable to install dsieve, try manually (22/46)
 Unable to install gotator, try manually (23/46)
 Unable to install ppmap, try manually (24/46)
 Unable to install subfinder, try manually (25/46)
 Unable to install smap, try manually (26/46)
 Unable to install crlfuzz, try manually (27/46)
 Unable to install sourcemapper, try manually (28/46)
 Unable to install jsluice, try manually (29/46)
 Unable to install Web-Cache-Vulnerability-Scanner, try manually (30/46)
 Unable to install cdncheck, try manually (31/46)
 Unable to install httpx, try manually (32/46)
 Unable to install ffuf, try manually (33/46)
 Unable to install subjs, try manually (34/46)
 Unable to install github-endpoints, try manually (35/46)
 Unable to install unfurl, try manually (36/46)
 Unable to install anew, try manually (37/46)
 Unable to install gf, try manually (38/46)
 Unable to install shortscan, try manually (39/46)
 Unable to install tlsx, try manually (40/46)
 Unable to install mantra, try manually (41/46)
 Unable to install github-subdomains, try manually (42/46)
 Unable to install enumerepo, try manually (43/46)
 Unable to install amass, try manually (44/46)
 Unable to install s3scanner, try manually (45/46)
 Unable to install dnstake, try manually (46/46)

how can i fix that? =)

PEACE!

**Comment by Krish123na** [comment]
@littlAcen  how did you fix your issues ?? please reply.....
