### ISSUE TITLE
Consider to add support for IP2Location.io as a fallback

### ISSUE THREAD

**Issue by ip2location** [six2dez/reconftw#901]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add IP2Location.io API into this project.

Our service provided 500 queries per day for keyless query, or 30000 queries per month if you sign up our free plan. You can read more on the result returned via [our documentation](https://www.ip2location.io/ip2location-documentation).

**Describe alternatives you've considered**
Not related.

**Additional context**
Not related.

**Comment by abdullahdevrel** [comment]
Just for context:

![IPinfo vs IP2Location](https://github.com/user-attachments/assets/b196a40d-ee6b-4467-89a5-82064c846376)


- IPinfo.io provides 1,000 requests per day without a token.
- IPinfo provides 50,000 requests per month with a free tier token.
- Universal access to a globally distributed load-balancing network regardless of access tier.
- Higher accuracy driven by latency-based IP geolocation methods. ([Blog post](https://ipinfo.io/blog/probe-network-how-we-make-sure-our-data-is-accurate/))

In addition to offering generous no-tier and free-tier access, we also have incredible uptime hours. If access or limits to our service is an issue, we are happy to look into it. Thanks.
