### ISSUE TITLE
domain_info() -> curl aadinternals.azurewebsites.net error

### ISSUE THREAD

**Issue by idlefire** [six2dez/reconftw#904]
**Describe the bug**
Can't Work. Add Header `Referer` and `User-Agent`.

**Screenshots**
![image](https://github.com/user-attachments/assets/e93c42fc-e157-4c2e-8e21-8f7f8363a3e6)
![image](https://github.com/user-attachments/assets/b9ccac9e-0e53-45db-8b20-8829f8081933)

**Desktop (please complete the following information):**
- Architecture:  x64
 - OS: Ubuntu
 - Version 22

**Comment by six2dez** [comment]
Will be fixed in next commit for dev version later today :)

**Comment by idlefire** [comment]
OK it is good
