### ISSUE TITLE
aquatone replacement 

### ISSUE THREAD

**Issue by bileltechno** [six2dez/reconftw#93]
**eyewitness**, **gowitness** or **webscreenshot**

**Comment by bileltechno** [comment]
> Target z***.com
### Gowitness
```.js
cat ${domain}_probed.txt | aquatone -out screenshots -threads 8 -silent
```

Web Screenshot Finished in 50 seconds.
Results are saved in in screenshots/aquatone_report.html folder

### Aquatone
```.js

```

**Comment by six2dez** [comment]
I don't find any trouble with webscreenshot, in fact it works really nice:

```
git clone https://github.com/maaaaz/webscreenshot
cd webscreenshot
pip3 install -r requirements.txt
python3 webscreenshot.py -i url_list.txt -w 8 -a "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" -o screens_folder
```

Will implement this

**Comment by six2dez** [comment]
Done d06c25b101cc96d6ffc2f44efa07e4b44b2d63eb
